### ISSUE TITLE
CIDER erroneously complaining about cider-nrepl version

### ISSUE THREAD

**Issue by canweriotnow** [clojure-emacs/cider#961] opened 2015-01-28 18:21 UTC
I've done everything up to and including reverting to stable, moving cider/cider-nrepl requirement to project.clj instead of .lein/profiles.clj, and clobbering my .emacs.d and doinf a fresh prelude install.

In every case, I get the following:

CIDER:
```
; CIDER 0.9.0snapshot (package: 20150126.1253) (Java 1.8.0_25, Clojure 1.7.0-alpha5, nREPL 0.2.6)
WARNING: The following required nREPL ops are not supported: 
apropos classpath complete eldoc info inspect-start inspect-refresh inspect-pop inspect-push inspect-reset macroexpand ns-list ns-vars resource stacktrace toggle-trace-var toggle-trace-ns undef
Please, install (or update) cider-nrepl 0.9.0-SNAPSHOT and restart CIDER
clerestory.repl> 
```
I've wiped my ~/.m2 and reinstalled cider-nrepl with `lein-deps` just to be sure, and I have the latest cider-nrepl from clojars.
`lein deps :tree`:

```
[cider/cider-nrepl "0.9.0-20150118.121230-2"]
   [cljs-tooling "0.1.3" :exclusions [[org.clojure/clojure]]]
   [compliment "0.2.1-20141130.115631-1" :exclusions [[org.clojure/clojure]]]
     [defprecated "0.1.1"]
   [org.clojure/java.classpath "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.namespace "0.2.5" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.trace "0.7.8" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
```

I've been trying various combinations for about 3 hours now. It's only been an issue since I ran `M-x prelude-update` yesterday. 

Filing here since I'm guessing it's a CIDER issue (rather than cider-nrepl), but any suggestions are welcome.

**Comment by bbatsov** [comment] 2015-01-28 19:32
Can't imagine what could have caused this. There have been only very small changes the past couple of months.

**Comment by sunng87** [comment] 2015-02-02 07:46
Having the same issue from me. I'm on MELPA channel and current cider version is 20150201 and cider-nrepl is updated to snapshot of 20150201. The issue is still there.

Also this breaks functionalities like `alt+.`

**Comment by scottdw** [comment] 2015-02-02 10:00
Is this from a fresh install of the cider emacs package or from an update? If it is from an update I would suggest removing the cider package and reinstalling it (possibly restarting emacs in between actions). From #646 it seems that there can be issues byte compiling on upgrade.

**Comment by sunng87** [comment] 2015-02-02 10:37
Thanks @scottdw , I have reinstalled cider but the issue is still there. I am getting warning:

> ; CIDER 0.9.0snapshot (package: 20150201.1117) (Java 1.8.0_31, Clojure 1.6.0, nREPL 0.2.6)
WARNING: The following required nREPL ops are not supported: 
apropos classpath complete eldoc info inspect-start inspect-refresh inspect-pop inspect-push inspect-reset macroexpand ns-list ns-vars resource stacktrace toggle-trace-var toggle-trace-ns undef
Please, install (or update) cider-nrepl 0.9.0-SNAPSHOT and restart CIDER

**Comment by scottdw** [comment] 2015-02-02 10:57
Are you adding cider-nrepl to `:dependencies` or `:plugins` in your lein `profiles.clj`/`project.clj`?  It should be under `:plugins`.

**Comment by ck** [comment] 2015-02-02 13:00
FWIW, I have same issue: 

    ; CIDER 0.9.0snapshot (package: 20150201.1117) (Java 1.7.0_71, Clojure 1.6.0, nREPL 0.2.6)
    WARNING: The following required nREPL ops are not supported:  
    apropos classpath complete eldoc info inspect-start inspect-refresh inspect-pop inspect-push inspect-    reset macroexpand ns-list ns-vars resource stacktrace toggle-trace-var toggle-trace-ns undef
    Please, install (or update) cider-nrepl 0.9.0-SNAPSHOT and restart CIDER

Reinstalled Prelude and cider-nrepl as well without luck.

**Comment by scottdw** [comment] 2015-02-02 13:17
Please post your `profiles.clj` or `project.clj`, wherever you are referencing `[cider/cider-nrepl "0.9.0-SNAPSHOT"]`

**Comment by sunng87** [comment] 2015-02-02 13:28
my profiles.clj:

```clj
{:user
 {:plugins [[environ/environ.lein "0.3.0"]
            [lein-set-version "0.4.1"]
            [lein-simpleton "1.1.0"]
            [lein-try "0.4.1"]
            [lein-ancient "0.5.5"]
            [cider/cider-nrepl "0.9.0-SNAPSHOT"]
            [venantius/ultra "0.1.9"]]

  :hooks [environ.leiningen.hooks]}}
```

**Comment by scottdw** [comment] 2015-02-02 13:50
The only way I can reproduce this error is if I incorrectly specify `cider-nrepl` under `:dependencies` rather than `:plugins`. But your `profiles.clj` looks fine so I'm running out of ideas.

**Comment by ck** [comment] 2015-02-02 14:02
Thanks to sunng87 posting his profiles file and comparing it to mine, I think I found the culprit.

If I comment out `venantius/ultra`, cider starts up normally.

**Comment by sunng87** [comment] 2015-02-02 14:26
Exactly!

**Comment by bbatsov** [comment] 2015-02-02 15:17
Guess this `ultra` project doing something nREPL related as well. I'm not familiar with it.

**Comment by bbatsov** [comment] 2015-02-02 15:20
`ultra` depends on a lot of things, so I'm not surprised it's causing breakages. Guess someone should report the CIDER issue upstream.

**Comment by anildigital** [comment] 2015-02-14 20:28
I am also getting this error.

cider-nrepl 0.9.0-SNAPSHOT and restart CIDER

I am not using ultra.

**Comment by expez** [comment] 2015-02-14 20:54
@anildigital are you using [pretty](https://github.com/AvisoNovate/pretty)?

**Comment by anildigital** [comment] 2015-02-15 04:36
@expez nope, I am not using pretty.

**Comment by venantius** [comment] 2015-02-16 06:02
Ultra author, here. I don't believe it's pretty; I think it's Whidbey and the nREPL middleware that are the root of the issue. At the moment it's not quite clear how the two are interfering with each other, though my guess is that Ultra does something with the nREPL middleware that causes CIDER to get the boot. I'm not an emacs user so I'm afraid I'm fairly unfamiliar with CIDER's configuration; I'd love to get this working for people, though.

**Comment by nickzam** [comment] 2015-02-19 10:27
Hi, same problem here, I am using emacs-live with cider 0.8.1

; CIDER 0.8.1 (Java 1.8.0_31, Clojure 1.6.0, nREPL 0.2.6)
WARNING: The following required nREPL ops are not supported: 
apropos classpath complete eldoc info inspect-start inspect-refresh inspect-pop inspect-push inspect-reset macroexpand ns-list ns-vars resource stacktrace toggle-trace-var toggle-trace-ns undef
Please, install (or update) cider-nrepl 0.8.1 and restart CIDER
user> 

my profiles.clj:
{:user {:plugins [[cider/cider-nrepl "0.8.1"]]}}

I don't have :plugins section in my project.clj. Also I am not using venantius/ultra and pretty.
Cleaning ~/.m2 and reinstalling cider-nrepl doesn't help.

**Comment by venantius** [comment] 2015-02-22 03:08
I believe the latest release of Ultra, `0.2.1`, should fix this. For those of you feeling adventurous, please update and let me know if you're still experiencing the issue.

**Comment by venantius** [comment] 2015-02-22 03:09
Pinging @bbatsov so he can close this if my assumptions prove correct.

**Comment by bbatsov** [comment] 2015-02-22 06:20
@venantius Thanks for looking into this! I'll close the ticket as soon as someone confirms the problem's no more.

**Comment by tsdh** [comment] 2015-03-02 09:18
Not sure if I have the same problem but since a week or so I get the following warning after `cider-jack-in`.

```
; CIDER 0.9.0snapshot (package: 20150301.936) (Java 1.8.0_31, Clojure 1.7.0-alpha5, nREPL 0.2.6)
WARNING: CIDER requires nREPL 0.2.7 to work properly
```
I don't have explicit deps for nREPL but only for `cider-nrepl` in my `~/.lein/profiles.clj`.

```clojure
{:user {:plugins [[lein-ancient "0.6.3"]
                  [cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [jonase/eastwood "0.2.1"]
                  [lein-try "0.4.3"]]
        :dependencies [[im.chit/vinyasa "0.3.3"]
                       [spyscope "0.1.5"]
                       [org.clojars.gjahad/debug-repl "0.3.3"]
                       [criterium "0.4.3"]
                       [org.clojure/tools.namespace "0.2.10"]]
        :injections [;; See https://github.com/zcaudate/vinyasa
                     (require 'vinyasa.inject)
                     ;; See https://github.com/dgrnbrg/spyscope
                     (require 'spyscope.core)
                     ;; See https://github.com/georgejahad/debug-repl
                     (require 'alex-and-georges.debug-repl)
                     (vinyasa.inject/in
                      [clojure.repl doc source]
                      [clojure.pprint pprint pp]
                      [clojure.tools.namespace.repl refresh refresh-all]
                      [criterium.core bench quick-bench]
                      [alex-and-georges.debug-repl debug-repl])]}
 :docs {:plugins [[lein-html5-docs "2.2.0"]
                  [lein-marginalia "0.8.0"]]}}
```

**Comment by bbatsov** [comment] 2015-03-02 09:31
The current stable `lein` pulls in 0.2.6, which is buggy. Most things will work fine, but one still needs 0.2.7 (especially for ClojureScript) for absolutely everything to work as it's supposed to. So, until we have a new lein release people will have to deal with this manually.

**Comment by tsdh** [comment] 2015-03-02 10:08
@bbatsov Ah, thank you.

**Closed** 2015-03-03 21:54 UTC

**Comment by nklein** [comment] 2015-03-27 13:35
@bbatsov, How does one "deal with this manually"?  I tried [this recommendation](http://stackoverflow.com/questions/28688721/how-to-upgrade-nrepl-version-of-leiningen) and did not get it to work.  My entire ~/.lein/profiles.clj is:

    {:user {:plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]]
            :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}

And, I know it is getting read because it wigs out if I try asking for version 9.2.7 instead of 0.2.7.  Thanks.

**Comment by expez** [comment] 2015-03-27 13:43
AFAIK there's nothing to be done about this due to the way lookup in the classloader chain works. Since the classloader at the top of the hierarchy is checked first, and  Lein owns one of those, whatever version lein loads is what you get (I think lein loads 0.2.6 atm, but that's changed on master).

**Comment by cichli** [comment] 2015-03-27 14:54
You can add the tools.nrepl dependency to the `:dev` profile to override the lein default (this also stumped me for a while).

**Comment by nklein** [comment] 2015-03-27 19:04
@cichli This has not helped me.  The REPL still starts using nREPL "0.2.6" no matter what version I put in depencies.  I'm a total newbie with Leiningen though, and this all seems like arcana.  So, I'm not sure if I'm even close:

    {:dev {:dependencies [[org.clojure/tools.nrepl "0.2.10"]]
           :plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]]}
     :user {:dependencies [[org.clojure/tools.nrepl "0.2.10"]]
            :plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]]}

**Comment by evrusc** [comment] 2015-03-27 23:23
@nklein I had the same thing happen today.  I'm new to this too but I did notice this: 

The warning shows if I try to cider-jack-in from an empty scratch buffer right after I start emacs, and cider loads nREPL 0.2.6.

It does NOT show the warning if I have a clojure file open before doing cider-jack-in, and cider loads nREPL 0.2.7.

**Comment by nklein** [comment] 2015-03-27 23:39
@evrusc Interesting.  I had been starting it sometimes from the *scratch* buffer and sometimes from editing profiles.clj.  But, I switched to an older version of CIDER before I bothered making a new project so I never tried in a directory that had a project.clj.

**Comment by MatthewWest** [comment] 2015-04-01 20:24
I've been trying to figure this out for a while, and @evrusc's advice works—it works when opening a nREPL from a file that's a part of a lein project already. If I try doing it for a stand-alone Clojure file, it fails.

**Comment by bbatsov** [comment] 2015-04-01 20:32
Looks like a leiningen bug to me. It doesn't make much sense to behave differently inside and outside of a project.

**Comment by peterfoldi** [comment] 2015-04-06 17:37
Adding the dependency on 0.2.7 worked for a while then some days later the warning returned. I guess some plugin's dependency caused 0.2.6 to load. For me adding the ^:replace meta to the dependency solved it. Now I have this in my profiles.clj dependency array:

    ^:replace [org.clojure/tools.nrepl "0.2.7"]

**Comment by arnab** [comment] 2015-04-09 23:13
Could it be that cider is reporting the `tools.nrepl` version instead of the `cider-nrepl` version?

Here's my `profiles.clj`:
```
{:user {:plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}
```

... and cider shows: `; CIDER 0.9.0snapshot (package: 20150303.1353) (Java 1.7.0_75, Clojure 1.6.0, nREPL 0.2.10)`.

If I change the `tools.nrepl` version to `0.2.7` then cider also reports that it's seeing `nrepl 0.2.7`.

**Comment by woozong** [comment] 2015-04-13 08:23
Hi Arnab, that worked beautifully for me.

**Comment by Davidbhodge** [comment] 2015-04-25 02:36
Using Arnabs profiles.clj on a completely fresh install,with a recently (last night)  download cider from melpa, I note that if I start CIDER within a project then all is fine, I get the right version of nrepl. If I start the nrepl outside a project i get the 0.2.6 version. 

HTH

**Comment by paomian** [comment] 2015-04-28 09:24
Having the same issue from me,but just can't use refresh
```
; CIDER 0.9.0snapshot (package: 20150427.2358) (Java 1.7.0_67, Clojure 1.6.0, nREPL 0.2.10)
WARNING: The following required nREPL ops are not supported: 
refresh
Please, install (or update) cider-nrepl 0.9.0-SNAPSHOT and restart CIDER
```
this is my profiles.clj
```
{:user {:plugins [[lein-swank "1.4.5"]
                  [cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [lein-exec "0.3.4"]
                  [lein-cljfmt "0.1.7"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}
```
the version of cider and cider-repl is
```
CIDER 0.9.0snapshot (package: 20150427.2358)
```
i just use prelude to install the cider,and didn't change any file.

**Comment by expez** [comment] 2015-04-28 09:27
@paomian to force an update of the middleware (or any other snapshot dependency) you can do `lein -U repl` in your project directory.

**Comment by paomian** [comment] 2015-04-28 09:39
Hi expez,i run the `lein -U repl` in my project directory,but it's seem to be useless.

**Comment by bbatsov** [comment] 2015-04-28 09:40
Try again. I had forgotten to upload the new snapshot to clojars. :-)

**Comment by paomian** [comment] 2015-04-28 09:47
bbatsov,expez,thanks:-),it work for me.

**Comment by martinvlk** [comment] 2015-04-29 17:55
I observe the same thing as @Davidbhodge - within a project the version of tools.nrepl specified in my .lein/profiles.clj is used as expected. If I start cider outside a project, then 0.2.6 is used and cider complains.
M.

**Comment by expez** [comment] 2015-04-29 18:05
@martinvlk there's nothing we can do about the version of `nrepl` that lein specifies in its `base` profile.  I don't know if `profiles.clj` is supposed to be used or not when running `lein` outside a project.  You might file a bug with `lein` if you think it's doing the wrong thing to do.

**Comment by sooheon** [comment] 2015-06-10 06:31
Not sure if this is fixed because it was fixed for everyone else, but for my case at least, this dependency conflict with figwheel seems to be the problem:
https://github.com/bhauman/lein-figwheel/issues/149

**Comment by manuel-uberti** [comment] 2015-06-10 08:05
Thank you @sooheon, that worked for me too.

**Comment by rebcabin** [comment] 2015-12-25 14:52
I am back to Clojure after being away for several months (partly because I hoped this topic would settle down while I was away -- I could play with Common Lisp or C++).  It's still here.  I just did a fresh install of emacs, spacemacs, leiningen, and bingo-bango this old horror is still here

```
; CIDER 0.11.0snapshot (package: 20151224.1145) (Java 1.8.0_66, Clojure 1.7.0, nREPL 0.2.10)
WARNING: CIDER requires nREPL 0.2.12 (or newer) to work properly
WARNING: The following required nREPL ops are not supported: 
  apropos classpath complete eldoc format-code format-edn info inspect-pop inspect-push inspect-refresh macroexpand ns-list ns-vars ns-path refresh resource stacktrace toggle-trace-var toggle-trace-ns undef
  Please, install (or update) cider-nrepl 0.11.0-SNAPSHOT and restart CIDER
WARNING: The following nREPL ops are not supported:
artifact-list artifact-versions clean-ns extract-definition find-symbol find-used-locals hotload-dependency namespace-aliases rename-file-or-dir resolve-missing stubs-for-interface version warm-ast-cache
Please, install (or update) refactor-nrepl and restart the REPL.
You can mute this warning by changing cljr-suppress-middleware-warnings.
WARNING: CIDER's version (0.11.0-snapshot) does not match cider-nrepl's version (not installed). Things will break!
WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 2.0.0-SNAPSHOT (package: 20151210.200) and n/a, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.
```

**Comment by Malabarba** [comment] 2015-12-25 19:15
The warning was telling you to use `[refactor-nrepl "2.0.0-SNAPSHOT"]`, not `[refactor-nrepl "1.1.0"]`. ;-)

**Comment by bbatsov** [comment] 2015-12-25 21:34
`refactor-nrepl` is not part of CIDER, but its warning messages kind of blend in with the rest of the warnings and many people are confused which warning is coming from where...

**Comment by rebcabin** [comment] 2015-12-26 19:32
Ooops, right -- I read the refactor-nrepl repo page instead of (deep into) the warning to get the version number.  That fixed it, and I'm grateful for your sharp eyes.

**Comment by borgauf** [comment] 2016-01-02 15:46
I've got

    WARNING: CIDER requires nREPL 0.2.12 (or newer) to work properly
    WARNING: The following required nREPL ops are not supported: 
      format-code format-edn ns-path refresh
      Please, install (or update) cider-nrepl 0.11.0-SNAPSHOT and restart CIDER
    WARNING: CIDER's version (0.11.0-snapshot) does not match cider-nrepl's version (0.8.1). Things   will break!

This is from the standard Emacs drop-in .emacs.d/ from the ["Clojure for the Brave and True"](https://github.com/flyingmachine/emacs-for-clojure/archive/book1.zip)

I did an ELPA update and the above warnings.

**Comment by piotr-yuxuan** [comment] 2016-02-04 08:56
For you information: I first got
```
WARNING: The following required nREPL ops are not supported: 
format-code format-edn ns-path refresh
Please, install (or update) cider-nrepl 0.9.1 and restart CIDER
WARNING: The following nREPL ops are not supported:
artifact-list artifact-versions clean-ns configure extract-definition find-debug-fns find-symbol find-unbound hotload-dependency rename-file-or-dir resolve-missing stubs-for-interface version warm-ast-cache
Please, install (or update) refactor-nrepl and restart REPL.
You can mute this warning by changing cljr-suppress-middleware-warnings.
WARNING: CIDER's version (0.9.1) does not match cider-nrepl's version (0.8.1)
```
I solved it by amending my `~/.lein/progiles.clj` from:
```clojure
{:user {:plugins [[cider/cider-nrepl "0.8.1"]]}}
```
to
```clojure
{:user {:plugins [[cider/cider-nrepl "0.9.1"]
                  [refactor-nrepl "1.1.0"]]}}
```
and it solved the error.

**Comment by evanspa** [comment] 2016-02-10 21:48
I just updated my prelude installation.  Here's my output (**note the "...does not match..." warning at the bottom**):

```
; CIDER 0.11.0snapshot (package: 20160210.718) (Java 1.8.0_71, Clojure 1.6.0, nREPL 0.2.12)
; ================================================================================
; Welcome to CIDER!
;
; If you're new to CIDER it is highly recommended to go through its manual first.
; Press <M-x cider-view-manual> to view it.
; In case you're seeing any warnings you should consult the manual's "Troubleshooting" section.
;
; Here are few tips to get you started:
;
; * Press <C-h m> to see a list of the keybindings available (this will work in every Emacs buffer)
; * Press <,> to quickly invoke some REPL command
; * Press <C-c C-z> to switch between the REPL and a Clojure source buffer
; * Press <M-.> to jump to the source of something (e.g. a var, a Java method)
; * Press <C-c C-d C-d> to view the documentation for something (e.g. a var, a Java method)
;
; CIDER is super customizable - try <M-x customize-group cider> to get
; a feel for this. If you're thirsty for knowledge you should try <M-x cider-drink-a-sip>.
;
; If you think you've encountered a bug (or have some suggestions for improvements) press <M-x cider-report-bug>.
;
; Above all else - don't panic! In case of an emergency - procure some (hard) cider and enjoy it responsibly!
;
; You can disable this message from appearing on start by setting `cider-repl-display-help-banner' to nil.
; ================================================================================
WARNING: CIDER's version (0.11.0-snapshot) does not match cider-nrepl's version (0.10.2). Things will break!
user> 
```

And here's my project.clj (I don't have a global one or anything):

```
(defproject my-app "0.0.1"
  :plugins [[lein-pprint "1.1.2"]]
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/tools.logging "0.3.1"]
                 [org.clojure/data.codec "0.1.0"]
                 [ch.qos.logback/logback-classic "1.0.13"]
                 [org.slf4j/slf4j-api "1.7.5"]
                 [clj-time "0.8.0"]
                 [org.clojure/java.jdbc "0.3.6"]
                 [com.cemerick/friend "0.2.1"]
                 [pe-core-utils "0.0.13"]
                 [pe-jdbc-utils "0.0.20"]
                 [pe-user-core "0.1.40"]
                 [pe-rest-utils "0.0.35"]
                 [pe-user-rest "0.0.52"]]
  :resource-paths ["resources"]
  :profiles {:dev {:source-paths ["dev"] 
                   :plugins [[cider/cider-nrepl "0.10.2"]
                             [lein-ring "0.8.13"]]
                   :dependencies [[org.clojure/tools.namespace "0.2.7"]
                                  [org.clojure/java.classpath "0.2.2"]
                                  [org.clojure/tools.nrepl "0.2.12"]
                                  [org.clojure/data.json "0.2.5"]
                                  [org.postgresql/postgresql "9.4-1201-jdbc41"]
                                  [ring/ring-codec "1.0.0"]
                                  [ring-server "0.3.1"]
                                  [ring-mock "0.1.5"]
                                  [clojurewerkz/mailer "1.2.0"]
                                  [de.ubercode.clostache/clostache "1.4.0"]
                                  [pe-rest-testutils "0.0.7"]]
                   :resource-paths ["test-resources"]}
             :test {:resource-paths ["test-resources"]}})

```

**Comment by bbatsov** [comment] 2016-02-10 21:52
The warning tells you want to do - you need cider-nrepl 0.11-SNAPSHOT
instead of 0.10.2 (which you're using). Either this or you need to install
cider 0.10.2 from MELPA Stable, instead of pulling the snapshot from MELPA.

On 10 February 2016 at 23:48, Paul Evans <notifications@github.com> wrote:

> I just updated my prelude installation. Here's my output (*note the
> "...does not match..." warning at the bottom*):
>
> ; CIDER 0.11.0snapshot (package: 20160210.718) (Java 1.8.0_71, Clojure 1.6.0, nREPL 0.2.12)
> ; ================================================================================
> ; Welcome to CIDER!
> ;
> ; If you're new to CIDER it is highly recommended to go through its manual first.
> ; Press <M-x cider-view-manual> to view it.
> ; In case you're seeing any warnings you should consult the manual's "Troubleshooting" section.
> ;
> ; Here are few tips to get you started:
> ;
> ; * Press <C-h m> to see a list of the keybindings available (this will work in every Emacs buffer)
> ; * Press <,> to quickly invoke some REPL command
> ; * Press <C-c C-z> to switch between the REPL and a Clojure source buffer
> ; * Press <M-.> to jump to the source of something (e.g. a var, a Java method)
> ; * Press <C-c C-d C-d> to view the documentation for something (e.g. a var, a Java method)
> ;
> ; CIDER is super customizable - try <M-x customize-group cider> to get
> ; a feel for this. If you're thirsty for knowledge you should try <M-x cider-drink-a-sip>.
> ;
> ; If you think you've encountered a bug (or have some suggestions for improvements) press <M-x cider-report-bug>.
> ;
> ; Above all else - don't panic! In case of an emergency - procure some (hard) cider and enjoy it responsibly!
> ;
> ; You can disable this message from appearing on start by setting `cider-repl-display-help-banner' to nil.
> ; ================================================================================
> WARNING: CIDER's version (0.11.0-snapshot) does not match cider-nrepl's version (0.10.2). Things will break!
> user>
>
> And here's my project.clj (I don't have a global one or anything):
>
> (defproject my-app "0.0.1"
>   :plugins [[lein-pprint "1.1.2"]]
>   :dependencies [[org.clojure/clojure "1.6.0"]
>                  [org.clojure/tools.logging "0.3.1"]
>                  [org.clojure/data.codec "0.1.0"]
>                  [ch.qos.logback/logback-classic "1.0.13"]
>                  [org.slf4j/slf4j-api "1.7.5"]
>                  [clj-time "0.8.0"]
>                  [org.clojure/java.jdbc "0.3.6"]
>                  [com.cemerick/friend "0.2.1"]
>                  [pe-core-utils "0.0.13"]
>                  [pe-jdbc-utils "0.0.20"]
>                  [pe-user-core "0.1.40"]
>                  [pe-rest-utils "0.0.35"]
>                  [pe-user-rest "0.0.52"]]
>   :resource-paths ["resources"]
>   :profiles {:dev {:source-paths ["dev"]
>                    :plugins [[cider/cider-nrepl "0.10.2"]
>                              [lein-ring "0.8.13"]]
>                    :dependencies [[org.clojure/tools.namespace "0.2.7"]
>                                   [org.clojure/java.classpath "0.2.2"]
>                                   [org.clojure/tools.nrepl "0.2.12"]
>                                   [org.clojure/data.json "0.2.5"]
>                                   [org.postgresql/postgresql "9.4-1201-jdbc41"]
>                                   [ring/ring-codec "1.0.0"]
>                                   [ring-server "0.3.1"]
>                                   [ring-mock "0.1.5"]
>                                   [clojurewerkz/mailer "1.2.0"]
>                                   [de.ubercode.clostache/clostache "1.4.0"]
>                                   [pe-rest-testutils "0.0.7"]]
>                    :resource-paths ["test-resources"]}
>              :test {:resource-paths ["test-resources"]}})
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/961#issuecomment-182596246>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by evanspa** [comment] 2016-02-10 21:59
MELPA Stable!!!  Alright...that makes sense.  Yeah, in my personal init.el, there's no mention of MELPA...M-x package-install just works and I never questioned the type of repo I was pulling from.  I'll explicitly switch to stable and see if that fixes things.  Thanks!

**Comment by Davidbhodge** [comment] 2016-02-10 22:40
woah - same here. I'll change to Melpa-stable

Thanks so much for the tip

**Comment by 0xABAB** [comment] 2016-02-11 14:04
```
; CIDER 0.10.2 (Java 1.8.0_65, Clojure 1.8.0, nREPL 0.2.10)
WARNING: CIDER requires nREPL 0.2.12 (or newer) to work properly
```
This is what I get in Emacs 24.5.1. I am already using Melpa-STABLE and my `~/.lein/profiles.clj` contains:

```
{:user {:plugins [[cider/cider-nrepl "0.10.2"]]}}
{:repl {:dependencies [[org.clojure/tools.nrepl "0.2.12"]]}}
```

```
# more info
/usr/local/bin/lein --version
Leiningen 2.5.3 on Java 1.8.0_65 Java HotSpot(TM) 64-Bit Server VM
```
Can someone please tell me what's wrong or alternatively fix the software (with full installation instructions)?

**Comment by Malabarba** [comment] 2016-02-11 14:06
That's not a valid profiles file. You want:

    {:user {:plugins [[cider/cider-nrepl "0.10.2"]]}
     :repl {:dependencies [[org.clojure/tools.nrepl "0.2.12"]]}}

**Comment by bbatsov** [comment] 2016-02-11 14:08
Actually I'd put them both under `:repl`.

**Comment by robincarlo84** [comment] 2016-02-13 08:30
I've been having this kind of problem and the one solution that fixed my case was upgrading my lein using `lein upgrade`. I found it on this [SO answer](http://stackoverflow.com/a/32873993/987447)

**Comment by darth10** [comment] 2016-03-12 05:33
I've run into a similar issue with CIDER `20160310.330`.
This is the warning I get on `cider-jack-in`.

 ``` Please, install (or update) cider-nrepl 0.12.0-SNAPSHOT and restart CIDER```

But, that version of cider-nrepl is already installed. Here's my `profiles.clj`.

```clj
{:user {:plugins
        [[lein-ancient "0.6.7"]
         [lein-exec "0.3.5"]
         [lein-pprint "1.1.2"]
         [lein-try "0.4.3"]
         [http-kit/lein-template "1.0.0-SNAPSHOT"]
         [compojure-app/lein-template "0.4.7"]]}
 :repl {:plugins
        [[cider/cider-nrepl "0.12.0-SNAPSHOT"]]
        :dependencies
        [[org.clojure/tools.nrepl "0.2.12"]
         [compliment "0.2.5"]]}}
```

Any clue as to how to resolve this? I'm not able to use basic stuff like `find-symbol`.

**Comment by kaosbeat** [comment] 2016-03-17 21:40
I have the same problem, i cannot consistently start projects over here, keeps changing. Driving me nuts
happens wit both cider-connect and cider-jack-in

```
; CIDER 0.11.0snapshot (package: 20151207.1307) (Java 1.8.0_31, Clojure 1.7.0, nREPL 0.2.12)
WARNING: The following required nREPL ops are not supported: 
inspect-start inspect-reset
Please, install (or update) cider-nrepl 0.8.1 and restart CIDER
WARNING: CIDER's version (0.8.1) does not match cider-nrepl's version (0.11.0-snapshot)
user> 
```

**Comment by bbatsov** [comment] 2016-03-17 22:08
@darth10 Doubtful. What's the exact warning you're seeing?

@kaosbeat Can you update to 0.11-stable or 0.12 snapshot and tell me if this still happens? Likely you've got cider installed twice or something; I can't imagine another reasons for this odd version mismatch.

**Comment by nybbles** [comment] 2016-04-16 06:27
@bbatsov hm im running into this too, googled through a bunch of different threads - uninstalled these packages, moved to MELPA Stable, but I still get the following when using clojure-jack-in.

```
;; Connected to nREPL server running on port 51399 on host localhost - nrepl://localhost:51399
;; CIDER 0.11.0 (Bulgaria), nREPL 0.2.12
;; Clojure 1.6.0, Java 1.8.0_72
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: C-c C-q
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;; ======================================================================
;; If you’re new to CIDER it is highly recommended to go through its
;; manual first. Type <M-x cider-view-manual> to view it.
;; In case you’re seeing any warnings you should consult the manual’s
;; "Troubleshooting" section.
;;
;; Here are few tips to get you started:
;;
;; * Press <C-h m> to see a list of the keybindings available (this
;;   will work in every Emacs buffer)
;; * Press <,> to quickly invoke some REPL command
;; * Press <C-c C-z> to switch between the REPL and a Clojure file
;; * Press <M-. to jump to the source of something (e.g. a var, a
;;   Java method)
;; * Press <C-c C-d C-d> to view the documentation for something (e.g.
;;   a var, a Java method)
;; * Enable `eldoc-mode' to display function & method signatures in the minibuffer.
;; * Print CIDER's refcard and keep it close to your keyboard.
;;
;; CIDER is super customizable - try <M-x customize-group cider> to
;; get a feel for this. If you’re thirsty for knowledge you should try
;; <M-x cider-drink-a-sip>.
;;
;; If you think you’ve encountered a bug (or have some suggestions for
;; improvements) use <M-x cider-report-bug> to report it.
;;
;; Above all else - don’t panic! In case of an emergency - procure
;; some (hard) cider and enjoy it responsibly!
;;
;; You can remove this message with the `cider-repl-clear-help-banner' command.
;; You can disable it from appearing on start by setting
;; `cider-repl-display-help-banner' to nil.
;; ======================================================================
WARNING: The following required nREPL ops are not supported: 
  apropos classpath complete eldoc format-code format-edn info inspect-pop inspect-push inspect-refresh macroexpand ns-list ns-vars ns-path refresh resource stacktrace toggle-trace-var toggle-trace-ns undef
  Please, install (or update) cider-nrepl 0.11.0 and restart CIDER
WARNING: CIDER's version (0.11.0) does not match cider-nrepl's version (not installed). Things will break!
```

**Comment by bbatsov** [comment] 2016-04-16 15:01
You should check that you've got nothing cider-related in `profiles.clj` and that your leiningen version is recent (e.g. 2.6).

**Comment by nybbles** [comment] 2016-04-18 00:04
Hm actually I found that "lein new" created a project with Clojure 1.6.0.
Once I changed that to 1.8.0, everything seems to work perfectly. Thanks!
