### ISSUE TITLE
cider-current-ns should be less naive

### ISSUE THREAD

**Issue by abo-abo** [clojure-emacs/cider#1104] opened 2015-05-20 08:24 UTC
I'm using this in the eval routine of `lispy`:

```elisp
(nrepl-sync-request:eval str (cider-current-ns) (nrepl-current-session))
```

But I'm getting a problem if I eval this in a file that I'm just browsing, and hasn't been loaded yet.  It should be possible to do this, for instance I could eval just to get arguments for the built-in function.

Turns out the reason is that `cider-current-ns` just falls back to the regex-based `clojure-find-ns`, that knows nothing of the REPL state. Could we rely on the assumption that it's OK to eval in `cider-current-ns`?

Also before, the eval status at least returned `(member "namespace-not-found" status)`. After some update, it's no longer possible, it just returns status nil, with no further indication.

**Comment by bbatsov** [comment] 2015-05-20 09:09
> Also before, the eval status at least returned (member "namespace-not-found" status). After some update, it's no longer possible, it just returns status nil, with no further indication.

The idea is that if you get something like this when evaling code in a file, you probably didn't load the file, so we just eval the ns automatically. You can see this interplay in the `*nrepl-messages*`.

> Turns out the reason is that cider-current-ns just falls back to the regex-based clojure-find-ns, that knows nothing of the REPL state. Could we rely on the assumption that it's OK to eval in cider-current-ns?

There's no other way to be certain what the current ns of a file buffer is. Might look lame, but it's actually the best option we have.

**Comment by abo-abo** [comment] 2015-05-20 09:31
> The idea is that if you get something like this when evaling code in a file, you probably didn't load the file, so we just eval the ns automatically. You can see this interplay in the *nrepl-messages*.

This is being too smart, in my opinion. Imagine Emacs evaluating the current Elisp buffer just because you happen to have it open when you call `eval-expression`. This is the exact same situation: I eval some code just to get the argument list or the docstring of e.g. `ns`. It doesn't mean that I want to load the file.

Also I have no `*nrepl-messages*` buffer on Emacs 25 and latest CIDER.

> There's no other way to be certain what the current ns of a file buffer is. Might look lame, but it's actually the best option we have.

There should be a way to track this, with a buffer-local var perhaps.

In any case, previously I could fall back to "user" for the eval, on encountering "namespace-not-found".  Now, I can't do that any more.

How do you suggest I can eval this, whether the current file is loaded or not:

```
"(if (symbol? 'System/getProperty)
  (if (special-symbol? 'System/getProperty)
    'special
    (or (resolve 'System/getProperty)
        (first (keep #(ns-resolve % 'System/getProperty) (all-ns)))
        (if-let [val (try (load-string \"System/getProperty\") (catch Exception e))]
          (list 'variable (str val)))))
  (if (keyword? 'System/getProperty)
    'keyword
    'unknown))"
```

Note the call to `resolve`: I need to prefer `(cider-current-ns)` and fall back to "user" only if the first one fails.

**Comment by vspinu** [comment] 2015-05-20 16:43
> There should be a way to track this, with a buffer-local var perhaps.

This used to be the case before. A local var was set that you could check if the ns was loaded or not. The ns form was even loaded automatically back then. There were reasons to rewrite the evaluation code but I think the ns caching should have stayed.

**Comment by bbatsov** [comment] 2015-05-20 21:32
> There should be a way to track this, with a buffer-local var perhaps.

And how are you going to account for editing the current namespace with this buffer local variable? 

> This used to be the case before. A local var was set that you could check if the ns was loaded or not. The ns form was even loaded automatically back then.

Actually the old behaviour was nothing like this. Introducing the `load-file` eval hack marked the beginning of auto-loading the ns. We never this this in the past and buffer-local vars for ns tracking were killed almost immediately after they were introduced.

**Comment by vspinu** [comment] 2015-05-21 03:12
> Actually the old behaviour was nothing like this. 

It was there for short period, and it wasn't killed because it was a bad feature, but rather because the load file hack was killed and the caching was killed alongside.  Now there seems to be a good reason to put it back.

**Comment by vspinu** [comment] 2015-05-21 03:35
> There should be a way to track this, with a buffer-local var perhaps.

BTW,  `cider-buffer-ns` is [set only](https://github.com/clojure-emacs/cider/blob/master/nrepl-client.el#L847) in non clojure buffers. You can simply add `cider-buffer-last-ns` that wold be set in all buffers. I guess it could be useful in general to know that ns was modified since the last eval.

**Comment by bbatsov** [comment] 2015-05-21 04:40
> It was there for short period, and it wasn't killed because it was a bad feature, but rather because the load file hack was killed and the caching was killed alongside.

Nope, you're not right.
The caching is still there - https://github.com/clojure-emacs/cider/blob/fc5e0336d9b631c7c92abb866694f91ab75d86d8/cider-interaction.el

**Comment by vspinu** [comment] 2015-05-21 08:10
> The caching is still there

Hm. Right. The good stuff is still there. Then why you contradicted me in the first place with  "buffer-local vars for ns tracking were killed almost immediately after they were introduced"?

There is a small problem with the caching logic btw. On cider's quit/restart the `cidre--cached-ns-form` is not cleaned. So next time you eval in a new session, you will get `Namespace not found` error.

Now back to OP,  if the `cider--cached-ns-form` then @abo-abo can eval conditionally on it being non-nil (with the above caveat on cider restart). How about moving that ns caching and ns-form eval directly into `cider-current-ns`? Then you can indeed have a guaranty that `cider-current-ns` always returns a valid namespace ready to be evaled into.

**Comment by bbatsov** [comment] 2015-05-21 08:17
> Hm. Right. The good stuff is still there. Then why you contradicted me in the first place with "buffer-local vars for ns tracking were killed almost immediately after they were introduced"?

Because they was actually buffer-local tracking in the very first versions of the project (when it was still called `nrepl.el`). I referred to this, not to the ns-caching. 

> There is a small problem with the caching logic btw. On cider's quit/restart the cidre--cached-ns-form is not cleaned. So next time you eval in a new session, you will get Namespace not found error.

It's worth registering a ticket for this.

> Now back to OP, if the cider--cached-ns-form then @abo-abo can eval conditionally on it being non-nil (with the above caveat on cider restart). How about moving that ns caching and ns-form eval directly into cider-current-ns? Then you can indeed have a guaranty that cider-current-ns always returns a valid namespace ready to be evaled into.

This is one option. Another would be to make this magic less magical - e.g. prompt the user when they try to evaluation something in a non-existing ns and offer them to do it. Non-interactive invocations won't do the prompting, therefore @abo-abo's problem will be solved.

**Comment by bbatsov** [comment] 2015-06-07 15:37
Hmm, after finally looking into this I saw that `nrepl-sync-request:eval` doesn't do anything special. The extra ns magic happens only in `cider-interactive-eval`. The plot thickens...

**Comment by bbatsov** [comment] 2015-06-07 16:16
So, the problem is in `nrepl-send-sync-request`. It simply does no checks for something like `namespace-not-found` in the response. I'm not sure what to do about this. We can either throw an `error` or return `nil`. Not sure when this behaviour changed and what it used to be exactly.

**Comment by Malabarba** [comment] 2015-06-08 07:14
FWIW, I miss this feature all time as well (I say "miss it", as compared to elisp). This is not in the context of `sync-eval`, but just with regular `C-x C-e`. When I'm browsing a file in another project, I get immediate namespace errors when trying to evaluate some simple expressions. I understand there are conceptual problems here (the expression could evaluate differently depending on which namespace you're in), but it would be good to have a dumb fallback so I wouldn't have to manually copy these expressions into repl buffer.

If the problem is *"which namespace would we use then?"*, we could just fallback on the user namespace, or to whatever namespace is on the repl buffer (or even just evaluate it on the repl buffer).

If the problem is that detecting these situations is difficult, we could at least have that behavior as a separate keybind instead of automatic (not ideal, but acceptable for me).

**Comment by abo-abo** [comment] 2015-06-08 07:26
Artur Malabarba <notifications@github.com> writes:

> If the problem is "which namespace would we use then?", we could just
> fallback on the user namespace, or to whatever namespace is on the
> repl buffer (or even just evaluate it on the repl buffer).

I still have this code in lispy, which used to work but doesn't now:

(let* ((res (nrepl-sync-request:eval
             str
             (cider-current-ns)
             (nrepl-current-session)))
       (status (nrepl-dict-get res "status"))
       (res (if (member "namespace-not-found" status)
                (nrepl-sync-request:eval str)
              res))))

Here, I try to eval STR twice: first in (cider-current-ns), and if it
returns "namespace-not-found" failure, in (implicit) "user", or whatever
`nrepl-sync-request:eval' wants to do if a namespace isn't provided.

It used to work, at least a year ago. Right now, "namespace-not-found"
status is no longer returned. So the fix is just to return to the
previous behavior, with which I'm fine with.
When I get some time, I could search for when "namespace-not-found" was
removed or changed. Or maybe someone can do it faster.

Oleh

**Comment by bbatsov** [comment] 2015-06-08 07:26
@Malabarba I'm assuming you're on 0.9-snapshot and there missing namespaces/out of sync namespaces are evaluated automatically. Isn't this working for you.

**Comment by bbatsov** [comment] 2015-06-08 07:29
@Malabarba @abo-abo As I said, the problem with the low level sync command has nothing to do with automated ns tracking. The problem there is that the error is silently discarded. Somebody has to go through the history to see what happened, but I'm guessing the change was accidental. Probably if there's some `error` in the status we should just raise an Emacs `error`.

**Comment by bbatsov** [comment] 2015-06-08 07:42
@abo-abo Ah, now I get it - the eval status is missing completely in the response. Originally I had misunderstood you and thought that problem was something else.

**Comment by abo-abo** [comment] 2015-06-08 07:47
Bozhidar Batsov <notifications@github.com> writes:

> @abo-abo Ah, now I get it - the eval status is missing completely in
> the response. Originally I had misunderstood you and thought that
> problem was something else.

Yes, that's what I meant to say. Here's what I've just found:

ea449959e06d27d7520c10882db15abf17832da4 is the first bad commit

The change was 2 months ago.

**Comment by Malabarba** [comment] 2015-06-08 07:49
> @Malabarba I'm assuming you're on 0.9-snapshot and there missing namespaces/out of sync namespaces are evaluated automatically. Isn't this working for you.

No, because the file I'm visiting is on another project, so I just get a "Namespace not found." message. Whereas simply copying the expression and evaluating it in any other buffer would have worked.

**Comment by bbatsov** [comment] 2015-06-09 10:40
OK, let's get back to original issue. What's should we do about it? I don't think that there's something wrong with `cider-current-ns`. Perhaps what's needed is some function that would allow you to determine if a namespace exists or not. And there's still the problem of making sure the ns is in sync with its ns form (and I'm not even going to mention that you can have multiple ns forms in one source file).

**Comment by abo-abo** [comment] 2015-06-09 11:20
> What's should we do about it? I don't think that there's something wrong with cider-current-ns

I think there's something wrong. It's not a big deal, but it could be better.

I propose to check the regex that `(clojure-find-ns)` gives against `(map ns-name (all-ns))`. If it fails, use `*ns*` instead.  That way, if the user is mucking around with `cider-eval-last-sexp` and wants to eval a `def` even when `(clojure-find-ns)` namespace isn't defined yet, I say let him. The `def` will just go into `*ns*`, whatever it is (probably `user`). If that's not what the user expected, it's not a big deal, but if that's what he wanted, he'll be happy with the dwim behavior.

Actually, using `*ns*` always instead of `(clojure-find-ns)` is also an option.  I think it would fit better with the language that actually allows multiple namespaces per file.  The current behavior is basically convention-over-configuration, to the point that some programmers don't even know the fact that you can have multiple namespaces in one file.

**Comment by Malabarba** [comment] 2015-06-09 12:32
> Perhaps what's needed is some function that would allow you to determine if a namespace exists or not.

The clojure side already does that, and replies with a `"namespace-not-found"` status. On the Emacs side `nrepl-make-response-handler` even has a clause for that, but it doesn't do anything besides messaging the user. We could just improve that clause to try to do a new `“eval“` but this time using a namespace that we know is safe.

**Comment by bbatsov** [comment] 2015-06-11 11:33
@Malabarba `cider-interactive-eval` already does this. You don't want to insert this kind of "magic" in a low-level function.

**Comment by Malabarba** [comment] 2015-06-11 12:28
@bbatsov I'll try again when I get home, but last I tried `cider-eval-last-sexp` (which uses `cider-interactive-eval`) didn't do that. It just messaged me to say the namespace didn't exist.

**Comment by Malabarba** [comment] 2015-06-14 22:21
@bbatsov Sorry it took me a while. On the latest cider, if I try to evaluate something simple (like `(inc 1)`) by hitting `C-x C-e` on it, and if the buffer I'm in is on a different project from the connection, I get a “Namespace not found.” message and no result is printed.

**Comment by Malabarba** [comment] 2015-06-14 22:32
And just to be clear, I'm not saying this is a bug, I'm just proposing a feature request.

**Comment by abo-abo** [comment] 2015-06-15 08:05
> And just to be clear, I'm not saying this is a bug, I'm just proposing a feature request.

That's how `lispy` works now. Press <kbd>e</kbd> to eval in the current namespace -> get a "Namespace not found" -> eval in `*ns*` and display the result.

Could be more efficient, I guess. But maybe that's just me being a C++ guy: throwing errors in C++ is expensive. But then, having to communicate with the process the second time is (probably) even more expensive. Although, when attached to a single interactive command, it's OK to have a delay of up to `0.1s`: it's certainly less than that in this case.

**Comment by bbatsov** [comment] 2015-06-20 05:50
@Malabarba See #1139. Your problem should be fixed now.

**Comment by Malabarba** [comment] 2015-06-21 18:47
@bbatsov Yes it is, Thanks!

**Comment by expez** [comment] 2015-11-26 12:27
Since #1139 has been fixed, can we close this now?

**Comment by abo-abo** [comment] 2015-11-26 12:49
@exprez Bug #1273 is still present. I can't tell if this one is truly fixed until the other one is.

Just tested on 03a147c, after `cider-eval-last-sexp` on `(ns foo)`, then `(ns bar)` in the same file; `(cider-current-ns)` still returns `"foo"`. Changed to `bar` in the REPL, but no change in the file, still returns `foo`.

Seems that CIDER tries to rely on best practices (single `ns` per file) to ease its job, instead of doing the right thing, which in my opinion is always using REPL's namespace. If the language standard allows multiple `ns` per file, CIDER should support it.

**Comment by Malabarba** [comment] 2015-11-26 15:53
No. Cider does try to support multiple namespaces, to the point that cider-current-ns should  return a different value depending on *where* you call it. 

Whatever you evaluated before is irrelevant. The namespace used for evaluation should be the namespace above the sexp being evaluated. Is that what you experience?

**Comment by Malabarba** [comment] 2015-11-26 16:31
Note that you may need to update clojure mode to get what I described.

**Comment by bbatsov** [comment] 2015-11-26 18:06
> Seems that CIDER tries to rely on best practices (single ns per file) to ease its job, instead of doing the right thing, which in my opinion is always using REPL's namespace. If the language standard allows multiple ns per file, CIDER should support it.

Why would you be using the REPL's namespace? After all you're in a source file and there's some ns declaration preceding the expression you're evaluating. Using this is the sensible thing to do. I'm guessing the problem might be caused by the ns caching logic or something like this, but I haven't had time to play try to reproduce it.

**Comment by bbatsov** [comment] 2016-10-02 06:09
Closing due to lack of activity.

**Closed by bbatsov** 2016-10-02 06:09 UTC
