### ISSUE TITLE
printing chars breaks cider repl printing

### ISSUE THREAD

**Issue by ysmiraak** [clojure-emacs/cider#1794] opened 2016-06-28 09:03 UTC
## Expected behavior

`(apply pr (map char (range 128)))`
Should print all the ASCII chars (and it does for lein repl in the terminal).

## Actual behavior

In cider repl, it prints ASCII from 64 `@` to 90 `Z`, and then the printing functionality breaks down: The repl still returns results but won't print anything anymore.

## Steps to reproduce the problem

Do `(apply pr (map char (range 128)))`,
And then print something else.
The repl won't print but only returns nil.

### CIDER version information

```
;; CIDER 0.13.0snapshot (package: 20160623.12), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_72
```

### Lein/Boot version

Lein 2.6.1

### Emacs version

"GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17)"

### Operating system

OS X 10.11 "El Capitan"

**Comment by dpsutton** [comment] 2016-07-16 03:57
I can reliably reproduce this issue with `(pr (char 27))`. I'm gonna investigate if this is getting caught in the decoder of the nrepl messages.

**Comment by dpsutton** [comment] 2016-07-16 04:00
ah, and its not printing @ .. z as stated above, but its printing 0-27 (and only half of the char 27 key) which it displays as 

    ;; ======================================================================
    user> (apply pr (map char (range 128)))
    \ \ \ \ \ \ \ \ \backspace \tab \newline \ \formfeed \return \ \ \ \ \ \ \ \ \ \ \ \ \ \
    nil
    user> 


![image](https://cloud.githubusercontent.com/assets/6377293/16892649/cd87c83e-4adf-11e6-98bf-a5246ef395e7.png)


The 27 key (not sure of the terminology here) is escape, represented as `\^[`

**Comment by dpsutton** [comment] 2016-07-16 04:14
Neat. This is actually an emacs bug and dies in list/ansi-color.el in the function ansi-color-apply

**Comment by dpsutton** [comment] 2016-07-16 04:17
(defvar-local ansi-color-context nil
      "Context saved between two calls to `ansi-color-apply'.
    This is a list of the form (CODES FRAGMENT) or nil.  CODES
    represents the state the last call to `ansi-color-apply' ended
    with, currently a list of ansi codes, and FRAGMENT is a string
    starting with an escape sequence, possibly the start of a new
    escape sequence.")

**Comment by dpsutton** [comment] 2016-07-16 04:46
its this bit of code in ansi-apply-color:

     (let (fragment)
      (if (string-match "\033" string start)
          (let ((pos (match-beginning 0)))
            (setq fragment (substring string pos))
            (push (substring string start pos) result))
        (push (substring string start) result))
      (setq ansi-color-context (if (or codes fragment) (list codes fragment))))

because "\033" equals \^[ which is the escape code or (char 27). This stays in the ansi-color-context and seemingly gets appended onto every string coming through. There's a comment "if context was saved, and it is a string, append it". So it saves the escape char and prepends it and returns nil every time.

**Comment by dpsutton** [comment] 2016-07-16 15:35
modified   cider-repl.el
    @@ -537,9 +537,11 @@ If BOL is non-nil insert at the beginning of line."
               ;; TODO: Review the need for bol
               (when (and bol (not (bolp))) (insert-before-markers "\n"))
               (insert-before-markers
    -           (ansi-color-apply (propertize string
    -                                         'font-lock-face output-face
    -                                         'rear-nonsticky '(font-lock-face))))
    +           ;; prevent holding a context for escape strings
    +           (let ((ansi-color-context nil))
    +             (ansi-color-apply (propertize string
    +                                           'font-lock-face output-face
    +                                           'rear-nonsticky '(font-lock-face)))))
               (when (and (= (point) cider-repl-prompt-start-mark)
                          (not (bolp)))
                 (insert-before-markers "\n")

The following diff sorta fixes the problem. Previously, if you passed a `\^[` or escape key, the ansi printer saw that as opening a ansi formatted string without a closing tag, so it would hold on to that string in the context looking for the remainder of the formatting. Thus _every_ string going is held in this context waiting for other strings. This patch nukes the context on each call, but it kinda doesn't fix the issue.

This patch prevents the blocking of subsequent calls but it still stores the printing in the fragment variable waiting for more control sequences.

**Comment by Malabarba** [comment] 2016-07-16 18:57
> This patch prevents the blocking of subsequent calls but it still stores the printing in the fragment variable waiting for more control sequences.

Could we also do something like `(apply #'insert ansi-color-context) ` at the end to solve that?

**Comment by dpsutton** [comment] 2016-07-24 15:18
I'm thinking about this suggestion now, @Malabarba . I'm worried that we might break the functionality that this intends to create, which is holding format strings until the entire string is there. I have no idea if this is just some not often used feature so we can safely purge and set this var to nil as we please or if we will break someone's app?

Any thoughts? I'm gonna test some stuff in the meantime but I don't know enough about use cases here I think.

**Comment by dpsutton** [comment] 2016-07-24 15:50
Question of style for you. Do you prefer a named function here or to just inline the functionality?

```
(insert-before-markers
 (ansi-color-apply (propertize string
                               'font-lock-face output-face
                               'rear-nonsticky '(font-lock-face))))
(when ansi-color-context
  (insert-before-markers (cadr ansi-color-context))
  (setq ansi-color-context nil))
```

versus
```

(insert-before-markers
 (ansi-color-apply (propertize string
                               'font-lock-face output-face
                               'rear-nonsticky '(font-lock-face))))
(cider-repl--flush-ansi-string)
```

**Closed** 2016-07-25 04:47 UTC
Labels: bug
