### ISSUE TITLE
cider-connect only show result in cider-repl buffer , it do not share with the terminal console

### ISSUE THREAD

**Issue by mut0u** [clojure-emacs/cider#2024] opened 2017-07-04 12:54 UTC
## Expected behavior
I use the lein repl to start the repl and cider-connect to connect to the repl. I hope the termial console will display the output which show in cider-repl buffer.

## Actual behavior
When I connect to repl , the output only show in cider-repl buffer

## Steps to reproduce the problem

in terminal, use this to start clojure
``` 
   lein repl
```
in emacs , use this to connect repl

```
   cider-connect
```
Then the output only show in cider-repl buffer

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
 CIDER 0.15.0snapshot (package: 20170630.2342), nREPL 0.2.12
 Clojure 1.8.0, Java 1.8.0_131
```

### Lein 

 Lein 2.7.1

### Emacs version

25.2.1

### Operating system

Fedora 25

PS: 
  When I use   cider-nrepl 0.14.0 , there is no such problem.

**Comment by bbatsov** [comment] 2017-07-07 05:51
> I use the lein repl to start the repl and cider-connect to connect to the repl. I hope the termial console will display the output which show in cider-repl buffer.

What do you refer to as output? Output from things like `println` or evaluation results? I guess the former, but I'd rather ask. In older CIDER versions the output was bound to the underlying REPL process and this caused output to end up in the REPL buffer or in `*cider nrepl-server*`, but we've changed this for the sake of being able to see everything important in a single place. 

See https://github.com/clojure-emacs/cider-nrepl/commit/65e6a1115e55405e108e96f63c7098ed586f0027

So, we consider this a feature, not a bug. :-)

**Comment by bbatsov** [comment] 2017-07-20 06:06
Guess we can close this.

**Closed** 2017-07-20 06:05 UTC
