### ISSUE TITLE
*cider-error* buffer is empty

### ISSUE THREAD

**Issue by apostaat** [clojure-emacs/cider#3306] opened 2023-01-11 08:24 UTC
## Expected behavior

When exception occurs - I should see stacktrace in \*cider-error\* buffer. 

## Actual behavior

When exception occurs - I see only exception message in Cider REPL buffer like
`Wrong number of args (2) passed to: clojure.core/update`. 

\*cider-error\* buffer is empty 

I see following message `error in process filter: Wrong type argument: sequencep, t` in minibuffer. 

## Steps to reproduce the problem

I just installed Doom Emacs and it happens. 

### CIDER version information

```
;; CIDER 1.5.0 (Strasbourg), nREPL 1.0.0
;; Clojure 1.11.1, Java 17.0.1

```
### Lein / Clojure CLI version

Clojure CLI version 1.10.3.102

### Emacs version

Doom Emacs 
GNU Emacs 28.2 (build 1, x86_64-apple-darwin22.2.0, Carbon Version 169 AppKit 2299.3) of 2022-12-22
emacs was installed using brew `emacs-mac` formulae (railwaycat/emacsport)

### Operating system

MacOS 13.1 "Ventura" on Intel 

### JDK distribution

 java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

**Comment by bbatsov** [comment] 2023-01-17 09:13
Do you also experience this problem with the latest CIDER version? (1.6)

It will also be very useful to provide some reproduction steps/project and the full stacktrace (see the start of https://docs.cider.mx/cider/troubleshooting.html for more details)

**Comment by bbatsov** [comment] 2023-01-18 13:06
See also https://github.com/clojure-emacs/cider-nrepl/issues/765. Seems this regression might be caused by some changes in cider-nrepl 0.29.

**Comment by apostaat** [comment] 2023-01-22 13:40
> Do you also experience this problem with the latest CIDER version? (1.6)

I have updated version to 1.6.0 and problem disappeared.

**Comment by apostaat** [comment] 2023-01-22 14:05
> Seems this regression might be caused by some changes in cider-nrepl 0.29. 

Yes, looks like this. Downgrading `cider-nrepl` to `0.28.6` also healed the problem on 1.5.0 CIDER.

**Comment by bbatsov** [comment] 2023-01-30 10:42
Guess we can close this then.

**Closed by bbatsov** 2023-01-30 10:42 UTC
