### ISSUE TITLE
cider-jack-in fails with an error when leiningen is in pedantic mode

### ISSUE THREAD

**Issue by j0ni** [clojure-emacs/cider#1665] opened 2016-04-11 21:35 UTC
## Expected behavior

`cider-jack-in` should start a new repl and not introduce any dependency collisions that may break in with leiningen's `:pedantic? :abort` setting.

## Actual behavior

`cider-jack-in` fails with the following error:

```
error in process sentinel: Could not start nREPL server: Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.12"]
 overrides
[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]

Consider using these exclusions:


Aborting due to :pedantic? :abort
```

## Steps to reproduce the problem

I have the following `project.clj`:

```clojure
(defproject experiment "0.1.0-SNAPSHOT"
  :pedantic? :abort
  :dependencies [[org.clojure/clojure "1.7.0"]])
```

I invoke `cider-jack-in`, and the following error appears in my `*Messages*` buffer after a few seconds:

```
error in process sentinel: Could not start nREPL server: Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.12"]
 overrides
[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]

Consider using these exclusions:


Aborting due to :pedantic? :abort
```

### CIDER version information

CIDER 20160408.2344

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.12.0snapshot (package: 20160408.2344), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_77
```

### Lein/Boot version

```
Leiningen 2.6.1 on Java 1.8.0_77 Java HotSpot(TM) 64-Bit Server VM
```

### Emacs version

Emacs 25.0.92.2

### Operating system

Mac OS X 10.11.4

**Comment by Malabarba** [comment] 2016-04-11 22:25
I guess we should  add `:exclusions [org.clojure/clojure]` to the `tools.nrepl` artifact we inject. The least we can do is inject the same thing we're depending on. :smile:

**Comment by bbatsov** [comment] 2016-04-12 07:03
Btw, also see http://cider.readthedocs.org/en/latest/caveats/#injecting-dependencies-and-leiningen-pedantic-abort-mode

**Comment by benedekfazekas** [comment] 2016-04-12 09:41
this seems to be a duplicate of #1573

**Comment by benedekfazekas** [comment] 2016-04-12 09:58
@Malabarba strangely I don't think adding the `:exclusions` fixes the problem.

**Comment by Malabarba** [comment] 2016-04-12 18:17
Then I'm out of ideas. :-(

**Comment by zacyang** [comment] 2016-08-30 06:15
I had the same issue with this :pedantic? :abort , due to project wide setting.

**Comment by bbatsov** [comment] 2016-10-07 08:25
I'll close this due to lack of recent activity.

**Closed by bbatsov** 2016-10-07 08:25 UTC
