### ISSUE TITLE
cider-browse-ns,  Error -- wrong type argument stringp 40

### ISSUE THREAD

**Issue by EricGebhart** [clojure-emacs/cider#1022] opened 2015-03-16 21:20 UTC
; CIDER 0.9.0snapshot (package: 20150315.528) (Java 1.8.0_25, Clojure 1.6.0, nREPL 0.2.7)
user> 

Something is really not right here.  I traced it down to nrepl-send-sync-request  where the response comes back as a list encoded as a string.  So when it get's back to cider-browse-ns  the 
(mapcar (lambda (format ...   gets a series of characters the first of which is \(  which is 40.

I've never looked at any of this code until today, so I figured it is best to let someone who knows the
design intentions take a look.

I wouldn't be surprised if I had something wrong in my setup.  I just got cider to stop complaining at me about upgrading or installing 0.9.0snapshot  today.   That said, I've never seen browse-ns actually work,
although I can clearly see the namespaces and ns-vars if I debug the elisp.  It's just that they are in a list encoded as a string and not a list.

**Comment by EricGebhart** [comment] 2015-03-16 22:10
I'm using clojure.tools.namespace  0.2.10.

**Comment by bbatsov** [comment] 2015-03-16 23:18
Sounds like a duplicate of #1017 (although the solution there is flawed). I'll have a look at this soon.

**Comment by cichli** [comment] 2015-03-16 23:37
I think this is happening because the middleware linearization algorithm changed in tools.nrepl 0.2.7, and pr-values is now causing the `:value` slot of the response to be printed. We just need to use a different name for the key.

**Comment by bbatsov** [comment] 2015-03-17 05:28
@cichli Nice catch!

P.S. Thought we had stopped using `:value` everywhere, but I guess this was not the case. :-)

**Closed** 2015-03-17 16:04 UTC
