### ISSUE TITLE
Can't debug core.async/go-loop

### ISSUE THREAD

**Issue by hsestupin** [clojure-emacs/cider#1796] opened 2016-06-30 12:40 UTC
## Expected behavior
Be able to evaluate clojure functions with go-loop for debugging 

## Actual behavior
*cider-error* buffer opens with 
```
 Unhandled clojure.lang.ExceptionInfo
   Could not resolve var: a
   {:var a, :file "your_file", :column 5, :line 110}

                  core.clj: 4617  clojure.core/ex-info
```

## Steps to reproduce the problem
Try to "C-u C-M-x" (cider-debug-defun-at-point) on this function:
```clojure
(defn foo
  [a]
  (go-loop [n 10]
    (println a)
    (if (zero? n)
      :finish
      (recur (dec n)))))
```
### CIDER version information
```
;; CIDER 0.13.0snapshot (package: 20160623.12), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_45
```

### Lein/Boot version
Lein 2.6.1

### Emacs version

24.5

### Operating system
Windows 8

**Comment by Malabarba** [comment] 2016-06-30 15:58
Looks like a duplicate of #1775

**Comment by bbatsov** [comment] 2016-07-15 11:27
Closing as duplicate.

**Closed** 2016-07-15 11:27 UTC
