### ISSUE TITLE
cider-connect issue

### ISSUE THREAD

**Issue by malloc82** [clojure-emacs/cider#1492] opened 2015-12-28 05:03 UTC
I usually like to start a lein repl in terminal, then connect to it. 
Pre v0.10, if the repl in the terminal got restarted, I just have to do another cider-connect, and the previous cider-repl buffer will be automatically reused.
After v0.10, when I try to reconnect using cider-connect, I get the following messages:
```
nREPL: Direct connection established
nrepl-send-sync-request: Sync nREPL request timed out (op clone id 2)
```
So usually I have to kill the zombie cider-repl buffer, in order to have a new one connected. which means I get to lose my history in that cider-repl. 

I'm not sure if this is somewhat intended, but pre v0.10 behavior makes more sense.

**Comment by bbatsov** [comment] 2015-12-28 07:40
This is a duplicate of https://github.com/clojure-emacs/cider/issues/1482

We'll try to release a 0.10.1 by the end of the week, which will feature this fix.

**Closed by bbatsov** 2015-12-28 07:40 UTC

**Comment by malloc82** [comment] 2015-12-28 07:42
thanks
