### ISSUE TITLE
Cider freezes on jack-in

### ISSUE THREAD

**Issue by kostafey** [clojure-emacs/cider#1314] opened 2015-09-10 16:02 UTC
When I run `cider-jack-in`, emacs freezes on infinite loop.
`cider-20150910.418`

Here is `*Messages*` log:

```
Making nrepl-create-client-buffer-function local to *nrepl-server my-project* while let-bound!
Making nrepl-use-this-as-repl-buffer local to *nrepl-server my-project* while let-bound!
Starting nREPL server via lein repl :headless...
nREPL server started on 41899
nREPL: Establishing direct connection to localhost:41899 ...
nREPL: Direct connection established
Invalid face attribute :foreground nil [15365 times]
Quit [6 times]
```

UPD: looks loke dublicate #1311.

**Comment by Malabarba** [comment] 2015-09-10 16:53
CLosing as duplicate then. (Try upgrading cider again).

**Comment by cichli** [comment] 2015-09-10 17:04
@Malabarba I'm getting this too on master. The problem is that `nrepl--pp` assumes every nREPL dict has an `id` slot, which is only true for requests and responses. Got a fix pushed to my fork, just letting it pass on Travis before pushing to origin...

**Closed** 2015-09-10 17:09 UTC

**Comment by Malabarba** [comment] 2015-09-10 17:59
@cichli Indeed! Thanks.

**Comment by bbatsov** [comment] 2015-09-10 18:16
> The problem is that nrepl--pp assumes every nREPL dict has an id slot, which is only true for requests and responses.

Maybe we should have used something else for the cache, as those dicts in general are supposed to represent requests and responses.

**Comment by Malabarba** [comment] 2015-09-10 18:21
At first I wanted to use hashmaps or alists.
When I started coding the feature I decided to wait and see what would be more appropriate, and in the end the dicts just stuck around. (I don't explictly create the dicts, that's just how the nrepl reads the clojure hashmaps).
