### ISSUE TITLE
circular dependency between cljs and clj with the same namespace names

### ISSUE THREAD

**Issue by huahaiy** [clojure-emacs/cider#1469] opened 2015-12-14 12:45 UTC
e.g. Cider reports circular dependency between rum.core and rum.core, where rum/core.cljs depends on rum/core.clj for macros:

{:reason :mranderson046.toolsnamespace.v0v3v0-alpha1.clojure.tools.namespace.dependency/circular-dependency, :node rum.core, :dependency rum.core}

**Comment by bbatsov** [comment] 2015-12-14 12:47
I'm not sure I understand the problem. A bit more details would be useful - e.g. some repro steps.

**Comment by expez** [comment] 2015-12-14 13:05
Guessing this was caused by running some clj-refactor op.  AFAIK `cider-refresh` doesn't build its tracker using cljs/cljc files, only clj files.

The relevant issue is here: https://github.com/clojure-emacs/refactor-nrepl/issues/127

Until the bug is solved in tools.namespace there's nothing we can do.

**Comment by huahaiy** [comment] 2015-12-14 13:09
Correct. This happened when I tried to run clj-refactor "find usage" operation.

**Comment by expez** [comment] 2015-12-14 13:13
Closed in favor of the issue in the refactor-nrepl repo

**Closed** 2015-12-14 13:12 UTC
