### ISSUE TITLE
Cider 0.21 miscolors some output at the REPL seemingly randomly, maybe fixed in 0.22 snapshot

### ISSUE THREAD

**Issue by joinr** [clojure-emacs/cider#2660] opened 2019-06-25 15:33 UTC
## Expected behavior
Cider's syntax highlighting in prior releases has consistently provided a nice visual
discriminator for data structures.  Collection delimiters are white, keywords are green,
numbers are white, strings are red, etc.

This should be consistent regardless of the output.

## Actual behavior

When some output is printed at the REPL, the syntax highlighting seemingly "breaks"
for chunks of the output for unknown reasons.  There seems to be an error somewhere
that parses (or partially parses) the output and infers it's a string, leaving the bulk of
the output to be red, with small portions (after a `"`) as white.  This is inconsistent and
indicative of an error in the syntax highlighting implementation.

[shown here](https://imgur.com/UIXPN75)

## Steps to reproduce the problem
Given the file [miscolored.edn](https://raw.githubusercontent.com/joinr/lametestdata/master/miscolored.edn), this problem emerges with a simple read:

``(clojure.edn/read-string (slurp "miscolored.edn"))``

Which, when printed through the REPL, should result in the image above (the last element is majority red).

### CIDER version information
```
;; CIDER 0.21.0 (New York), nREPL 0.6.0
;; Clojure 1.10.0, Java 1.8.0_181
```
### Lein/Boot version
Leiningen 2.9.1 on Java 1.8.0_181 Java HotSpot(TM) 64-Bit Server VM
### Emacs version
25.3.1
### Operating system
Windows 10

## Addendum 
I also tested this using spacemacs on an ubuntu remote machine.  Since spacemacs clojure layer updates more frequently, I unintentionally had a snapshot release of 0.22 installed.

The picture [here](https://imgur.com/Y7Qzmx3) demonstrates expected output under spacemacs with cider 0.22.0 snapshot (package 20190515.946) under spacemacs using the same input `miscolored.edn`. 

I'm uncertain if the issue is platform dependent (windows vs. linux) or if 0.22 has fixed it.

**Comment by bbatsov** [comment] 2019-06-26 14:22
That's a duplicate of #2628. I'm afraid it's not fixed yet.

**Closed by bbatsov** 2019-06-26 14:22 UTC
