### ISSUE TITLE
Strange slowness when scrolling using spacemacs

### ISSUE THREAD

**Issue by vadali** [clojure-emacs/cider#1504] opened 2016-01-05 14:20 UTC
Hey,
I have a strange problem...

I recently shifted from prelude to spacemacs. When I open a clojure file through tramp (which my main mode of work), and I scroll the buffer (moving up/down lines) emacs becomes very unresponsive. Sometimes taking 10-20 seconds (!!) to scroll to the next line (this doesnt happen if the file is local). 

If I disable cider-mode for that buffer, then I dont get such lags. Re-enabling it brings the lag back.

I am not sure it helps, but in *Messages* buffer I see 
>Error during redisplay: (eval (format " cider[%s]" (cider--modeline-info))) signaled (quit) [2 times]

Which I dont see if I am using prelude. Also, this same version of cider 
>CIDER 0.11.0snapshot (package: 20160104.1114)

behaves properly running on prelude.. 

Any clues?

**Comment by vadali** [comment] 2016-01-05 15:07
ok, a small update, if I connect to a running nrepl, I dont experience the lag. The moment I disconnect (and enable cider-mode) the lag comes back!

**Comment by bbatsov** [comment] 2016-01-17 08:22
That's puzzling. Ideally you should run the [profiler](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html), so we can see what exactly is causing the slowdowns for you. It's seems pretty unlikely that this would be `(cider--modeline-info)`.

**Comment by vadali** [comment] 2016-01-21 23:44
Thanks for the advise!
Using the profiler I got the following:
```
- command-execute                                                1871  86%
 - apply                                                         1871  86%
  - ad-Advice-command-execute                                    1871  86%
   - #<compiled 0x400bd553>                                      1871  86%
    - call-interactively                                         1871  86%
     - funcall-interactively                                     1814  83%
      - next-line                                                1809  83%
       - line-move                                               1809  83%
        - line-move-partial                                      1792  82%
         - pos-visible-in-window-p                               1387  64%
          - eval                                                 1379  63%
           - spaceline--prepare                                  1376  63%
            - spaceline--prepare-any                             1363  63%
             - spaceline--eval-segment                           1337  61%
              - mapcar                                           1266  58%
               - #<compiled 0x449e8501>                          1256  58%
                - spaceline--eval-segment                        1255  58%
                 - spaceline--segment-minor-modes                1125  52%
                  - mapcar                                       1125  52%
                   - #<compiled 0x44ae4b7b>                      1120  51%
                    - format-mode-line                           1114  51%
                     - eval                                      1114  51%
                      - format                                   1114  51%
                       - cider--modeline-info                    1114  51%
                        - cider-current-connection               1114  51%
                         - cider-find-connection-buffer-for-project-directory               1111  51%
                          - clojure-project-dir                  1089  50%
                           - mapcar                              1089  50%
                            - #<compiled 0x4519e75b>               1089  50%
                             - locate-dominating-file               1088  50%
                              + file-exists-p                     405  18%
                              + expand-file-name                  403  18%
                              + file-name-directory                124   5%
                              + directory-file-name                119   5%
                              + file-name-as-directory                 14   0%
                                abbreviate-file-name                 12   0%
                          + cider-current-dir                      21   0%
                            seq-filter                              1   0%
                         + cider-connections                        2   0%
                    + s-trim                                        1   0%
                 + spaceline--segment-remote-host                  36   1%
                 + mapcar                                          23   1%
                 + eval                                            18   0%
                 + powerline-raw                                    9   0%
                   spaceline--segment-buffer-encoding-abbrev                  5   0%
                 + spaceline--segment-buffer-id                     4   0%
                   facep                                            3   0%
                 + spaceline--segment-buffer-size                   2   0%
               + #<compiled 0x449e8515>                            10   0%
              + powerline-raw                                      18   0%
                facep                                               7   0%
              + spaceline--segment-hud                              6   0%
              + eval                                                3   0%
              + spaceline--eval-segment                             3   0%
              + cl-remove-if-not                                    2   0%
                apply                                               1   0%
              + spaceline--segment-major-mode                       1   0%
              + spaceline--segment-version-control                  1   0%
              + spaceline--segment-new-version                      1   0%
             + mapcar                                              16   0%
            + powerline-render                                      7   0%
            + powerline-width                                       4   0%
              powerline-fill                                        1   0%
          + jit-lock-function                                       8   0%
         + posn-at-point                                           92   4%
           default-font-height                                      4   0%
         + scroll-up                                                2   0%
         + window-screen-lines                                      2   0%
        + line-move-visual                                          8   0%
        + default-line-height                                       5   0%
        + window-inside-pixel-edges                                 3   0%
      + helm-M-x                                                    5   0%
     + byte-code                                                   57   2%
+ ...                                                             165   7%
```
WDYT?.. please let me know if I can give you any more information to tackle this.

**Comment by bbatsov** [comment] 2016-01-26 19:49
Damn. The problem is that `clojure-project-dir` is too slow over tramp. We either have to cache or you'll have to disable the fancy modeline. Or then can be some special handling when editing files remotely...

**Comment by vadali** [comment] 2016-01-26 20:57
Thanks! So here is the confusing part, all of this works perfectly when using prelude (editing remote files with no nrepl running), so I am not entirely sure cider is the root-cause..

I wonder which bits of spacemacs might influence this behavior. For the moment I just went back to good-old prelude. You think I should open a ticket with a link to this discussion on spacemacs? What would you suggest I do to further pin-point the root cause?

**Comment by bbatsov** [comment] 2016-02-10 07:16
I don't know - it seems to me the same problem should be present everywhere when people are editing remote files. I'll think of some solution eventually, but it might take a while as my hands are full.

**Comment by bbatsov** [comment] 2016-10-02 06:50
Closing this due to lack of recent activity.

**Closed by bbatsov** 2016-10-02 06:50 UTC
