### ISSUE TITLE
Spawning subrepl using main/repl not working.

### ISSUE THREAD

**Issue by maacl** [clojure-emacs/cider#2017] opened 2017-06-18 16:34 UTC
## Expected behavior
At cider repl:

```
(defn foo
  [n]
  (cond (> n 40) (+ n 20)
        (> n 20) (- (first n) 20)
        :else 0))

(require '[clojure.main :as main])
(main/repl :caught (fn [_] (println "Broken! HaHa!")))

(foo 24)
=> Broken! HaHa!
```

## Actual behavior

```
(defn foo
  [n]
  (cond (> n 40) (+ n 20)
        (> n 20) (- (first n) 20)
        :else 0))

(require '[clojure.main :as main])
(main/repl :caught (fn [_] (println "Broken! HaHa!")))
```

Jumps to minibuffer with a `stdin:` prompt.

## Steps to reproduce the problem

See above.

### CIDER version information

CIDER 0.15.0-snapshot, nREPL 0.2.12
Clojure 1.8.0, Java 1.8.0_131

### Lein/Boot version

N/A

### Emacs version

Emacs 26.0.50

### Operating system

Ubuntu 17.04

**Comment by TimoFreiberg** [comment] 2018-06-27 18:11
Seems like an nREPL problem (if you can call it a problem).
Immediately after printing the prompt, nREPL asks for stdin input (the last message in the following snippet).
nREPL asks for stdin because the implementation of `clojure.main/repl` reads from `*in*`.
So you're right @bbatsov , this seems related to the follow-up issue of [2317](https://github.com/clojure-emacs/cider/issues/2317)

At the moment I would say "not a bug", but maybe the stdin handling of nREPL could be improved :).

nREPL messages:
```
(-->
  id                 "11"
  op                 "eval"
  session            "3e6c03a1-b531-46cc-bd36-df172ec81f9c"
  time-stamp         "2018-06-27 20:02:22.592855479"
  code               "(main/repl :caught (fn [_] (println \"Broken! HaHa!\")))"
  column             9
  content-type       "true"
  file               "*cider-repl filter(clj)*"
  line               55
  ns                 "filter.core"
  pprint             "true"
  pprint-fn          "clojure.pprint/pprint"
  print-right-margin 80
)
(<--
  id         "11"
  session    "3e6c03a1-b531-46cc-bd36-df172ec81f9c"
  time-stamp "2018-06-27 20:02:22.611202068"
  out        "filter.core=> "
)
(<--
  id         "11"
  session    "3e6c03a1-b531-46cc-bd36-df172ec81f9c"
  time-stamp "2018-06-27 20:02:22.612512035"
  status     ("need-input")
)
```

**Comment by bbatsov** [comment] 2019-05-11 21:05
I'll close this, as it has to be solved in nREPL. See https://github.com/nrepl/nrepl/issues/45

**Closed by bbatsov** 2019-05-11 21:05 UTC
Labels: bug, nREPL
