### ISSUE TITLE
cljc buffers not evaluated in cljs repl by cider-load-buffer

### ISSUE THREAD

**Issue by leppert** [clojure-emacs/cider#1875] opened 2016-10-28 20:54 UTC
## Expected behavior

After running `cider-jack-in-clojurescript`, `cider-load-buffer` loads the cljc buffer in both the Clojure and ClojureScript REPLs per the [`cider-load-buffer` docstring](https://github.com/clojure-emacs/cider/blob/master/cider-interaction.el#L1526-L1527).
## Actual behavior

The buffer is evaluated in the Clojure REPL but not the ClojureScript REPL.
## Steps to reproduce the problem
1. Check out this sample project: https://github.com/leppert/cljc-bug
2. Open [src/cljc_bug/core.cljc](https://github.com/leppert/cljc-bug/blob/master/src/cljc_bug/core.cljc)
3. Run `cider-jack-in-clojurescript`
4. `C-c M-n` to load the namespace. Note: this works correctly in both REPLs
5. `C-c C-k` to eval the buffer
6. Calling `(foo "bar")` in the Clojure REPL will now correctly print `bar Hello, World!`
7. Calling `(foo "bar")` in the ClojureScript REPL will throw the error `WARNING: Use of undeclared Var /foo at line 1 <cljs repl>`

![image](https://cloud.githubusercontent.com/assets/26643/19821543/e9745d74-9d2c-11e6-8b68-1a1c3a65b107.png)
### CIDER version information

```
;; CIDER 0.15.0snapshot (package: 20161016.424), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_40
```
### Lein/Boot version

`Leiningen 2.7.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM`
### Emacs version

`GNU Emacs 25.1.1 (x86_64-apple-darwin16.0.0, NS appkit-1504.00 Version 10.12 (Build 16A320)) of 2016-09-21`
### Operating system

macOS 10.12 (16A320)

**Comment by bbatsov** [comment] 2016-10-30 06:21
Sounds like some regression to me. Probably fixing this would be easy, but I won't be able to look into this for a while.

**Comment by leppert** [comment] 2016-10-30 13:25
@bbatsov I'll give it a stab.

**Comment by leppert** [comment] 2016-10-30 15:57
To narrow this down further, it does appear that:

- [`cider--cljc-or-cljx-buffer-p`](https://github.com/clojure-emacs/cider/blob/5a9b3ced54f52abfa3632a9e8d382be49cd4faff/cider-util.el#L85-L90) returns correctly
- [`cider-map-connections`](https://github.com/clojure-emacs/cider/blob/1491f7d6060f07e23fafc360e6e5cff128439e27/cider-client.el#L342-L345) correctly sets `which` to `:both`
- [`cider-map-connections`](https://github.com/clojure-emacs/cider/blob/1491f7d6060f07e23fafc360e6e5cff128439e27/cider-client.el#L369-L371) invokes the function for the `other-connection`

I've also confirmed that simply changing the major mode of the `.cljc` buffer from `clojurec-mode` to `clojurescript-mode` leads to the buffer being loaded in the ClojureScript REPL correctly.

**Comment by leppert** [comment] 2016-10-30 19:35
Still digging, but it looks like after the [`load-file`](https://github.com/clojure-emacs/cider/blob/master/cider-interaction.el#L1546-L1551) lambda is called on `other-connection`, `(cider-current-connection "cljs")` starts to return nil because `cider--connection-properties` reports the cljs REPL connection as `:type clj` even though calling `M-x : cider-repl-type` from that buffer returns "cljs".

**Comment by leppert** [comment] 2016-10-30 21:58
Beginning to wonder if this has something to do with the nrepl callback queue. Here's a log of activity when `cider-load-buffer` is called:

```
cider-request:load-file *cider-repl cljc-bug*
cider-nrepl-send-request *cider-repl cljc-bug*
nrepl-send-request connection=*cider-repl cljc-bug* id=27, nrepl-session=1c5efd99-9886-4dab-9277-8ced6fc448e0
cider-request:load-file *cider-repl CLJS cljc-bug*
cider-nrepl-send-request *cider-repl CLJS cljc-bug*
nrepl-send-request connection=*cider-repl CLJS cljc-bug* id=27, nrepl-session=a1e9394e-766e-45cb-8c89-c6455c47d906
Loading /Users/leppert/github/cljc-bug/src/cljc_bug/core.cljc...
cider-repl--state-handler response=(dict id 27 session 1c5efd99-9886-4dab-9277-8ced6fc448e0 value #’cljc-bug.core/foo)
=> #'cljc-bug.core/foo
cider-repl--state-handler response=(dict id 27 session 1c5efd99-9886-4dab-9277-8ced6fc448e0 status (done))
cider-repl--state-handler response=(dict changed-namespaces (dict) id 27 repl-type clj session 1c5efd99-9886-4dab-9277-8ced6fc448e0 status (state))
cider-repl--state-handler response=(dict id 27 session 1c5efd99-9886-4dab-9277-8ced6fc448e0 value #’cljc-bug.core/foo)
=> #'cljc-bug.core/foo
cider-repl--state-handler response=(dict id 27 session 1c5efd99-9886-4dab-9277-8ced6fc448e0 status (done))
cider-repl--state-handler response=(dict changed-namespaces (dict) id 27 repl-type clj session 1c5efd99-9886-4dab-9277-8ced6fc448e0 status (state))
```

With the caveat that I know very little about this system, it looks like the callbacks are called twice for the clj buffer (session id `1c5efd99-9886-4dab-9277-8ced6fc448e0`) rather than once for the clj buffer and once for the cljs buffer (session id `a1e9394e-766e-45cb-8c89-c6455c47d906`).

**Comment by Malabarba** [comment] 2016-11-02 13:22
Perhaps it's possible that the state tracker middleware is below the load-file middleware, so once you call load-file cider gets confused. Technically I can't see how that would produce the results you observe, but it's the closest I can think of to a lead. 😕

**Comment by dpsutton** [comment] 2016-12-02 21:23
So the code goes through `cider-map-connections` twice. The first time it knows it is supposed to work on `:both` buffers. And `current-buffer` is the source file so it allows it. However, point moves to the repl and so when it goes through this call again, `current-buffer` is no longer a buffer deriving from clojurec-mode or clojurex-mode, and therefore it drops `:both` for `:any`.

**Comment by Malabarba** [comment] 2016-12-08 02:06
OK. It definitely shouldn't go through the function the second time. I guess we need to rethink the code flow here a bit.

**Comment by dpsutton** [comment] 2016-12-19 13:43
Ok, I think I've gotten to the bottom of the issue. The problem is that the session for cljs is being marked as clj type, as @leppert mentioned earlier. The issue (I think) is that when you load the buffer, it doesn't fully respect the connection that its given:

    (defun cider-request:load-file (file-contents file-path file-name &optional connection callback)
      "Perform the nREPL \"load-file\" op.
    FILE-CONTENTS, FILE-PATH and FILE-NAME are details of the file to be
    loaded.

    If CONNECTION is nil, use `cider-current-connection'.
    If CALLBACK is nil, use `cider-load-file-handler'."
      (cider-nrepl-send-request (list "op" "load-file"
                                      "session" (cider-current-session)
                                      "file" file-contents
                                      "file-path" file-path
                                      "file-name" file-name)
                                (or callback
                                    (cider-load-file-handler (current-buffer)))
                                connection))


So here, the connection is looked up but session is grabbed independently of this. And there's our bug. We say do this to cljs repl and it does on that connection, but it grabs the clj session info. And when the state info comes back, it marks it as a clj repl for the future.

**Comment by dpsutton** [comment] 2016-12-22 14:33
This can be closed now as well.

**Closed** 2016-12-22 14:50 UTC
Labels: bug

**Comment by eggsyntax** [comment] 2017-09-19 15:20
Great work on this, y'all, this removes a major pain point for me. Really appreciate this, and all of your work :) 💯
