### ISSUE TITLE
Add matcher-combinators suppor to cider

### ISSUE THREAD

**Issue by claynon** [clojure-emacs/cider#2215] opened 2018-02-23 13:22 UTC
I'm using this [matcher-combinators](https://github.com/nubank/matcher-combinators) library, but I can't make it work with cider-test. I'm not sure if to fix that cider or matcher-combinator need to change. Can you give me a hand with that, please?
The `matcher-combinators` library is not a new testing library like `clojure.test` or `midje`, it just adds nice matchers to these libs.
When I use these matchers with `clojure.test` cider-test doesn't recognize failed tests, just the ones that passes. So I lose the most important part of the matcher-combinators library, which is the nice reports when test fail.

For example:
This works fine with cider:
```
(deftest test-1
  (is (match? 1 1))
```

When I try to run with cider test
```
(deftest test-2
  (is (match? 1 2))
```
I get the following message: `No assertions (or no tests) were run.Did you forget to use 'is' in your tests?`
And doesn't print the report on my repl
If I run on repl `run-tests 'namespace.of.my.tests.` it works as expected

### CIDER version information

```
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0
OpenJDK 64-Bit Server VM 1.8.0_144-b01
```

### Lein/Boot version

Leiningen 2.7.1

### Emacs version

GNU Emacs 25.3.1

### Operating system

Arch linux; Linux version 4.15.3-2-ARCH

**Comment by phillipm** [comment] 2018-02-24 12:55
For a bit more context:
`matcher-combinators` functionality is integrated with `clojure.test` in https://github.com/nubank/matcher-combinators/blob/master/src/matcher_combinators/test.clj by implementing a version of `clojure.test/assert-expr` for `match?` so that it is recognized by the `is` macro and reporting by implementing `clojure.test/report` with `:mismatch`.

As far as we can tell, it follows the standard pattern of other such implementations of `clojure.test/assert-expr` and `clojure.test/report`, so it is unclear why cider does not behave as `clojure.test/run-tests`. Is there a step we need to take to provide support for running tests with cider?

Thanks!

**Comment by xiongtx** [comment] 2018-02-24 21:28
The problem is that, in the failing test case, `cider-nrepl` [does not understand messages of type `:mismatch`](https://github.com/clojure-emacs/cider-nrepl/blob/v0.16.0/src/cider/nrepl/middleware/test.clj#L94-L120).

You've implemented the `clojure.test/report` method for `:mismatch`, but that only affects `clojure.test`'s reporting (e.g. when you run via CLI), not CIDER's.

**Comment by xiongtx** [comment] 2018-02-24 23:42
With clojure-emacs/cider-nrepl#510, you can extend `cider.nrepl.middleware.test/report` like:

```clojure
(require '[clojure.test :as test])
(require '[cider.nrepl.middleware.test :as ctest])

(defmethod cider.nrepl.middleware.test/report :mismatch
  [{:keys [markup] :as m}]
  (let [ns (ns-name (get m :ns (:testing-ns @ctest/current-report)))
        v (last test/*testing-vars*)]
    (swap! ctest/current-report
           #(-> %
                (update-in [:summary :test] inc)
                (update-in [:summary :fail] (fnil inc 0))
                (update-in [:results ns (:name (meta v))]
                           (fnil conj [])
                           (ctest/test-result ns v (assoc m :actual markup :type :fail)))
                (assoc :gen-input nil)))))
```

Running on the test:

```clojure
(deftest match-test
  (is (match? (m/prefix [1 odd?]) [1 2 2 3])))
```

gives:

![image](https://user-images.githubusercontent.com/1624090/36636282-99a73d42-1978-11e8-8d7c-04dee47c6207.png)

**Comment by bbatsov** [comment] 2018-03-04 13:25
Guess we can close this now.

**Closed by bbatsov** 2018-03-04 13:25 UTC
