### ISSUE TITLE
Not storing new nREPL connections!?

### ISSUE THREAD

**Issue by howardabrams** [clojure-emacs/cider#1306] opened 2015-09-06 01:27 UTC
Upgraded to the latest version of Cider (`20150905.604`) this evening, and have the following `:plugins` section in my `.projects.clj`:

```clojure
  :plugins [[lein-ring "0.8.13"]
            [cider/cider-nrepl "0.10.0-SNAPSHOT"]
            [refactor-nrepl "1.2.0-SNAPSHOT"]]
```
When I kick off a `cider-jack-in` while in one of my Clojure buffers, I see get a REPL containing:

```CIDER 0.10.0snapshot (package: 20150905.604) (Java 1.8.0_45, Clojure 1.6.0, nREPL 0.2.7)```

And have the following messages in the Emacs message buffer:

```
Starting nREPL server via lein repl :headless...
nREPL server started on 50419
nREPL: Establishing direct connection to localhost:50419 ...
nREPL: Direct connection established
Connected.  Happy hacking!
```
Great... expected. However, any Cider-related commands, return the error: ```cider-ensure-connected: No active nREPL connection```

Digging around, I see the value of `cider-connections`, it is `nil`. What other details should I submit to troubleshoot this?

**Comment by bbatsov** [comment] 2015-09-06 06:09
That's a duplicate of #1305

**Closed by bbatsov** 2015-09-06 06:09 UTC
