### ISSUE TITLE
Print to *out* outside REPL fails if REPL buffer is clear 

### ISSUE THREAD

**Issue by danskarda** [clojure-emacs/cider#1024] opened 2015-03-17 13:40 UTC
When I evaluate `(prn "Hello world")` from Clojure buffer using `C-x C-e` AND `*cider-repl*` buffer is clear, print fails with:

```
line-move-visual: Beginning of buffer
```

The issue is caused in `cider-repl--end-of-line-before-input-start`. The code moves up unconditionally one line up. This does not work if you are at the beginning of the buffer. `line-move` would be better than `previous-line` (patch follows).

**Comment by danskarda** [comment] 2015-03-17 13:41
Whoa, bug report number 2^10. Big party here ;)

**Comment by bbatsov** [comment] 2015-03-17 14:23
Btw, this is a duplicate of #1006. Looking forward to the patch! :-)

**Closed** 2015-03-19 07:09 UTC
