### ISSUE TITLE
exceptionally dis-connecting to repl

### ISSUE THREAD

**Issue by Kejia** [clojure-emacs/cider#1224] opened 2015-07-23 18:28 UTC
repl may be dis-connected exceptionally in unicode environments. when the path of a prog namespace contains non-ascii unicode characters (e.g. a project home directory consists of chinese characters), compiling the prog may result in repl-disconnecting.

if one open such a prog by `M-.` and compile the unit by `C-c C-k`, the repl connection must be broken. however, if the same prog unit is open by `C-x C-f`, things go well.

`程式磨坊`---copy this for debug purpose.

## UPDATE

@expez 

i have created a repo for this issue:
[repo for cider issue 1224](https://github.com/Kejia/for-cider)

the path looks like: 
> for_cider/projects/程式磨坊/rice

the main prog should be opened in this way:
```
$ emacs /foo/for_cider/projects/程式磨坊/rice/src/rice/main.clj
```

the core code:
```
(ns rice.main
  (:require [rice.helper :as h]))

(defn -main [& args]
  (println "initializing rice"))

;; "C-c C-k" to compile the prog, "C-c M-n" to load the namespace to repl, and
;; then run `(make 6)'.
;;
;; please ensure rice/helper.clj has not opened yet. now, move your pointer
;; at `h/grow', and then "M-." to open rice/helper.clj. in rice/helper.clj buffer,
;; "C-c C-k", and the repl connection will be broken.
(defn make [a]
  (h/grow a))
```

**Comment by expez** [comment] 2015-08-02 20:24
Could you create a github repo we can clone to reproduce the issue?

**Comment by Kejia** [comment] 2015-08-06 19:30
@expez

**Comment by expez** [comment] 2015-08-11 12:44
On windows I can't even get a repl going and I had to disable `git-gutter-mode` in order to view the file at all.

I'll give this a try on linux later

**Comment by expez** [comment] 2015-08-16 09:43
```
(--->
  op  "load-file"
  session  "651803e1-85c4-42d3-b503-f895321ad137"
  file  "(ns rice.main\n  (:require [rice.helper :as h]))\n\n(defn -main [& args]\n  (println \"initializing rice\"))\n\n;; \"C-c C-k\" to compile the prog, \"C-c M-n\" to load the namespace to repl, and\n;; then run `(make 6)'.\n;;\n;; please ensure rice/helper.clj has not opened yet. now, move your pointer\n;; at `h/grow', and then \"M-.\" to open rice/helper.clj. in rice/helper.clj buffer,\n;; \"C-c C-k\", and the repl connection will be broken.\n(defn make [a]\n  (h/grow a))\n"
  file-path  "/home/expez/git/for-cider/for_cider/projects/程式磨坊/rice/src/rice/main.clj"
  file-name  "main.clj"
  id  "19"
)
(<-
  id  "19"
  session  "651803e1-85c4-42d3-b503-f895321ad137"
  value  "#'rice.main/make"
)

(--->
  op  "load-file"
  session  "651803e1-85c4-42d3-b503-f895321ad137"
  file  "(ns rice.helper)\n\n(defn grow [a]\n  (+ a 2))\n"
  file-path  "/home/expez/git/for-cider/for_cider/projects/\347\250\213\345\274\217\347\243\250\345\235\212/rice/src/rice/helper.clj"
  file-name  "helper.clj"
  id  "21"
)

;;=> nREPL: Connection unexpectedly closed (connection broken by remote peer)
```

This appears to be a bug in emacs itself.  

Running `(buffer-file-name)` in the two buffers results in:

```
"/home/expez/git/for-cider/for_cider/projects/\347\250\213\345\274\217\347\243\250\345\235\212/rice/src/rice/helper.clj"
"/home/expez/git/for-cider/for_cider/projects/程式磨坊/rice/src/rice/main.clj"
```

Our middleware handles one of these encodings but not the other.  

@Kejia if you want to solve this you'll have to file a bug with emacs to get `(buffer-file-name)` fixed to be consistent in how it encodes its result.

**Comment by Malabarba** [comment] 2015-08-16 10:28
If I had to guess, I'd say `buffer-file-name` is respecting the encoding of the buffer, which would mean that those two buffers are using different encodings for some reason.

@Kejia Could you check if that's the case for you

@expez Regardless of any of this, I think `nrepl-client.el` should normalize string encodings before sending. Emacs can be pretty unpredictable with regards to the encoding that it uses, so if our nrepl middleware relies on a specific, we should ensure that's the one we're sending.

**Comment by Kejia** [comment] 2015-08-18 15:51
@Malabarba I have run `buffer-file-name` on the two buffers, and got the same results as @expez :

> "/home/xd/for_cider/projects/\347\250\213\345\274\217\347\243\250\345\235\212/rice/src/rice/helper.clj"
> "/home/xd/for_cider/projects/程式磨坊/rice/src/rice/main.clj"

The former buffer is opened via `M-.`, and the second via `C-x C-f`.

Is this what I'm supposed to do?

**Comment by Malabarba** [comment] 2015-08-18 16:02
@Kejia On each of these buffers, do `C-h C` and hit `RET`.
This will bring up a window describing the coding systems in use for the current buffer.

See the description you get from each of those files, and see if there's any difference between them.
They should be exactly the same.

**Comment by Kejia** [comment] 2015-08-19 15:43
@Malabarba, i did the instructions, and the coding systems in use for both buffers are identical:

Coding system for saving this buffer:
  - -- undecided-unix (alias: unix)

Default coding system (for new files):
  U -- utf-8-unix (alias: mule-utf-8-unix)

Coding system for keyboard input:
  U -- utf-8-unix (alias: mule-utf-8-unix)

Coding system for terminal output:
  U -- utf-8-unix (alias: mule-utf-8-unix)

Coding system for inter-client cut and paste:
  nil
Defaults for subprocess I/O:
  decoding: U -- utf-8-unix (alias: mule-utf-8-unix)

  encoding: U -- utf-8-unix (alias: mule-utf-8-unix)


Priority order for recognizing coding systems when reading files:
  1. utf-8 (alias: mule-utf-8)
  2. iso-2022-7bit 
  3. iso-latin-1 (alias: iso-8859-1 latin-1)
  4. iso-2022-7bit-lock (alias: iso-2022-int-1)
  5. iso-2022-8bit-ss2 
  6. emacs-mule 
  7. raw-text 
  8. iso-2022-jp (alias: junet)
  9. in-is13194-devanagari (alias: devanagari)
  10. chinese-iso-8bit (alias: cn-gb-2312 euc-china euc-cn cn-gb gb2312)
  11. utf-8-auto 
  12. utf-8-with-signature 
  13. utf-16 
  14. utf-16be-with-signature (alias: utf-16-be)
  15. utf-16le-with-signature (alias: utf-16-le)
  16. utf-16be 
  17. utf-16le 
  18. japanese-shift-jis (alias: shift_jis sjis)
  19. chinese-big5 (alias: big5 cn-big5 cp950)
  20. undecided 

  Other coding systems cannot be distinguished automatically
  from these, and therefore cannot be recognized automatically
  with the present coding system priorities.

Particular coding systems specified for certain file names:

  OPERATION	TARGET PATTERN		CODING SYSTEM(s)
  ---------	--------------		----------------
  File I/O		"\\.rkt[dl]?\\'"		(utf-8 . utf-8)
				"\\.dz\\'"				(no-conversion . no-conversion)
				"\\.txz\\'"				(no-conversion . no-conversion)
				"\\.xz\\'"				(no-conversion . no-conversion)
				"\\.lzma\\'"			(no-conversion . no-conversion)
				"\\.lz\\'"				(no-conversion . no-conversion)
				"\\.g?z\\'"				(no-conversion . no-conversion)
				"\\.\\(?:tgz\\|svgz\\|sifz\\)\\'"
										(no-conversion . no-conversion)
				"\\.tbz2?\\'"			(no-conversion . no-conversion)
				"\\.bz2\\'"				(no-conversion . no-conversion)
				"\\.Z\\'"				(no-conversion . no-conversion)
				"\\.elc\\'"				utf-8-emacs
				"\\.el\\'"				prefer-utf-8
				"\\.utf\\(-8\\)?\\'"	utf-8
				"\\.xml\\'"				xml-find-file-coding-system
				"\\(\\`\\|/\\)loaddefs.el\\'"
										(raw-text . raw-text-unix)
				"\\.tar\\'"				(no-conversion . no-conversion)
				"\\.po[tx]?\\'\\|\\.po\\."
										po-find-file-coding-system
				"\\.\\(tex\\|ltx\\|dtx\\|drv\\)\\'"
										latexenc-find-file-coding-system
				""						(undecided)
  Process I/O	nothing specified
  Network I/O	nothing specified

**Comment by Malabarba** [comment] 2015-08-19 16:49
Ok, then it looks like you need to report this as an emacs bug. :-/

**Comment by bbatsov** [comment] 2015-08-19 17:32
OK, so I guess we can close this ticket.

**Closed by bbatsov** 2015-08-19 17:32 UTC
Labels: bug, help wanted
