### ISSUE TITLE
`cider-scale-background-color` produces unusable color codes

### ISSUE THREAD

**Issue by daveliepmann** [clojure-emacs/cider#2157] opened 2018-01-09 13:31 UTC
Everywhere that `cider-scale-background-color` is used—in test output and stacktraces—it creates unusable 12-character color codes. These color codes are ignored, causing the default (white) to be used. Since I have a dark theme, this makes CIDER's stacktraces and test output jarringly difficult to read. 

For instance, in a buffer with a background color of "#161616", executing `(cider-scale-background-color)` evaluates to "#22e322e322e3". I suspect this is unintended behavior.

I currently use a workaround: 
```elisp
(set-variable 'cider-stacktrace-frames-background-color "#161616")
(set-variable 'cider-test-items-background-color "#333333")
```
...but would prefer not to need it. 😃 

## Expected behavior
When running tests, I expect test items to be displayed with a readable background color, scaled from my [dark theme](https://github.com/jackrusher/dotemacs/blob/master/eigengrau/eigengrau-definitions.el)'s existing background color. Similarly, when evaluating code that causes an excepton, I expect items in the stack trace to also be displayed with a scaled version of my background color.

## Actual behavior
Instead, in both cases (`*cider-test-report*` and `*cider-error*`), the background controlled by `cider-scale-background-color` is pure white. This conflicts with the dark theme both aesthetically and in the fact that the off-white text is unreadable.

## Steps to reproduce the problem
This happens when running tests or executing exception-producing statements. My theme is [eigengrau](https://github.com/jackrusher/dotemacs/blob/master/eigengrau/). The issue can be reproduced most directly, however, by simply evaluating `cider-scale-background-color` an seeing the 12-character output. The function detects the current buffer's background color, so try it with the background set to "#161616" or another dark color.

### CIDER version information

```
;; CIDER 0.16.0 (Riga), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_151
```

### Emacs version

GNU Emacs 25.3.1 (x86_64-apple-darwin17.2.0, Carbon Version 158 AppKit 1561.1) of 2018-01-05

### Operating system

MacOS High Sierra v10.13.2 (17C88)

**Comment by bbatsov** [comment] 2018-01-09 20:44
@jeffvalk Can you take a look at this?

**Comment by xiongtx** [comment] 2018-01-09 21:17
Are you sure the 12-digit RGB triplets are not being applied properly? They _should_ work, [according to the Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Colors.html).

>  Each of the R, G, and B components is a hexadecimal number specifying the component's relative intensity, one to four digits long (usually two digits are used).

I do see, however, that the `cider-scale-color` code could be improved through use of e.g. `color-darken-name`.

**Comment by bbatsov** [comment] 2018-01-10 13:33
@daveliepmann Can you check if @xiongtx's changes fixed the problem you had?

**Comment by jeffvalk** [comment] 2018-01-12 03:58
@bbatsov A bit late to the party, but I couldn't reproduce it. @xiongtx's change seems to make it moot though. I was unaware of `color-lighten-name` when I wrote that function. Good to know!

**Comment by bbatsov** [comment] 2018-01-15 08:03
Well, I guess we can close this then. @jeffvalk Nice to see you around. I miss the good old days when we were hacking together. :-) Happy New Year!

**Closed** 2018-01-15 08:04 UTC

**Comment by daveliepmann** [comment] 2018-01-15 10:04
I appreciate that folks have been quick to respond. I haven't had time to change my dev environment to test. 

>Well, I guess we can close this then.

If the bug has not been replicated then I'm not sure why we would close the ticket?

**Comment by bbatsov** [comment] 2018-01-15 14:26
Because the problematic code doesn't exist anymore and we're fairly certain an Emacs built-in should work. 😄  If you run into problems with the updated version - feel free to reopen it.

**Comment by jeffvalk** [comment] 2018-01-15 21:48
@bbatsov Happy New Year! I miss those days too. We need to engineer a "pause time" button -- it would make so many things easier! :smile:

**Comment by vemv** [comment] 2023-11-18 16:10
Hi!

Please create a new ticket from scrach following the template. Be generous as well with the description e.g. paste screenshots if needed.

Thanks - V
