### ISSUE TITLE
CIDER freezing in ClojureScript files whilst attempting to autocomplete

### ISSUE THREAD

**Issue by j0ni** [clojure-emacs/cider#879] opened 2014-11-17 23:59 UTC
I think this may be related to #844, or at least it has the same symptom.

I'm seeing this happening, with corresponding hangs and errors whenever I type anything vaguely symbol-like in a ClojureScript buffer.

```
Company: An error occurred in auto-begin
Company: Back-end company-capf error "Sync nREPL request timed out (op complete session 44f5198e-3c3e-4b89-a2e2-5d7f1b2ade43 ns frontend.components.nps symbol  context :same id 140)" with args (candidates :div.nps-quest--)
```

Disabling company-mode in the buffer makes it go away. Note that I have a Clojure REPL running, but no ClojureScript REPL of any kind.

**Comment by bbatsov** [comment] 2015-01-09 08:57
Guess we're missing some error handling in the middleware. I'll have a look at this.

**Comment by mtnygard** [comment] 2015-02-19 23:14
Also a similar behavior: freezes from eldoc. This one seems to be related to (failure to) initialize JavaFX classes from within cider-nrepl middleware:

```
ERROR: Unhandled REPL handler exception processing message {:op eldoc, :session 6c18e3ba-799d-4aa9-9163-48e3a7bc631b, :ns dynamo.ui.widgets, :symbol make-e-h, :id 76}
java.lang.NoClassDefFoundError: Could not initialize class javafx.scene.control.Control
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at cider.nrepl.middleware.util.java$class_info_STAR_$fn__2410.invoke(java.clj:141)
	at cider.nrepl.middleware.util.java$class_info_STAR_.invoke(java.clj:141)
	at cider.nrepl.middleware.util.java$class_info.invoke(java.clj:182)
	at cider.nrepl.middleware.util.java$member_info.invoke(java.clj:214)
	at cider.nrepl.middleware.util.java$resolve_member$fn__2435.invoke(java.clj:261)
	at clojure.core$map$fn__4529.invoke(core.clj:2614)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:485)
	at clojure.core$seq__4109.invoke(core.clj:135)
	at clojure.core$filter$fn__4556.invoke(core.clj:2669)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.RT.seq(RT.java:485)
	at clojure.lang.RT.nthFrom(RT.java:896)
	at clojure.lang.RT.nth(RT.java:855)
	at clojure.core$distinct$step__5055$fn__5056$fn__5058.invoke(core.clj:4804)
	at clojure.core$distinct$step__5055$fn__5056.invoke(core.clj:4804)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:485)
	at clojure.core$seq__4109.invoke(core.clj:135)
	at cider.nrepl.middleware.util.java$resolve_symbol.invoke(java.clj:282)
	at cider.nrepl.middleware.info$info_clj.invoke(info.clj:115)
	at cider.nrepl.middleware.info$info.invoke(info.clj:132)
	at cider.nrepl.middleware.info$eldoc.invoke(info.clj:240)
	at cider.nrepl.middleware.info$eldoc_reply.invoke(info.clj:246)
	at cider.nrepl.middleware.info$wrap_info$fn__2592.invoke(info.clj:261)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__425.invoke(middleware.clj:17)
	at cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__2802.invoke(macroexpand.clj:79)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__425.invoke(middleware.clj:17)
	at cider.nrepl.middleware.ns$wrap_ns$fn__2838.invoke(ns.clj:61)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__425.invoke(middleware.clj:17)
	at cider.nrepl.middleware.trace$wrap_trace$fn__3289.invoke(trace.clj:65)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__425.invoke(middleware.clj:17)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
	at clojure.tools.nrepl.server$handle$fn__779.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__4425.invoke(core.clj:1912)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by bbatsov** [comment] 2015-02-20 07:43
I think @cichli recently submitted a patch that fixed this. Are you using 0.9-snapshot?

**Comment by bbatsov** [comment] 2015-02-20 07:45
@mtnygard Looking at your stacktrace I believe this is a different problem. Guess some minimal project in which we could reproduce this would help us track the problem down.

**Comment by cichli** [comment] 2015-02-20 11:05
@bbatsov not merged yet :) https://github.com/clojure-emacs/cider-nrepl/pull/150

I think all the info/eldoc errors and timeouts are now sorted in 0.9-SNAPSHOT, but I will try and replicate with a project including JavaFX tonight, just to be sure.

**Closed** 2015-02-20 12:17 UTC

**Comment by mtnygard** [comment] 2015-02-20 13:52
@bbatsov I've just tried the same case with 0.9.0-SNAPSHOT, and was not able to reproduce the hang.
