### ISSUE TITLE
Fix confusing button text when suppressing / backgrounding middleware errors

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1829] opened 2016-08-24 10:10 UTC
When a middleware error occurs the following popup is shown:

![image](https://cloud.githubusercontent.com/assets/1006557/17926889/80e275f0-69f3-11e6-8c87-e76487520fbd.png)

The text makes sense, you can choose to background a certain kind of errors, but the text you press to activate this behavior makes no sense to me.  I suggest it's changed to 'Suppress future error popups' or something to that effect.

**Comment by bbatsov** [comment] 2016-08-25 09:52
> I suggest it's changed to 'Suppress future error popups' or something to that effect.

Sounds reasonable to me. I wonder if there wasn't some scenario when we were listing multiple exceptions, though. Someone will have to check this.

**Comment by dpsutton** [comment] 2016-08-27 15:04
There can be many buttons in here, one for each error. The text says which error you are suppressing (if the button is "up") or allowing to pop-up (if button is "down"). So this is offering to suppress completion errors of type <button-text>. The tough thing is that the code does this for each type in the variable `error-types`, but I can't find out how multiple would end up here. It throws the errors from the nrepl-dictionary "done". Does anyone know how there could be multiple errors?

**Comment by bbatsov** [comment] 2016-08-27 15:42
Guess we can add @sanjayl here as I'm pretty busy and I don't have time to look at the implementation right now.

**Comment by sanjayl** [comment] 2016-08-27 17:59
You're right, a response passed from `cider-nrepl` to `cider` can contain an arbitrary number of errors. These all get stuffed in the `:status` portion of the response; I don't know if this was by design or because there's no schema for the response. That being said, a request can traverse through an arbitrary number of middlewares, each with something to complain about, so it might be purposeful.

I don't know if I have any bright solutions to solve this issue. The stacktrace viewer uses a very similar concept to turn portions of the stacktrace on or off, so that's what I mimicked.

Let me know if there's anything I can do to help, and hope you're all doing well!

**Comment by Malabarba** [comment] 2016-08-29 12:31
We could just take the first error, and ignore the rest. From the looks of it, 99% of the time there'll be only one anyway. And in the other 1%, after the user chooses to disable the first error, if the problem happens again he can disable the second.

**Comment by sanjayl** [comment] 2016-08-29 16:10
That might lead to non-deterministic behavior in the 1%. The error-types are collected in a clojure set, which then gets translated to an elisp list in the bencoding/decoding process. I can't remember if the elements get sorted before being put in the list or not, so ordering might not be guaranteed.

How about I just make the verbiage clearer?

**Comment by Malabarba** [comment] 2016-08-29 17:08
You mean just changing the button to say something like "Suppress complete-error"? I think thats fine too.

**Comment by sanjayl** [comment] 2016-08-29 22:20
The tool tip already says that:

![sketch 1](https://cloud.githubusercontent.com/assets/7213170/18068910/c0badc68-6e11-11e6-80fd-2fafd3be5c8f.png)

I went ahead and put in a PR (https://github.com/clojure-emacs/cider/pull/1836) for a relabeled button incase you think it's needed in addition to the tooltip, this is what it looks like:

![cider](https://cloud.githubusercontent.com/assets/7213170/18069306/5493a968-6e14-11e6-8a05-2e2f8e70ea58.png)

**Comment by Malabarba** [comment] 2016-08-29 22:57
Thanks Sanjayl. I like the new label. :+1:

**Comment by bbatsov** [comment] 2016-08-30 07:23
Fixed in #1836.

**Closed by bbatsov** 2016-08-30 07:23 UTC
Labels: bug, help wanted, low hanging fruit
