### ISSUE TITLE
After cider-connect and cider-quit the standard output is not shown anywhere

### ISSUE THREAD

**Issue by maksr** [clojure-emacs/cider#2242] opened 2018-03-18 18:05 UTC
## Expected behavior

When Cider is not connected, the output of Clojure println (and the like) should be seen in the terminal where the appilcation was started (with lein repl or otherwise). Even when Cider *is* connected, the output of independent threads should be shown in the terminal (as it was e.g. at least until cider-0.11.0).

## Actual behavior

After cider-connect and cider-quit, the output of println is not shown anywhere.

## Steps to reproduce the problem

Follow the steps of Clojure Ring Getting Started on https://github.com/ring-clojure/ring/wiki/Getting-Started with a slightly modifed core.clj so it includes a println:

```
(ns hello-world.core)

(defn handler [request]
  (println "handler called")
  {:status 200
   :headers {"Content-Type" "text/html"}
   :body "Hello World"})
```
After last step (visiting http://localhost:3000/) verify that "handler called" is printed in the terminal where lein repl was started. You may have to press one Ctrl-C to kill the cmd that Windows uses to start the lein.bat and may get in the way.

M-x cider-connect from Emacs.

Reload the page on localhost:3000 from the browser. The "handler called" is now printed in the *cider-repl localhost* buffer.

M-x cider-quit.

Reload localhost:3000 . The "handler called" is not shown anywhere.

## Environment & Version information
The ouput of starting lein repl:
```
nREPL server started on port 52355 on host 127.0.0.1 - nrepl://127.0.0.1:52355
REPL-y 0.3.7, nREPL 0.2.13
Clojure 1.9.0
Java HotSpot(TM) Client VM 1.7.0_67-b01
```
The project dependencies are exactly as in the example but I have the same behaviour in other versions of Clojure, Ring etc.

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:52355
;; CIDER 0.16.0 (Riga), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.7.0_67
```

### Lein/Boot version

```
Leiningen 2.5.2 on Java 1.7.0_67 Java HotSpot(TM) Client VM
```

### Emacs version

```
GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-04-04 on KAEL
```

### Operating system

Windows 10, 64 bit, but I see the same behavior when application is started on Linux and not with lein repl.

**Comment by bbatsov** [comment] 2018-03-19 01:19
That problem is caused by the way we redirect the output to the CIDER REPL https://github.com/clojure-emacs/cider-nrepl/pull/474 Seems we either should just fork it as suggested in this PR or restore the original streams on quit.

**Comment by bbatsov** [comment] 2018-03-19 01:39
I just confirmed we forgot to add a call to unsubscribe-out when disconnecting. That should be pretty easy to fix.

**Comment by bbatsov** [comment] 2018-03-19 05:44
Looking more closely in the code it doesn't seem this will fix anything. The real solution should be something along the lines of the linked PR.

**Comment by maksr** [comment] 2018-03-19 10:45
The PR on clojure-emacs/cider-nrepl#474 is about the same problem, so I suggest to close this issue.

**Comment by bbatsov** [comment] 2018-05-05 13:07
That's fixed on `master`, btw.

**Closed by bbatsov** 2018-05-05 13:07 UTC
