### ISSUE TITLE
ClojureScript buffers not sending cider commands to CLJS REPL

### ISSUE THREAD

**Issue by cap10morgan** [clojure-emacs/cider#1509] opened 2016-01-09 20:43 UTC
I could have sworn this was working at one point in the development of 0.10.1, but now it's not.

**Steps to reproduce:**

1. Run `lein new figwheel cider-cljs -- --om`.
1. Add `:profiles {:dev {:dependencies [[com.cemerick/piggieback "0.2.1"]
                                  [org.clojure/tools.nrepl "0.2.12"]]}}` to `project.clj`
1. Open `src/cider-cljs/core.cljs` in Emacs.
1. Hit `C-c M-J` in that buffer to run `cider-jack-in-clojurescript`.
1. Once the REPL starts up, hit `C-c C-k` to evaluate the buffer.

**Expected result:**

CIDER evals the buffer in the CLJS REPL.

**Observed result:**

CIDER attempts to eval the buffer in the CLJ REPL and generates an error like `Unable to resolve symbol: enable-console-print!`.

**Versions:**

* Mac OS X 10.11.2
* Emacs (mac-port) 24.5.1
* CIDER 0.10.1
* cider-nrepl 0.10.1
* nrepl 0.2.12
* Java 1.8.0_60
* Clojure 1.7.0
* ClojureScript 1.7.170

It seems to do this with other commands too. `C-c M-n` causes the CLJ REPL to switch to the ClojureScript buffer's namespace, but not the CLJS REPL.

**Comment by Malabarba** [comment] 2016-01-09 22:37
What's the value of the variables `cider-repl-type` and `nrepl-project-dir` in each of your repl buffers?

**Comment by cap10morgan** [comment] 2016-01-09 22:50
`cider-repl-type` is `clj` in the CLJ REPL and `cljs` in the CLJS REPL.

`nrepl-project-dir` is `~/cider-cljs/` (the correct path to the project root) in both REPLs.

**Comment by Malabarba** [comment] 2016-01-09 23:14
Ok, that's what it should be. So the problem is probably in cider-load-buffer or in cider-current-connection.
I can't debug it right now (due to bad internet I can't even check out the 0.10.1 branch), but the next step will be to edebug these two functions and figure out what goes wrong.

**Comment by rfkm** [comment] 2016-01-16 01:41
The 0.10.0 branch seems not to contain https://github.com/clojure-emacs/cider/pull/1477.
I guess this is fixed on master.

**Comment by cap10morgan** [comment] 2016-01-16 13:25
Thanks @rfkm, that fixed it.

I'll issue a PR with that commit cherry-picked into v0.10.

**Closed** 2016-01-30 21:07 UTC

**Comment by jonpither** [comment] 2016-02-03 09:42
I spent some time with the problem in the title of this issue. Turns out it was my own fault - explicitly added a clojure-mode for .cljs files, which isn't needed as clojurescript-mode is auto-loaded. This was confusing `(cider-connection-type-for-buffer)`.

Took some time to diagnose though, so perhaps worth adding to troubleshooting?

**Comment by bbatsov** [comment] 2016-02-03 09:47
PR welcome. :-)

**Comment by jonpither** [comment] 2016-02-03 09:49
Will do.
