### ISSUE TITLE
Attempting to call unbound fn: #’cider.nrepl.middleware.debug/debug-reader

### ISSUE THREAD

**Issue by arnm** [clojure-emacs/cider#1886] opened 2016-12-06 17:05 UTC
## Expected behavior
Should be able to start REPL in with debug statements

## Actual behavior
`cider-jack-in` produces the following

```
Starting nREPL server via /usr/local/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #’cider.nrepl.middleware.debug/debug-reader, compiling:(hipchat_welcome/routes/services.clj:57:11)
	at clojure.lang.Compiler.load(Compiler.java:7386)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at hipchat_welcome.handler$eval218$loading__5569__auto____219.invoke(handler.clj:1)
	at hipchat_welcome.handler$eval218.invokeStatic(handler.clj:1)
	at hipchat_welcome.handler$eval218.invoke(handler.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at hipchat_welcome.core$eval212$loading__5569__auto____213.invoke(core.clj:1)
	at hipchat_welcome.core$eval212.invokeStatic(core.clj:1)
	at hipchat_welcome.core$eval212.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at user$eval3$loading__5569__auto____4.invoke(user.clj:1)
	at user$eval3.invokeStatic(user.clj:1)
	at user$eval3.invoke(user.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:359)
	at clojure.lang.RT.maybeLoadResourceScript(RT.java:355)
	at clojure.lang.RT.doInit(RT.java:475)
	at clojure.lang.RT.<clinit>(RT.java:331)
	... 1 more
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #’cider.nrepl.middleware.debug/debug-reader
	at clojure.lang.Var$Unbound.throwArity(Var.java:43)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.LispReader$CtorReader.readTagged(LispReader.java:1249)
	at clojure.lang.LispReader$CtorReader.invoke(LispReader.java:1228)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:684)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.Compiler.load(Compiler.java:7374)
	... 90 more
Subprocess failed
```

## Steps to reproduce the problem
- Spacemacs 0.200.5 installed with `clojure` layer
- place `#dbg` in clojure code
- `cider-jack-in`

### CIDER version information

```
Starting nREPL server via /usr/local/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless...
```

### Lein/Boot version

Lein 2.7.1

### Emacs version

Emacs 25.1 Spacemacs 0.200.5

### Operating system
macOs Sierra 10.12.1

**Comment by dpsutton** [comment] 2016-12-07 13:55
I hate to say "works for me" but I cannot reproduce this. Do you by any chance have a lein profile or anything like that that could leave an old version of nrepl working or anything?

**Comment by dpsutton** [comment] 2016-12-07 13:59
@arnm  If you remove the `#dbg` statement, can you jack in, and does the banner say the nrepl is working? Can you debug forms by instrumenting them with `C-u C-M-x`?

**Comment by Malabarba** [comment] 2016-12-08 02:02
Like @dpsutton said, try starting without the debug statement, and then debugging the code once you're connected. 

I don't know where you're inserting that #dbg, but it looks like the code is getting executed before cider is even loaded, which make it impossible for cider to debug it.

**Comment by dpsutton** [comment] 2017-01-06 22:09
@arnm can you help us reproduce this issue? I always hate to say "works for me" but I'm wondering if your emacs/repl/CIDER were in a bad state and a restart fixed everything.

**Comment by dpsutton** [comment] 2017-01-08 16:43
@bbatsov can you close this issue?

**Closed** 2017-01-08 16:46 UTC

**Comment by HardcoreParkore** [comment] 2019-07-15 23:56
This is closed, but I wanted to clarify that removing any debug expressions did fix this issue for me.

**Comment by cfeckardt** [comment] 2022-01-21 18:56
I came across this issue today too.

It occurs when there are `#dbg` expressions, or you try to debug a function in CIDER but the middleware isn't injected yet. I'm using deps.edn, so in my case the following was missing:

```
 :aliases {:repl {:extra-deps {cider/cider-nrepl {:mvn/version "0.25.2"}}
                  :main-opts ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}}}
```

Specifically `"--middleware" "cider.nrepl/cider-middleware"` wasn't correctly configured.
