### ISSUE TITLE
Cannot jump to Java symbols

### ISSUE THREAD

**Issue by watkinsr** [clojure-emacs/cider#2819] opened 2020-03-11 00:10 UTC
## Expected behavior
Succesfully jump to java source files
## Actual behavior
No symbol found
## Steps to reproduce the problem
M-. on a given java symbol like (.toUpperClass)

### CIDER version information

```
;; CIDER 0.25.0snapshot (package: 20200225.1516)
;; Clojure 1.8, Java 1.8.0_232
```

### Lein/Boot version
Lein 2.9.1

### Emacs version
Emacs 28.0.50

### Operating system
Gentoo

**Comment by bbatsov** [comment] 2020-03-11 08:55
Have you installed the JDK source package? You have to have the JDK sources on your classpath for the lookup to work. You can also point CIDER manually to some sources using `cider-jdk-src-paths`.

**Comment by watkinsr** [comment] 2020-03-11 15:33
Hey @bbatsov so I did install the docs and source for the icedtea-3.* package which is basically java 8. I also saw in the docs to set `cider-jdk-src-paths` so I set this to a src.zip file I believe in my $JAVA_HOME. One thing I did notice is I do not have a $CLASSPATH.

**Comment by jr0cket** [comment] 2020-03-22 15:40
I can confirm that CIDER 0.25.0snapshot (package: 20200227.1414) does navigate to sources using `cider-find-var`, once those sources are on the classpath.

I am using a `deps.edn` project rather than Leiningen (although that shouldn't make any different to CIDER).

Emacs: 26.3
OS: Ubuntu Linux
Java: openjdk 11
Clojure CLI: version "1.10.1.507"
Java Sources: version 11 - added with Ubuntu package `openjdk-11-source` added as an alias 
https://practicalli.github.io/spacemacs/navigating-code/java-definitions.html

**Comment by Invertisment** [comment] 2020-04-18 14:45
Hi
https://github.com/clojure-emacs/cider-nrepl/issues/64

**Comment by Solaxun** [comment] 2020-11-05 02:47
Echoing @jr0cket above - I spent the past few hours reading through all the related issues and the only thing that seemed to work to enable `cider-find-var` to correctly jump to java source was explicitly including it in the build tool (in my case lein).  

For example, added to `project.clj`:

`:java-source-paths ["/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/src.zip"]`

I had almost given up, and in fact after trying last night before finding this tip I had installed Cursive and spent a few hours porting all my shortcuts over.  I'm not sure how Cursive has accomplished this, but when setting up a lein project, there was no need to specify source, it just worked.  The `project.clj` file in Cursive also appears unmodified and has no reference to the `:java-source-paths` , so some sort of sorcery is going on to make it work I guess.

I know it was mentioned above that it largely depends on the build tool, but somehow they've got it working in Cursive so there must be a path.  My primary concern with this approach is I change JDK later on and forget to adjust the `:java-source-paths`.

**Comment by bbatsov** [comment] 2020-11-05 08:37
> The project.clj file in Cursive also appears unmodified and has no reference to the :java-source-paths , so some sort of sorcery is going on to make it work I guess.

IntelliJ knows a lot about Java sources in general. :-) It's hard for us to match their work.

Btw, CIDER's approach used to work for years pretty well without much additional setup for the JDKs, so I'm still puzzled what went wrong on JDK 8 (on JDK 9+ it's clear that the modules messed up everything). The situation is definitely fixable, but I haven't had time to dive into this for a while now. 

Potentially you can address the problem by using `lsp-mode` along-side CIDER, as I assume their navigation to Java sources is better. 

> I celebrated prematurely. Jumping to Java source only works some of the time, probably due to type inference issues but I can't be certain. I guess for heavy interop projects this just might not be in the cards.

If you can provide more details about the issues that'd be helpful.

**Comment by jeffvalk** [comment] 2021-01-21 22:36
I think may be (yet another) duplicate of clojure-emacs/orchard#103.

**Comment by vemv** [comment] 2021-08-29 05:36
A working solution goes like this:

* make sure the JDK source-paths are in your classpath
  * sometimes they are by default, otherwise add them by hand
* [Disable dynapath](https://github.com/clojure-emacs/orchard/tree/b855c87432f10659e0a48710a9625c49201cbb62#configuration-options)
* Use https://github.com/clojure-emacs/enrich-classpath/ for adding arbitrary Java sources for your whole dependency tree
  * (it doesn't add sources for the JDK itself atm, but it's easy enough to do that one by hand)

**Comment by Solaxun** [comment] 2021-08-31 16:26
I appreciate you taking the effort to post a work-around @vemv but jump-to-source is table-stakes for any editor and it should be something that just works without tinkering (easier said than done I'm sure).  It seems after more than a year that this is still not the case, which is unfortunate but I suppose beggars can't be choosers.

**Comment by vemv** [comment] 2021-08-31 16:38
We're working on it! I'm also not posting a workaround, but a preview of how CIDER will work. You can get the same featureset today by performing those steps.

That would be actually valuable feedback. We prefer to find surprises today than after a big announcement.

Cheers - V

**Comment by vemv** [comment] 2023-10-09 09:08
`enrich-classpath` has been a reality for the last few months.

Revamped documentation: https://docs.cider.mx/cider/config/basic_config.html#use-enrich-classpath

You can check this recent announcement for a tour of our current capabilities: https://clojurians.slack.com/archives/C0617A8PQ/p1696618492372739

**Closed by vemv** 2023-10-09 09:08 UTC
Labels: bug, help wanted, high priority
