### ISSUE TITLE
Debugger not ignoring macros dispatch "ignore next form (#_)"

### ISSUE THREAD

**Issue by marc-sabates-gelpi** [clojure-emacs/cider#2251] opened 2018-03-25 12:18 UTC
## Expected behavior
Debugger to ignore forms ignored with (`#_`)

## Actual behavior
The debugger stops at the ignored form and displays the value of the next form.

## Steps to reproduce the problem
1. Run _cider-eval-defun-at-point_ (<kbd>C-c C-c</kbd>) on the following code:
```
(do
  ;;(println "I am commented out!")
  (comment (println "I am commented out, too.."))
  #_ (println "I am commented out, as well..")
  #break (+ 2 2))
```

The debbuger will stop at `#_ (println "I am commented out, as well..")` and will show the result of `(+ 2 2)`..

![cider debugger issue](https://user-images.githubusercontent.com/20740039/37874835-4c712924-3026-11e8-8d5c-4ad7976d8a92.png)

### CIDER version information

```
;; CIDER 0.16.0 (Riga), nREPL 0.2.12
;; Clojure 1.9.0, Java 1.8.0_102
```

### Lein/Boot version

```Leiningen 2.8.1 on Java 1.8.0_102 Java HotSpot(TM) 64-Bit Server VM```

### Emacs version

```GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.23) of 2018-02-11```

### Operating system

```Ubuntu 14.04 LTS```
```Linux 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

Thanks!

**Comment by vspinu** [comment] 2018-10-15 13:02
Duplicate of #1680

**Closed by vspinu** 2018-10-15 13:02 UTC
Labels: bug, debugger
