### ISSUE TITLE
Printing Datomic entities incorrectly

### ISSUE THREAD

**Issue by robert-stuttaford** [clojure-emacs/cider#1505] opened 2016-01-05 15:07 UTC
Cider 11-SNAPSHOT's `*cider-result*` appears to be printing `#object[datomic.query.EntityMap "0xXXXXXX" "<a pr-str'd representation of the data>"]` instead of the normal map output we got before.

**Comment by Malabarba** [comment] 2016-01-05 15:45
Could you also check whether this happens in cider-nrepl-0.10.0? You don't need to reinstall cider.el or anything. Just change the cider-nrepl version to "0.10.0" in your `project.clj`/`profiles.clj`.

**Comment by robert-stuttaford** [comment] 2016-01-05 16:07
I'm fairly sure it doesn't: I've been using 10 since SNAPSHOT. Switched to 11-SNAPSHOT today, got the error. I'm happy to check if you need me to confirm.

**Comment by cichli** [comment] 2016-01-06 12:20
Does the issue still occur if you `(setq cider-pprint-fn 'pprint)`? (I'm assuming you're using one of the `cider-pprint-` commands). This might be because we've changed the default pretty-printer to `fipp`.

**Comment by Malabarba** [comment] 2016-01-07 21:45
I've noticed the same thing with other object types. Looks like fipp does not respect print-method definitions. The problem is solved if I change it to pprint. 

You can verify this by evaluating `inc` at the REPL.

**Comment by robert-stuttaford** [comment] 2016-01-08 10:16
I have done as @cichli recommended and set `(setq cider-pprint-fn 'pprint)`. I've tested a Datomic entity and it prints as I would expect it to. Thanks!

**Comment by bbatsov** [comment] 2016-01-08 12:48
Still, we have to fix this for `fipp`.

**Comment by robert-stuttaford** [comment] 2016-01-08 12:49
True, sorry, I shouldn't have closed it!

**Comment by Malabarba** [comment] 2016-02-14 20:25
Would anyone like to mention this issue with `fipp` upstream?

**Comment by bbatsov** [comment] 2016-04-28 23:56
Guess we can just mention here @brandonbloom and hope he'll read this. :-)

**Comment by brandonbloom** [comment] 2016-04-29 17:12
File an issue: https://github.com/brandonbloom/fipp/issues

**Comment by bbatsov** [comment] 2016-10-02 06:53
I'm closing this as an upstream fix is out of our hands.

**Closed by bbatsov** 2016-10-02 06:53 UTC
Labels: bug
