### ISSUE TITLE
M-x cider-debug-defun-at-point fails, 'No reader function for tag dbg'

### ISSUE THREAD

**Issue by ibcoleman** [clojure-emacs/cider#1359] opened 2015-10-05 20:44 UTC
# Description
Running cider-debug-defun-at-point always throws a ReaderException.

I recently updated to Leiningen 2.5.3 (for unrelated reasons)...

# Stats
GNU Emacs 24.5.1
Fedora 22
; CIDER 0.10.0snapshot (package: 20151005.453) (Java 1.8.0_60, Clojure 1.7.0, nREPL 0.2.10)

# Stacktrace
```
  Show: Clojure Java REPL Tooling Duplicates All  (0 frames hidden)

2. Unhandled clojure.lang.LispReader$ReaderException
   java.lang.RuntimeException: No reader function for tag dbg

               LispReader.java:  292  clojure.lang.LispReader/read
               LispReader.java:  196  clojure.lang.LispReader/read
               LispReader.java:  190  clojure.lang.LispReader/read
                      core.clj: 3640  clojure.core/read
                      core.clj: 3638  clojure.core/read
        interruptible_eval.clj:   68  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn/fn
                      main.clj:  238  clojure.main/repl/read-eval-print/fn
                      main.clj:  238  clojure.main/repl/read-eval-print
                      main.clj:  258  clojure.main/repl/fn
                      main.clj:  258  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   58  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  630  clojure.core/apply
                      core.clj: 1868  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  191  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  159  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.RuntimeException
   No reader function for tag dbg

               LispReader.java: 1245  clojure.lang.LispReader$CtorReader/readTagged
               LispReader.java: 1228  clojure.lang.LispReader$CtorReader/invoke
               LispReader.java:  684  clojure.lang.LispReader$DispatchReader/invoke
               LispReader.java:  263  clojure.lang.LispReader/read
               LispReader.java:  196  clojure.lang.LispReader/read
               LispReader.java:  190  clojure.lang.LispReader/read
                      core.clj: 3640  clojure.core/read
                      core.clj: 3638  clojure.core/read
        interruptible_eval.clj:   68  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn/fn
                      main.clj:  238  clojure.main/repl/read-eval-print/fn
                      main.clj:  238  clojure.main/repl/read-eval-print
                      main.clj:  258  clojure.main/repl/fn
                      main.clj:  258  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   58  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  630  clojure.core/apply
                      core.clj: 1868  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  191  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  159  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run
```

**Comment by Malabarba** [comment] 2015-10-05 21:12
Was this working before you upgraded leiningen?
And what's the cider-nrepl version in your project.clj?

**Comment by ibcoleman** [comment] 2015-10-06 15:46
Hi Artur,

As far as I know. It was working at least as of a day or two ago. 

The cider-nrepl version in profiles.clj is 0.10.0-SNAPSHOT. None specified in project.clj.

I was going to backlevel the cider-nrepl to the 0.9.n release, but wasn't sure how to rever to the older MELPA package too...

**Comment by rasom** [comment] 2015-10-10 10:53
I'm facing the same issue.

GNU Emacs 24.5.1
OSX 10.11
; CIDER 0.10.0snapshot (package: 20151006.714) (Java 1.8.0_51, Clojure 1.7.0, nREPL 0.2.10)

**Comment by Malabarba** [comment] 2015-10-10 22:39
I must say, this is intriguing, so I'll continue to ask random questions until I hear a hit. ☺

@ibcoleman @rasom 
What do you get if you evaluate each of the following expressions on the repl? 

1. `*data-readers*`
2. `cider.nrepl.middleware.debug/debug-reader`

**Comment by DanPallas** [comment] 2015-10-11 16:05
I'm experiencing the same issue. Also using [cider/cider-nrepl "0.10.0-SNAPSHOT"] and cider from melpa updated yesterday.  In answer to your last question, I get

1. *data-readers* => {}
2. cider.nrepl.middleware.debug/debug-reader => #object[cider.nrepl.middleware.debug$debug_reader 0x3ac8a839 "cider.nrepl.middleware.debug$debug_reader@3ac8a839"]

**Comment by Malabarba** [comment] 2015-10-13 13:47
Does anyone have this problem with lein? Or is it just boot?

If someone has this problem with lein, seeying your `profiles.clj` and your `project.clj` would be a big help.

**Comment by expez** [comment] 2015-10-13 14:17
This is `C-u C-c C-c` using `lein`: 
```

  Show: Clojure Java REPL Tooling Duplicates All  (22 frames hidden)

2. Unhandled clojure.lang.LispReader$ReaderException
   java.lang.RuntimeException: No reader function for tag dbg

               LispReader.java:  292  clojure.lang.LispReader/read
               LispReader.java:  196  clojure.lang.LispReader/read
               LispReader.java:  190  clojure.lang.LispReader/read
                      core.clj: 3640  clojure.core/read
                      core.clj: 3638  clojure.core/read
        interruptible_eval.clj:   68  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn/fn
                      main.clj:  238  clojure.main/repl/read-eval-print/fn
                      main.clj:  238  clojure.main/repl/read-eval-print
                      main.clj:  258  clojure.main/repl/fn
                      main.clj:  258  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   58  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  630  clojure.core/apply
                      core.clj: 1868  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  191  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  159  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.RuntimeException
   No reader function for tag dbg

               LispReader.java: 1245  clojure.lang.LispReader$CtorReader/readTagged
               LispReader.java: 1228  clojure.lang.LispReader$CtorReader/invoke
               LispReader.java:  684  clojure.lang.LispReader$DispatchReader/invoke
               LispReader.java:  263  clojure.lang.LispReader/read
               LispReader.java:  196  clojure.lang.LispReader/read
               LispReader.java:  190  clojure.lang.LispReader/read
                      core.clj: 3640  clojure.core/read
                      core.clj: 3638  clojure.core/read
        interruptible_eval.clj:   68  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn/fn
                      main.clj:  238  clojure.main/repl/read-eval-print/fn
                      main.clj:  238  clojure.main/repl/read-eval-print
                      main.clj:  258  clojure.main/repl/fn
                      main.clj:  258  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   58  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  630  clojure.core/apply
                      core.clj: 1868  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  191  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  159  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

```

**Comment by Malabarba** [comment] 2015-10-13 15:55
I still need the profiles+project of anyone who has the bug. :-)

**Comment by expez** [comment] 2015-10-14 07:35
```clj
(defproject keyhole "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]])
```

```clj
{:user {:plugins [[lein-localrepo "0.5.3"]
                  [lein-ancient "0.6.3"]
                  [com.jakemccrary/lein-test-refresh "0.10.0"]
                  [refactor-nrepl "2.0.0-SNAPSHOT"]
                  [cider/cider-nrepl "0.10.0-SNAPSHOT"]]
        :test-refresh {:quiet true}
        :repl-options {:init (do
                               (set! *print-length* 200)
                               (require '[clojure.repl :refer :all]))}
        :jvm-opts ["-XX:-OmitStackTraceInFastThrow"]
        :dependencies [[pjstadig/humane-test-output "0.6.0"]
                       [print-foo "1.0.1"]
                       [spyscope "0.1.5"]
                       [org.clojure/tools.nrepl "0.2.10"]
                       [acyclic/squiggly-clojure "0.1.2-SNAPSHOT"]
                       [im.chit/vinyasa "0.3.0"]]
        :injections [(require 'spyscope.core)
                     (require 'print.foo)
                     (require '[vinyasa.inject :as inject])

                     (inject/in ;; the default injected namespace is `.`

                      ;; note that `:refer, :all and :exclude can be used
                      [vinyasa.inject :refer [inject [in inject-in]]]

                      ;; imports all functions in vinyasa.pull
                      [vinyasa.pull :all]

                      ;; inject into clojure.core
                      clojure.core
                      [vinyasa.reflection .> .? .* .% .%> .& .>ns .>var]
                      clojure.core
                      [print.foo :all]

                      ;; inject into clojure.core with prefix
                      clojure.core >
                      [clojure.pprint pprint]
                      [clojure.java.shell sh])

                     (require 'pjstadig.humane-test-output)
                     (pjstadig.humane-test-output/activate!)]}}
```

**Comment by ibcoleman** [comment] 2015-10-15 00:03
```
What do you get if you evaluate each of the following expressions on the repl?

*data-readers*
cider.nrepl.middleware.debug/debug-reader
```

I get the following:

```
RuntimeException No reader function for tag dbg  clojure.lang.LispReader$CtorReader.readTagged (LispReader.java:1245)
user> *data-readers*
{}
user> cider.nrepl.middleware.debug/debug-reader
#object[cider.nrepl.middleware.debug$debug_reader 0x6c3a81f8 "cider.nrepl.middleware.debug$debug_reader@6c3a81f8"]
```

My .lein/profiles.clj is:

```
{:user {:plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]]}}
```

My project.clj is:

```
(defproject clojure-scratch "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/math.numeric-tower "0.0.4"]]
  :main ^:skip-aot clojure-scratch.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

The *cider-error* window shows:
``` 

  Show: Clojure Java REPL Tooling Duplicates All  (22 frames hidden)

2. Unhandled clojure.lang.LispReader$ReaderException
   java.lang.RuntimeException: No reader function for tag dbg

               LispReader.java:  292  clojure.lang.LispReader/read
               LispReader.java:  196  clojure.lang.LispReader/read
               LispReader.java:  190  clojure.lang.LispReader/read
                      core.clj: 3640  clojure.core/read
                      core.clj: 3638  clojure.core/read
        interruptible_eval.clj:   68  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn/fn
                      main.clj:  238  clojure.main/repl/read-eval-print/fn
                      main.clj:  238  clojure.main/repl/read-eval-print
                      main.clj:  258  clojure.main/repl/fn
                      main.clj:  258  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   58  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  630  clojure.core/apply
                      core.clj: 1868  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  191  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  159  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.RuntimeException
   No reader function for tag dbg

               LispReader.java: 1245  clojure.lang.LispReader$CtorReader/readTagged
               LispReader.java: 1228  clojure.lang.LispReader$CtorReader/invoke
               LispReader.java:  684  clojure.lang.LispReader$DispatchReader/invoke
               LispReader.java:  263  clojure.lang.LispReader/read
               LispReader.java:  196  clojure.lang.LispReader/read
               LispReader.java:  190  clojure.lang.LispReader/read
                      core.clj: 3640  clojure.core/read
```

**Comment by expez** [comment] 2015-10-15 07:16
```
keyhole.core> *data-readers*
{ordered/set
 #<Var@5249e568: 
   #object[ordered.set$into_ordered_set 0x140f4c8c "ordered.set$into_ordered_set@140f4c8c"]>,
 ordered/map
 #<Var@57d2b7bd: #object[ordered.map$ordered_map 0x382f9976 "ordered.map$ordered_map@382f9976"]>,
 spy/p
 #<Var@6c96b848: #object[spyscope.core$print_log 0x10d8d860 "spyscope.core$print_log@10d8d860"]>,
 spy/d
 #<Var@4ec3fe2c: 
   #object[spyscope.core$print_log_detailed 0x257dcbbd "spyscope.core$print_log_detailed@257dcbbd"]>,
 spy/t #<Var@6a98e283: #object[spyscope.core$trace 0x7cec71f6 "spyscope.core$trace@7cec71f6"]>}

keyhole.core> cider.nrepl.middleware.debug/debug-reader
#object[cider.nrepl.middleware.debug$debug_reader 0x5d3725e9 "cider.nrepl.middleware.debug$debug_reader@5d3725e9"]
```

**Comment by Malabarba** [comment] 2015-10-19 16:03
Ok, I've installed lein 2.5.3, and using immitating those projects I still can't reproduce this. So I'm going to start taking some shots at the dark.

The commit I just pushed *might* fix it. I'll push to clojars when I get home.

**Comment by Malabarba** [comment] 2015-10-19 22:33
Ok. it's on clojars.
Let me know if the latest snapshot fixes the issue. Otherwise I'll try something else.

**Comment by expez** [comment] 2015-10-22 08:38
This still happens.  Perhaps you should try registering the data readers in another way?  You could do what [spyscope](https://github.com/dgrnbrg/spyscope/blob/master/src/data_readers.clj) does.  Such a file at the root is 'magical' and can be used to extend the `*data-readers*`.

Here's some more information about this machine:

```clj
; CIDER 0.10.0snapshot (package: 20151019.2303) (Java 1.8.0_31, Clojure 1.7.0, nREPL 0.2.10)
```

My lein version, 2.5.0, is somewhat old, but even getting lein to work on windows was such a pain I'm not touching it again until everything is fucked.

**Comment by Malabarba** [comment] 2015-10-28 07:37
@expez Neat! Didn't know about that.

I've changed to that approach. Again, let me know if it worked.

**Comment by expez** [comment] 2015-10-28 08:26
@Malabarba That did it for me.  Thanks!

I wonder what was special about his project, perhaps clojure 1.7? I don't have any other deps and I haven't changed my `profiles.clj` in a while.

@ibcoleman can you confirm the fix before we close this?

**Comment by Malabarba** [comment] 2015-10-28 08:37
@expez My guess would be that it has something to do with the new tools.nrepl release, and possibly a conflict with a specific lein version.

**Comment by expez** [comment] 2015-10-28 08:51
We were both on 2.10 of nrepl but on 2.5.0 and 2.5.3 of lein.  I've since upgraded to 2.11, so I suppose that might've been what fixed it, but that doesn't explain why failure was limited to a single project for me.

**Comment by ibcoleman** [comment] 2015-10-29 21:29
@expez Sorry to be incommunicado. On my end the issue seems to have been project dependent, but things seem to be working again even with that project. Looks good to me!

**Closed** 2015-10-30 10:42 UTC
Labels: bug, debugger

**Comment by Malabarba** [comment] 2015-10-30 10:45
:+1:

**Comment by lambdatronic** [comment] 2016-05-12 20:27
Howdy folks,

Since I can't seem to find this explained anywhere online, I'll post it here. If you are experiencing this error when using the CIDER debugger with Boot, the problem seems to be that Boot doesn't automatically load the data_readers.clj files from your project's dependencies. To bring in the debugger's tags (#dbg, #break, #light), you just have to add this line to the end of your $BOOT_HOME/profile.boot:

`(boot.core/load-data-readers!)`

That's it. Easy peasy. Now the debugger should work in all of your Boot projects. So here's my complete profile.boot:

```
(require 'boot.repl)

(swap! boot.repl/*default-dependencies*
       concat '[[cider/cider-nrepl "0.12.0"]])

(swap! boot.repl/*default-middleware*
       conj 'cider.nrepl/cider-middleware)

;; Enable debugging in Boot
(boot.core/load-data-readers!)
```

Once you've launched a repl with boot repl or M-x cider-jack-in, eval (keys *data-readers*) and verify that dbg, break, and light are present in that map.

NOTE: If your project's dependencies provide additional data_readers.clj files, you'll have to include the (boot.core/load-data-readers!) line in your project's build.boot as well to import them. In all cases, the debugger should work with the fix to $BOOT_HOME/profile.boot that I described above.

Happy hacking!
  Gary
