### ISSUE TITLE
"No source location" when jumping to source on remote TRAMP file

### ISSUE THREAD

**Issue by weissjeffm** [clojure-emacs/cider#2162] opened 2018-01-12 15:54 UTC
## Expected behavior

Can jump to source when visiting a remote TRAMP file using a TRAMP repl

## Actual behavior

"No source location"

## Steps to reproduce the problem

I traced this error down to the following function in cider-common.el:

```emacs-lisp
(defun cider-tramp-prefix (&optional buffer)
  "Use the filename for BUFFER to determine a tramp prefix.
Defaults to the current buffer.
Return the tramp prefix, or nil if BUFFER is local."
  (let* ((buffer (or buffer (current-buffer)))
         (name (or (buffer-file-name buffer)
                   (with-current-buffer buffer
                     default-directory))))
    (when (tramp-tramp-file-p name)
      (with-parsed-tramp-file-name name v
        ;; `tramp-make-tramp-file-name' was changed to take 6 mandatory
        ;; parameters in Emacs 26 instead of 4
        (if (version< emacs-version "26")
            (with-no-warnings
              (tramp-make-tramp-file-name v-method v-user v-host v-localname))
          (with-no-warnings
            (tramp-make-tramp-file-name v-method v-user v-domain v-host v-port v-localname)))))))
```

The problem is that this function does not return a **prefix**, it returns the full tramp path, including the file path at the remote end.

So the function `cider--client-tramp-filename` will tack on yet another local path (eg "ssh:host:/foo/bar.txt/foo/quux.txt"), which results in a non-existent TRAMP location and leads to the error.

I was able to fix this by replacing `v-localname` with `""` in the function above, but I'm not sure if that's the best way to fix it.

## Environment & Version information

Emacs 25.3, OS X

### CIDER version information

```
;; CIDER 0.16.0 (Riga), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_144
```

**Comment by bbatsov** [comment] 2018-01-13 07:34
Seems like a duplicate of a bug that was recently fixed on `master` https://github.com/clojure-emacs/cider/pull/2156

**Closed** 2018-01-14 20:31 UTC
