### ISSUE TITLE
Namespace Not Found even when evaling NS form in 0.9.

### ISSUE THREAD

**Issue by phillord** [clojure-emacs/cider#1145] opened 2015-06-19 22:06 UTC
I am getting a "Namespace Not Found" error from cider, ironically, when attempting to eval a namespace form. Currently, I find that it is difficult to replicate this error in a simple test case, so I report it here in case anyone else has seen it. It does not appear to occur in a newly lein created project.

The "Namespace Not Found" error can be worked around in two ways. First, the whole buffer can be evaluated. This works fine -- even if the eval crashes, it is now possible to evaluate individual forms. Second, if the REPL buffer is switched to the current namespace (with C-cM-n) then again the problem disappears.

This is against CIDER 0.9. I have not noticed a problem with 0.8 previously.

**Comment by bbatsov** [comment] 2015-06-20 05:41
This is a duplicate of #1139.

**Closed by bbatsov** 2015-06-20 05:41 UTC

**Comment by phillord** [comment] 2015-06-20 08:25
Ah, apologies, not sure how I missed that. Does appear to be the same problem. Thanks for fixing!
