### ISSUE TITLE
cider-connect-clj fails with wrong-type-argument stringp

### ISSUE THREAD

**Issue by ChrisHacker** [clojure-emacs/cider#3406] opened 2023-08-13 18:36 UTC
## Expected behavior
cider-connect-clj connects to specified localhost:port repl
## Actual behavior
fails with error `wrong-type-argument stringp ("/home/PATH/REDACTED/" "40000")
## Steps to reproduce the problem
While in an open clj buffer, call M-x cider-connect, provide "localhost" as host value, and hit enter

### CIDER version information

cider doesn't launch - from package-manager 20230811.1023

### Lein / Clojure CLI version

Leiningen 2.10.0 on Java 17.0.5 OpenJDK 64-Bit Server VM

### Emacs version

27.1

### Operating system

Ubuntu 22.04

### JDK distribution

Java 17.0.5 OpenJDK

```
Debugger entered--Lisp error: (wrong-type-argument stringp ("/home/PATH/REDACTED/" "40000"))                                                                                                              
   directory-file-name(("/home/PATH/REDACTED/" "40000"))                                                                                                                                                   
   #f(compiled-function (x) #<bytecode 0x1563d5a7a4c5>)((("/home/PATH/REDACTED/" "40000") ("/home/PATH/REDACTED/" "40000")))                                                                          
   mapcar(#f(compiled-function (x) #<bytecode 0x1563d5a7a4c5>) ((("/home/PATH/REDACTED/" "40000") ("/home/PATH/REDACTED/" "40000"))))                                                                 
   cider-locate-running-nrepl-ports("/home/PATH/REDACTED/")                                                                                                                                         
   cider--infer-ports(#("localhost" 0 9 (idx 0 ivy-index 0)) (("blits") (#("chris" 0 6 (tramp-default t)))))                                                                                                   
   cider-select-endpoint()                                                                                                                                                                                      
   cider--update-host-port((:project-dir "/home/PATH/REDACTED/"))                                                                                                                                          
   cider-connect-clj(nil)                                                                                                                                                                                       
   funcall-interactively(cider-connect-clj nil)                                                                                                                                                                 
   #<subr call-interactively>(cider-connect-clj record nil)                                                                                                                                                     
   apply(#<subr call-interactively> cider-connect-clj (record nil))                                                                                                                                             
   call-interactively@ido-cr+-record-current-command(#<subr call-interactively> cider-connect-clj record nil)                                                                                                   
   apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (cider-connect-clj record nil))                                                                                           
   call-interactively(cider-connect-clj record nil)                                                                                                                                                             
   command-execute(cider-connect-clj record)                                                                                                                                                                    
   counsel-M-x-action("cider-connect-clj")                                                                                                                                                                      
   ivy-call()                                                                                                                                                                                                   
   ivy-read("M-x " ("emacs-version" "package-list-packages" "toggle-debug-on-error" "cider-jack-in" "kill-emacs" "cider-connect" "ag" "cd" "5x5" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "l$
   counsel-M-x()                                                                                                                                                                                                
   funcall-interactively(counsel-M-x)                                                                                                                                                                           
   #<subr call-interactively>(counsel-M-x nil nil)                                                                                                                                                              
   apply(#<subr call-interactively> counsel-M-x (nil nil))                                                                                                                                                      
   call-interactively@ido-cr+-record-current-command(#<subr call-interactively> counsel-M-x nil nil)                                                                                                            
   apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (counsel-M-x nil nil))                                                                                                    
   call-interactively(counsel-M-x nil nil)                                                                                                                                                                      
   command-execute(counsel-M-x)                     
```

**Comment by bbatsov** [comment] 2023-08-13 20:59
I'm guessing that's a duplicate of #3405.

**Closed** 2023-08-13 22:12 UTC

**Comment by vemv** [comment] 2023-08-13 22:14
I could repro this an verify the fix worked. Please update CIDER when a snapshot is published again (this normally happens a couple hours after a master commit).

Apologies for the nuisance.

Cheers - V
