### ISSUE TITLE
cider-jack-in-clojurescript starts 2 repl's of type clj

### ISSUE THREAD

**Issue by mallt** [clojure-emacs/cider#2271] opened 2018-04-18 12:48 UTC
## Expected behavior
`cider-jack-in-clojurescript` starts 1 repl of type `clj` and 1 repl of type `cljs`

## Actual behavior
`cider-jack-in-clojurescript` starts 2 repl's of type `clj`

<img width="507" alt="image" src="https://user-images.githubusercontent.com/8885691/38932465-8f539f9e-4316-11e8-8e2d-4887e507e710.png">

## Steps to reproduce the problem
- create new reagent project with `lein new reagent test-reagent`
- open file core.cljs
- M-x `cider-jack-in-clojurescript`

### CIDER version information
CIDER 0.17.0snapshot (package: 20180417.2312), nREPL 0.2.13
Clojure 1.9.0, Java 1.8.0_162

### Lein/Boot version
Leiningen 2.7.0

### Emacs version
GNU Emacs 27.0.50

### Operating system
Kubuntu 16.04.4 LTS

**Comment by mallt** [comment] 2018-04-18 13:02
I noticed before opening url http://0.0.0.0:3449 to make connection with figwheel, the repl type is still `cljs`. So it seems the figwheel connection changes the repl type to `clj`, would that be possible? Is there a way to avoid this?

Thanks!

**Comment by AsAddict** [comment] 2018-04-18 15:55
I had the same problem on my mac today....

**Comment by bbatsov** [comment] 2018-04-18 20:37
That's fixed in `master`. In the morning I messed things up, while hacking on piggieback. Sorry about that!

**Closed by bbatsov** 2018-04-18 20:37 UTC

**Comment by mallt** [comment] 2018-04-18 20:45
No problem, thanks a lot!

**Comment by saevarb** [comment] 2018-04-18 22:00
Hello.

I just spent the better part of an hour tracking down this bug. I guess I must have updated my spacemacs packages or something, since I had no issues a couple of days ago and now it's causing me problems.

You say you fixed this on master -- okay, but what steps do I need to take to fix this? What combination of dependencies and their versions? 

Right now I'm using `cider/piggieback 0.3.0`  as per the updated readme, as well as `figwheel-sidecar 0.5.0-2` in my `project.clj`. Trying to start the repl via `cider-jack-in-clojurescript` gives me a `Stdin: ` prompt in the minibuffer through which the CLJS repl takes input, and trying to write directly in the CLJS repl buffer simply doesn't work.

**Comment by dpsutton** [comment] 2018-04-18 22:04
This was caused by a SNAPSHOT package being updated, which lein happily updated for you without bumping the version.

In order to fix this, we need to get the new cider-nrepl code. An easy way to do this should be `lein deps -U` which should force an update of your dependencies. If not, delete the `~/.m2/repository/cider` directory and you will get all new code which contains the fix.

**Comment by saevarb** [comment] 2018-04-18 22:09
Wow, thanks for the fast answer :) It seems `lein` doesn't recognize `-U` as a subcommand to `deps`, but deleting the directory worked and now everything works as it did before. Cheers!

**Comment by dpsutton** [comment] 2018-04-18 22:11
cool. Sorry about the `- U` it does something somewhere :). Sorry about the disruption!

**Comment by bbatsov** [comment] 2018-04-19 04:50
Just keep in mind that `figwheel` hasn't release a version supporting piggieback 0.3 yet (it supports it only in its current snapshot version). So you should either update to it, or go back to piggieback 0.2.2.
