### ISSUE TITLE
Error printing java object

### ISSUE THREAD

**Issue by archaic** [clojure-emacs/cider#963] opened 2015-02-02 00:11 UTC
Using cider 0.8.2, Java 1.7.0_72, Clojure 1.7.0-alpha5, nREPL 0.2.6

Printing a java object (from HtmlUnit) in a standard lein REPL prints:

`#<HtmlSubmitInput HtmlSubmitInput[<input type="submit" name="ctl00$ContentPlaceHolder1$rptrNSWTABRacing$ctl00$btnFields" value="" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$rptrNSWTABRacing$ctl00$btnFields&quot;, &quot;&quot;, false, &quot;&quot;, &quot;/Racing/RacingFormFields.aspx?meetid=227415&quot;, false, false))" id="ctl00_ContentPlaceHolder1_rptrNSWTABRacing_ctl00_btnFields" title="Fields" class="formButton fields">]>`

Printing the identical object from within emacs in a CIDER REPL does not throw
an error, however, does not print the form and in *Messages* and the minibuffer
prints: 

error in process filter: clojure-string-start: Search failed: "\\(\\s-\\|^\\|#\\|(\\|\\[\\|{\\)\\(\"\\)"

If it would be helpful I can construct a minimal project with HtmlUnit
dependencies and the exact object causing the problem.

**Comment by bbatsov** [comment] 2015-02-02 06:55
> If it would be helpful I can construct a minimal project with HtmlUnit
> dependencies and the exact object causing the problem.

Yes. Although, I'm fairly certain where the problem is (`clojure-string-start`).

**Comment by archaic** [comment] 2015-02-04 23:37
Here is that project:
https://github.com/archaic/cider_issue

**Comment by bbatsov** [comment] 2016-07-11 07:48
Nobody has complained about this for a while, so I'll just close this issue.

**Closed by bbatsov** 2016-07-11 07:48 UTC
Labels: bug

**Comment by Bost** [comment] 2017-03-23 16:28
To mee it looks like CIDER 0.14.0 (Berlin) still contains this problem:
```
error in process filter: clojure-string-start: Search failed: "\\(\\s-\\|^\\|#\\|(\\|\\[\\|{\\)\\(\"\\)"
error in process filter: Search failed: "\\(\\s-\\|^\\|#\\|(\\|\\[\\|{\\)\\(\"\\)"
```
