### ISSUE TITLE
cider-repl--position-in-history not working

### ISSUE THREAD

**Issue by turbopape** [clojure-emacs/cider#1123] opened 2015-06-12 16:21 UTC
When I try going to previous repl entries using C-(arrow-up) or typing the command I get the following error: 
cider-repl--position-in-history: Symbol's function definition is void: forward
I am running newest cider version from Melpa, on emacs 25.0.50.2

**Comment by expez** [comment] 2015-06-13 21:14
Could you `M-x toggle-debug-on-error` and provide a stacktrace?  This code hasn't been touched for quite some time and it's working fine for me.  You sure this isn't just a bad interaction with your config?

**Comment by turbopape** [comment] 2015-06-15 10:28
I did not change my config from a while.

here is the stacktrace:
Debugger entered--Lisp error: (void-function forward)
  forward(-1)
  cider-repl--position-in-history(-1 backward "")
  cider-repl--history-replace(backward nil)
  cider-repl-backward-input()
  funcall-interactively(cider-repl-backward-input)
  #<subr call-interactively>(cider-repl-backward-input nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> cider-repl-backward-input nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (cider-repl-backward-input nil nil))
  call-interactively(cider-repl-backward-input nil nil)
  command-execute(cider-repl-backward-input)
Thank you for your help.

**Comment by expez** [comment] 2015-06-15 10:37
`ad-Advice-call-interactively(# cider-repl-backward-input nil nil)`

This line in the stacktrace indicates that you've advised this function.  This is likely the cause of your problems.

**Comment by turbopape** [comment] 2015-06-15 10:55
And how do I find who is responsible for this addition? I don't remember setting it myself...

**Comment by expez** [comment] 2015-06-15 11:09
If you do `C-h f cider-repl-backward-input <RET>` it should tell you the name of the advice.  At that point you can grep through your `.emacs.d` to find the source location.

**Comment by turbopape** [comment] 2015-06-15 11:30
When describing the function I only get its deginition from the cider-repl.el file:
"cider-repl-backward-input is an interactive compiled Lisp function in
‘cider-repl.el’.

It is bound to <C-up>.

(cider-repl-backward-input)

Cycle backwards through input history."
Seems I messed around something with my emacsen when using the snapshot versions...

**Comment by expez** [comment] 2015-06-15 11:35
You can probably find where the advice is being added by grepping for `advice` in your `.emacs.d`.

I'm gonna close this because it appears this is related to your emacs config.  Please re-open this issue if you can follow [these steps](https://github.com/clojure-emacs/cider#issues) and still reproduce the problem.

**Closed by expez** 2015-06-15 11:35 UTC

**Comment by turbopape** [comment] 2015-06-15 12:25
Seems that helm, for an unknown reason, is advising my functions. I will investigate. Thank you.
