### ISSUE TITLE
cider-restart not working

### ISSUE THREAD

**Issue by hugoduncan** [clojure-emacs/cider#1480] opened 2015-12-22 14:07 UTC
Running `M-x cider-restart` from a REPL buffer or a `.clj` file results in:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  cider--restart-connection(nil)
  cider-restart(nil)
  funcall-interactively(cider-restart nil)
  call-interactively(cider-restart record nil)
  command-execute(cider-restart record)
  execute-extended-command(nil "cider-restart")
  funcall-interactively(execute-extended-command nil "cider-restart")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by whysoserious** [comment] 2015-12-22 20:25
Confirmed, same happens for me. My `profiles.clj`:
```clojure
{:repl {:dependencies [[pjstadig/humane-test-output "0.7.0"]
                       [org.clojure/tools.nrepl "0.2.12"]]
        :injections [(require 'pjstadig.humane-test-output)
                     (pjstadig.humane-test-output/activate!)]
        :plugins [[cider/cider-nrepl "0.10.0"]
                  [refactor-nrepl "2.0.0-SNAPSHOT"]]}
 :user {:dependencies [[slamhound "1.5.5"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
```
cider version: `0.10.0` from MELPA stable

**Comment by bbatsov** [comment] 2015-12-23 12:57
The restart works for me with the current master. I wonder if this is some bug we've already fixed, or there's something more to reproducing it...

**Comment by cap10morgan** [comment] 2015-12-23 19:15
The combination of 5b450b33a7dfb644b47bac3fa070ac955f945f43 and 83b53804c6914a6500f5fe8935bcefbf0fd8040f seem to fix this.

**Comment by cap10morgan** [comment] 2016-01-09 20:17
@hugoduncan Is this fixed in 0.10.1?

**Comment by hugoduncan** [comment] 2016-01-09 22:28
@cap10morgan Seems to be fixed in HEAD.  Haven't tried 0.10.1.

**Comment by bbatsov** [comment] 2016-01-24 20:58
Let's assume it's fixed. :-)

**Closed** 2016-01-24 20:58 UTC
Labels: bug
