### ISSUE TITLE
cider-expected-ns returns nil on boot projects

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1651] opened 2016-04-03 19:18 UTC
This happens because the list of strings returned by `(cider-sync-request:classpath)` apparently doesn't include the project directory.
This, in turn, happens because boot masks the project under: `~/.boot/cache/tmp/FULL/PATH/ followed by some gibberish.

As a (hopefully) temporary patch, I'll make this function fallback on `clojure-expected-ns`.

**Comment by bbatsov** [comment] 2016-04-04 04:32
This bites us every time. I'm guessing we can reuse some of boot-related code for the info middleware.

**Comment by grzm** [comment] 2017-11-15 22:45
Digging into this a bit, it looks like the issue is related to the values returned by `cider-sync-request:classpath`. Boot added a `:fake-class-path` key to the boot environment (also available via the "fake.class.path" system property) to address issues like the one here. Some of this was addressed in https://github.com/clojure-emacs/cider-nrepl/commit/fbcecbaf10bb55aae875f93810b67b41c833da21 to access resource paths. Does it make sense for `cider-sync-request:classpath` to return `:fake-class-path` when running under boot? From what I can see, the only usage of this is in `cider-expected-ns`.

**Comment by grzm** [comment] 2017-11-16 01:30
I've put together a POC here: https://github.com/grzm/cider-nrepl/commit/4fe4a7021835a5cd2305a9a322c412b8bbd24c05. If this looks good, I'll submit a PR to cider-nrepl. (Should we continue this discussion under a ticket for cider-nrepl?)

**Closed** 2017-12-09 16:47 UTC
Labels: bug, Hacktoberfest
