### ISSUE TITLE
Cljs repl type selection window does not always show up

### ISSUE THREAD

**Issue by achikin** [clojure-emacs/cider#2245] opened 2018-03-21 17:45 UTC
## Expected behavior
When I do `cider-jack-in-clojurescript` repl selection window appears, let me choose repl type and then cljs repl is started.

## Actual behavior
If you open a helm window (e.g. `helm M-x` or `helm-mini`) after `cider-jack-in-clojurescript` but before cljs repl selection window shows up, then no selection window is shown and no cljs repl started.

**There is a long pause in the middle of the gif while repl starts. Please hold on and watch to the end**

![cider-3](https://user-images.githubusercontent.com/611419/37726944-a8f5d762-2d47-11e8-80dc-dcb14e856e27.gif)

## Steps to reproduce the problem
I can only confirm this with helm.
- `M-x cider-jack-in-clojurescript`
- `M-x` again immediately
- Wait until helm window disappears
- Check buffer list
*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

## Environment & Version information
Spacemacs
### CIDER version information

```
;; CIDER 0.17.0snapshot (package: 20180319.1204), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_20
```

### Lein/Boot version
Leiningen 2.8.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM

### Emacs version
GNU Emacs 25.3.1

### Operating system
macOS High Sierra 10.13.3

**Comment by bbatsov** [comment] 2018-03-24 03:29
Hmm, I've puzzled about this. Could it be some helm problem @xiongtx? 

@achikin Do you have this problem if you just run the jack-command without helm?

**Comment by xiongtx** [comment] 2018-03-24 05:37
If you check your `*Messages*`, you'll find something like:

```
[nREPL] Establishing direct connection to localhost:9009 ...
[nREPL] Direct connection to localhost:9009 established
Connected.  One REPL to rule them all, One REPL to find them, One REPL to bring them all, and in parentheses bind them!
Aborting an helm session running in background
```

Since you're using `helm-mode`, CLJS REPL type selection is a Helm session. By default, Helm sessions [cannot interrupt existing Helm sessions](https://github.com/emacs-helm/helm/blob/6f80bbcbf86f30ee827002189d86ffd962041180/helm.el#L2202).

Helm does have an [`:allow-nest`](https://github.com/emacs-helm/helm/blob/6f80bbcbf86f30ee827002189d86ffd962041180/helm-mode.el#L514) option which, if applied to [`helm-completing-read-default-1`](https://github.com/emacs-helm/helm/blob/6f80bbcbf86f30ee827002189d86ffd962041180/helm-mode.el#L717), would allow completing reads to interrupt existing Helm session.

This, however, is a "sledgehammer" solution that'd require modifying Helm itself, which @thierryvolpiatto probably wouldn't accept.

@bbatsov Is there a way to start a CLJS REPL given that the CLJ REPL has started? I've actually never tried. 

Since this problem is relatively rare, only occurring when you've a Helm session active at the exact moment the CLJS REPL selection prompt tries to appear, invoking a command to start the CLJS REPL again is probably a better solution that modifying Helm.

**Comment by achikin** [comment] 2018-03-24 19:32
@xiongtx 
> Since this problem is relatively rare, only occurring when you've a Helm session active at the exact moment the CLJS REPL selection tries to appear, invoking a command to start the CLJS REPL again is probably a better solution that modifying Helm.

This problem is not rare for me. I start repls, do some files navigation while repls are starting and then find out that there is no cljs repl.

**Comment by achikin** [comment] 2018-03-24 19:40
@bbatsov 
> Do you have this problem if you just run the jack-command without helm?
No I don't. If I wait patiently for repls both repls to start and don't try to use any helm buffers - all goes well. But If I navigate files/global search/enter or other things that involve helm - I usually end up with no cljs repl. Also that selection window tend to jump out when you are busy typing/entering some hotkeys, so you can occasionally skip it or choose some irrelevant option.
I think the solution could be to create a separate buffer for cljs repl and ask for repl type inside that buffer when user switches to it. Is it possible? 
It is not perfect because this way the repl is not started until you open the buffer, but at least that does not lead to the situation when repl is skipped completely.

**Comment by xiongtx** [comment] 2018-03-24 20:06
The issue is w/ the use of `helm-mode`. It's nothing to do w/ CIDER per se, which simply calls `completing-read`. Therefore, I don't think there's anything to fix on the CIDER side.

You can use a `dir-locals.el` file to set the REPL type for a project. Then you won't have to choose it every time.

**Comment by achikin** [comment] 2018-03-24 20:11
@xiongtx thank you, setting default repl type will solve my issue. Anyway it's more convenient than choosing repl type every time.
I disagree with you that it is not CIDER issue. Neither `helm` nor `completing-read` are not responsible for choosing repl type. The fact that CIDER is using a solution that leads to a failure is not an excuse.

**Comment by xiongtx** [comment] 2018-03-24 20:15
You can open an issue on Helm w/ this use case if you like. Regardless, I'll close this issue.

**Closed by xiongtx** 2018-03-24 20:15 UTC

**Comment by achikin** [comment] 2018-03-24 22:31
> You can open an issue on Helm w/ this use case if you like. Regardless, I'll close this issue.
I'm sorry, I didn't get it. Cider does not operate correctly because of the recently (and poorly) implemented functionality in cider itself. What kind of issue can I open in Helm?

**Comment by bbatsov** [comment] 2018-03-25 01:08
> I disagree with you that it is not CIDER issue. Neither helm nor completing-read are not responsible for choosing repl type. The fact that CIDER is using a solution that leads to a failure is not an excuse.

But as @xiongtx there's really nothing special about this code - it's just a regular prompt to read something from the minibuffer. As this works with everything else (`ido`, standard completing read and `ivy`), I'm inclined to believe that's something wrong with Helm. I don't use that package, so I can't provide much more guidance there. 

> I think the solution could be to create a separate buffer for cljs repl and ask for repl type inside that buffer when user switches to it. Is it possible?

You have to run some checks in advance, otherwise you don't really know if the cljs repl can be created to begin with. I don't think it's a good idea to create a potential throwaway buffer for this. I'm truly surprised something so basic doesn't work with Helm... I've got a few more ideas for improvements to the cljs startup process, maybe they'll help with your problem down the road. In the mean time it's probably best to just set the `cider-default-cljs-repl-type` to avoid getting that prompt altogether.
