### ISSUE TITLE
Bad performance in nrepl-show-maximum-output

### ISSUE THREAD

**Issue by acieroid** [clojure-emacs/cider#228] opened 2013-01-23 10:01 UTC
When printing lots of lines, the performances of nrepl are really bad (emacs hang out for a long time, depending how long is the *nrepl* buffer). This seems to come from nrepl-show-maximum-output:

````elisp
 (dotimes (i 1000)
   (with-current-buffer nrepl-nrepl-buffer
     (insert-before-markers "foo\n")
     (nrepl-show-maximum-output)))
````
Takes 0.7827s to run on a clean buffer (that has just been C-c C-o'd), while
````elisp
 (dotimes (i 1000)
   (with-current-buffer nrepl-nrepl-buffer
     (insert-before-markers "foo\n")))
````
only takes 0.0169s.

The more the *nrepl* buffer is long, the more time it will take. For example, with a ~13k lines buffer, it takes around 7s while only 0.018s without nrepl-show-maximum-output.

This affects the performance of clojure codes that prints lots of stuff (eg. `(dotimes [i 1000] (println "foo"))`) to the point that you might have to kill emacs because it does not respond anymore.

**Comment by sbocq** [comment] 2015-06-05 07:26
The issue is also present in CIDER.

I ran ELP on `CIDER 0.9.0snapshot (package: 20150315.528)` and here is what it reports when parsing large XML files with `data.zip.xml`:

Function Name |	Call Count | 	Elapsed Time | 	Average Time
-------------|-------------|-----------------|--------------
cider-repl--show-maximum-output|3|49.264890923|16.421630307
cider-repl-emit-result|1|33.385848477|33.385848477
cider-repl-clear-output|1|22.934797576|22.934797576
cider-repl--end-of-line-before-input-start|1|22.931481792|22.931481792
cider-repl-emit-prompt|1|15.849498747|15.849498747
cider-eldoc|2|0.857376006|0.428688003
cider-eldoc-info-in-current-sexp|2|0.857124579|0.4285622895
cider-eldoc-beginning-of-sexp|2|0.8566141789|0.4283070894
cider-repl-return|1|0.035156144|0.035156144
cider-repl--send-input|1|0.034885998|0.034885998
cider-current-ns|7|0.0004598360|6.569...e-05
cider-symbol-at-point|2|0.000410108|0.000205054
cider-repl--insert-prompt|1|0.000250591|0.000250591
cider-repl-previous-prompt|1|0.000247797|0.000247797
cider-repl--find-prompt|1|0.000227403|0.000227403
cider-search-property-change|2|0.000108952|5.4476e-05
cider-eldoc-arglist|2|9.4425e-05|4.72125e-05
cider-repl--input-complete-p|1|5.8388e-05|5.8388e-05
cider-connected-p|2|2.7378e-05|1.3689e-05
cider-end-of-proprange-p|3|2.7378e-05|9.126e-06
cider-repl-handler|1|2.5702e-05|2.5702e-05
cider-repl--current-input|1|2.5701e-05|2.5701e-05
cider-repl--mark-input-start|1|2.1232e-05|2.1232e-05
cider-repl--mark-output-start|1|1.9835e-05|1.9835e-05
cider-repl--in-input-area-p|1|1.1454e-05|1.1454e-05
cider-repl-default-prompt|1|1.0057e-05|1.0057e-05
cider-repl--add-to-input-history|1|9.778e-06|9.778e-06

Emacs becomes barely usable until it registers the next `C-c C-o` to clear the last output.

**Comment by bbatsov** [comment] 2015-06-05 08:26
Yep, this is still an issue. Unfortunately I never could find the time to dig deep into it. Help welcome!

**Comment by axsk** [comment] 2015-08-20 08:47
+1. And I thought there was some performance issue in my code until I saw the 543k information in the status bar and thought it might be the REPL :D.
Ended up suppressing the output for now.

**Comment by bbatsov** [comment] 2016-04-02 16:33
I think this was mostly addressed by @rfkm's recent work, so I'll close it.

**Closed by bbatsov** 2016-04-02 16:33 UTC
Labels: enhancement
