### ISSUE TITLE
No reader function for tag dbg with boot

### ISSUE THREAD

**Issue by sooheon** [clojure-emacs/cider#1596] opened 2016-02-29 10:42 UTC
Calling `cider-debug-defun-at-point` with a boot connected cider-repl errors out with `java.lang.RuntimeException: No reader function for tag dbg`. This is a duplicate issue of #1462, just a new issue as per @malabarba 's request.

## Steps to reproduce the problem

Contents of my profile.boot
```
(set-env!
 :dependencies '[[org.clojure/tools.nrepl "0.2.12"
                  :exclusions [org.clojure/clojure]
                  :scope "test"]
                 [boot-deps "0.1.4" :scope "test"]])

(require '[boot-deps :refer [ancient]]
         'boot.repl)

(swap! boot.repl/*default-dependencies* concat
       '[[cider/cider-nrepl "0.11.0-SNAPSHOT"]
         [refactor-nrepl "2.2.0-SNAPSHOT"]])

(swap! boot.repl/*default-middleware* conj
       'cider.nrepl/cider-middleware
       'refactor-nrepl.middleware/wrap-refactor)
```

cider-jack-in in a boot project and calling `cider-debug-defun-at-point` will reproduce.

### CIDER version information

```
;; CIDER 0.11.0snapshot (package: 20160228.454), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_60
```

### Emacs version

`GNU Emacs 24.5.1 (x86_64-apple-darwin15.4.0, NS apple-appkit-1404.41) of 2016-02-26 on Icarus`

### Operating system

OSX El Capitan

**Comment by mitchelkuijpers** [comment] 2016-03-01 13:14
A quick fix is running `(boot.core/load-data-readers!)` in your cider-repl, this works for me in emacs :dancers:

**Comment by Malabarba** [comment] 2016-04-12 20:44
Sorry nobody replied before. Indeed the workaround above is the only known solution. 

Closing as a duplicate of #1462.

**Closed by Malabarba** 2016-04-12 20:44 UTC

**Comment by ds2643** [comment] 2017-02-27 16:55
@mitchelkuijpers Do you know how to implement this solution in the context of a lein project?

**Comment by wminshew** [comment] 2020-08-26 03:46
having this issue w/ lein as well
