### ISSUE TITLE
CIDER-REPL prints entire buffer when symbol not found

### ISSUE THREAD

**Issue by yonkornilov** [clojure-emacs/cider#1389] opened 2015-10-29 13:25 UTC
Ever since bumping tools.nrepl to 0.2.11, CIDER now prints my entire namespace buffer in the REPL if I refer to a symbol that doesn't exist in that namespace.

This wasn't happening before bumbing to that version of tools.nrepl.

I suspected that this was a compatibility issue with the new version tools.nrepl and CIDER, but upgrading to the latest version from the Melpa repo didn't fix it.

Actually, this also extends to errors such as "Can't take value of macro"

**Comment by scottdw** [comment] 2015-10-29 15:54
`; CIDER 0.10.0snapshot (package: 20151025.1201) (Java 1.8.0_45, Clojure 1.7.0, nREPL 0.2.11)`

After executing `cider-load-buffer`, exceptions at the repl cause the contents of the buffer to be printed after the exception. eg:
```
user> undefined
CompilerException java.lang.RuntimeException: Unable to resolve symbol: undefined in this context, compiling:(***buffer text removed***:1:6403) 
```

**Comment by bbatsov** [comment] 2015-10-29 17:30
@cemerick Any ideas what might be causing this?

**Comment by scottdw** [comment] 2015-10-30 10:34
```
; CIDER 0.10.0snapshot (package: 20151028.758) (Java 1.8.0_45, Clojure 1.7.0, nREPL 0.2.10)
WARNING: CIDER requires nREPL 0.2.11 (or newer) to work properly
user> undefined
CompilerException java.lang.RuntimeException: Unable to resolve symbol: undefined in this context, compiling:(***temp folder***\form-init6925707551600658869.clj:1:6403) 
```

Reading through the code in `tools.nrepl` I think https://github.com/clojure/tools.nrepl/commit/64238a10a8465e0c590acb660ec5d54bf7cc3af4#diff-a15f8f9db1997aa5418a8345c820a473R68 is the culprit. In `load-file` `file` is used to refer to the contents of the file so maybe it should be `file-name`. But I'm not in a position to rebuild and test nrepl to confirm.

**Comment by bbatsov** [comment] 2015-10-30 10:51
@cichli Can you look into this?

**Comment by cemerick** [comment] 2015-10-30 14:48
`file` in the eval context corresponds to `*file*`, a path, not the contents.

Anyway, I can replicate this. Looks like CIDER is sending a file's contents to eval instead of the filename.

**Comment by cemerick** [comment] 2015-10-30 14:58
@scottdw ech, I see what you were referring to re: the connection with load-file:

https://github.com/clojure/tools.nrepl/blob/0d964f9821fd5c13293af79b83bad29fc954dc65/src/main/clojure/clojure/tools/nrepl/middleware/load_file.clj#L80

`file-name` needs to clobber `file` in that altered message.

**Comment by cemerick** [comment] 2015-10-30 15:09
This is fixed on nREPL master, `0.2.12-SNAPSHOT` will be available momentarily. Please test and report confirmation that the problem is resolved (or not).

**Comment by scottdw** [comment] 2015-10-30 16:04
Moving to `0.2.12-SNAPSHOT` does resolve this issue and doesn't appear to have introduced any breakages (AFAICT).

**Comment by bbatsov** [comment] 2015-10-30 16:05
Guess we need a stable release then.

On Friday, 30 October 2015, Scott Douglas-Watson <notifications@github.com>
wrote:

> Moving to 0.2.12-SNAPSHOT does resolve this issue and doesn't appear to
> have introduced any breakages (AFAICT).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1389#issuecomment-152566694>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by cemerick** [comment] 2015-10-30 16:17
Percolating through hudson now. Expect `0.2.12` in mvn central in an hour or so?

**Comment by bbatsov** [comment] 2015-10-30 16:20
Fantastic. I'm on a trip with a computer for the weekend, so someone else
should update CIDER's deps.

On Friday, 30 October 2015, Chas Emerick <notifications@github.com> wrote:

> Percolating through hudson now. Expect 0.2.12 in mvn central in an hour
> or so?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1389#issuecomment-152570819>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by bbatsov** [comment] 2015-10-30 16:21
Without a computer

On Friday, 30 October 2015, Bozhidar Batsov <bozhidar.batsov@gmail.com>
wrote:

> Fantastic. I'm on a trip with a computer for the weekend, so someone else
> should update CIDER's deps.
>
> On Friday, 30 October 2015, Chas Emerick <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Percolating through hudson now. Expect 0.2.12 in mvn central in an hour
>> or so?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/clojure-emacs/cider/issues/1389#issuecomment-152570819>
>> .
>>
>
>
> --
> Best Regards,
> Bozhidar Batsov
>
> http://www.batsov.com
>
>

-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by yonkornilov** [comment] 2015-10-30 16:45
Eagerly waited until 0.2.12 was up, and it works beautifully! None of this problem anymore. Thanks (:

**Comment by yonkornilov** [comment] 2015-10-30 17:36
I'll leave this issue to be closed to the devs, if you guys need to sort things out for CIDER or nREPL.

**Comment by Malabarba** [comment] 2015-10-30 17:57
I can merge and deploy those PRs by @scottdw once I get a confirmation that the release is up.

**Closed** 2015-10-30 19:17 UTC
Labels: bug

**Comment by Malabarba** [comment] 2015-10-30 19:19
Deployed.
