### ISSUE TITLE
On Windows 10, cider-quit doesn't quit.

### ISSUE THREAD

**Issue by mtnygard** [clojure-emacs/cider#1946] opened 2017-02-27 19:00 UTC
## Expected behavior

Running `cider-quit` should terminate both the leiningen JVM and the application JVM.

## Actual behavior

The leiningen JVM terminates, but the application JVM remains around.

## Steps to reproduce the problem

1. Create an empty leiningen project: `lein new repro-case`
2. Open `repro-case\project.clj`
3. Use M-x `cider-jack-in` to get a REPL. Use Task Manager to see there are two Java processes.
4. Immediately run M-x `cider-quit`.
5. Observe that one Java process exits, but the other remains.

### CIDER version information

;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_111

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_111 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

- Emacs 25.1.1

### Operating system

- Windows 10, build 15031.0

**Comment by bbatsov** [comment] 2017-02-28 13:31
That's a duplicate of https://github.com/clojure-emacs/cider/issues/390

Long story short - that's outside of CIDER's scope and we can't really do much about it.

**Closed by bbatsov** 2017-02-28 13:31 UTC
