### ISSUE TITLE
jack-in disables clojure-mode

### ISSUE THREAD

**Issue by blueberry** [clojure-emacs/cider#1317] opened 2015-09-11 15:44 UTC
After upgrade from 20150910 to 20150911 clojure-mode gets disabled each and every time something from a clojure buffer is evaluated in the repl. All clojure code loses syntax highlighting (for the clojure parts and parens).
After M-x clojure-mode, the highlihgting gets back. New evaluation disables it again.
 
Steps to reproduce:
1. create a new project: lein new cider-bug
2. Open project.clj in emacs
3. C-c M-j
result: no parens coloring in project.clj

**Comment by Malabarba** [comment] 2015-09-11 15:50
Could you verify your cider-nrepl version?

**Comment by blueberry** [comment] 2015-09-11 15:52
Yes. 0.10.0-SNAPSHOT
Also tried 0.9.1 - the problem stays
The bug appeared after emacs restart (and I suppose an automatic update) with no change in setup and projects that worked this morning

**Comment by expez** [comment] 2015-09-11 16:23
@blueberry I can't reproduce this.

Can you clone this repo and run `make run-cider` and see if you can reproduce the issue without your configuration?

If you don't have cask installed (dependency management for emacs) you can install it with 

`curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh`

**Comment by Malabarba** [comment] 2015-09-11 16:33
Do you get any messages indicating what might have happened?

**Comment by blueberry** [comment] 2015-09-11 20:14
I have tried make run-cider, but it shows plain vanilla emacs that shows all parens in black anyway. That's why this can't be reproduced, or can, but cannot be seen on the screen.

My emacs is basically emacs 24.5.1 with prelude and very minimal personal setings (literally a few lines setting a few keybindings unrelated to clojure). I commented out everything from the personal configuration and the problem is still there after restarting emacs.

**Comment by blueberry** [comment] 2015-09-11 20:25
As for messages, this is the contents of *Messages* buffer after starting the REPL (seems normal to me):

Making nrepl-create-client-buffer-function local to *nrepl-server cider-bug* while let-bound!
Making nrepl-use-this-as-repl-buffer local to *nrepl-server cider-bug* while let-bound!
Starting nREPL server via lein repl :headless...
nREPL server started on 53108
nREPL: Establishing direct connection to localhost:53108 ...
nREPL: Direct connection established
Connected.  Controlling complexity is the essence of computer programming. -Brian Kernighan

**Comment by expez** [comment] 2015-09-11 20:25
Aight, then this is a problem with your config and not a bug related to CIDER.  CIDER isn't involved in color parenthesis, and neither is clojure-mode.  Likely you have something like rainbow-delimiters-mode which is applied in the clojure-mode-hook.  Something goes wrong when your custom hook code runs, sometimes, causing it to not get to the rainbow delimiters part.  When you do `M-x clojure-mode` the hook is run again, but this time it works.

**Comment by expez** [comment] 2015-09-11 20:27
You can do do `C-h v clojure-mode-hook <RET>` to inspect the value of that hook if you need further assistance debugging this.

**Comment by blueberry** [comment] 2015-09-11 20:53
But I have coloring and everything with my PLAIN VANILLA emacs. My hook code (and the whole custom.el) is literally only this:
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    (<some hashes here>  default))))

(load-theme 'cyberpunk)
(scroll-bar-mode -1)
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
(add-hook 'prog-mode-hook 'paredit-everywhere-mode)
(add-hook 'clojure-mode-hook 'smartparens-strict-mode)
;display line numbers in all frames
(global-set-key (kbd "C-x n RET") 'linum-mode)

;;recognize OpenCL *.cl files as c source code
(setq auto-mode-alist (cons '("\.cl$" . c-mode) auto-mode-alist))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
)
----------------------------------------------------------------

I identified that this option from cider is the problem, and everything works fine if I set:
(setq cider-font-lock-dynamically '())

Of course, then there is a problem of font locking not working...

**Comment by blueberry** [comment] 2015-09-11 21:20
And to add about the clojure-mode-hook:

1. If i disable cider-font-lock-dynamically, it is:
 (cider-mode
 #[nil "\300\301!\207"
       [run-hooks prelude-clojure-mode-hook]
       2]
 er/add-clojure-mode-expansions smartparens-strict-mode)

2. When I enable it, it is:
(cider-mode
 #[nil "\300\301!\207"
       [run-hooks prelude-clojure-mode-hook]
       2]
 er/add-clojure-mode-expansions smartparens-strict-mode)

So, that value is the same.

**Comment by Malabarba** [comment] 2015-09-11 21:30
It's possible we're doing something incompatible with `rainbow-delimiters-mode`, the question is whose bug is it.

**Comment by blueberry** [comment] 2015-09-11 21:36
I do not insist on rainbow-delimiters-mode - any alternative that works for you is fine for me. Can you please share a relevant part of your own configuration that works?

**Comment by bbatsov** [comment] 2015-09-11 21:36
Perhaps it's something similar to https://github.com/clojure-emacs/cider/issues/749?

**Comment by Malabarba** [comment] 2015-09-11 21:43
@blueberry This whole conversation was slightly confusing. Could you show us a screenshot of the problem? I just want to see what your clojure buffers look like when this issue happens.

**Comment by blueberry** [comment] 2015-09-12 16:26
To sum it up:
Problem: after jack-in, code such as this:
[[[[[[]]]]]]
loses rainbow coloring in the clj file

Why I think it is not due to my custom configuration:
I REINSTALLED PRELUDE from scratch, enabled clojure language support, have absolutely no custom config, and the problem is still there. Plus, everything worked fine until cider 20150911.253

Since I have found a (clunky) workaround, It is not something urgent. Thank you for providing such an excellent tool with prompt support. It seems to me I have to find time to read the elisp book, so I can investigate such problems in more detail when they arise.

You can close the issue if you think it does not affect other users, although I'd be surprised if it is so since I've tried a fresh prelude install and the problem is still here...

**Comment by expez** [comment] 2015-09-12 16:34
@blueberry `prelude` is several thousand lines of custom config...

It's likely that other users are affected by this.  Both `prelude` and `rainbow-delimiters-mode` are popular packages. 

What was your workaround?  Perhaps that gives some indication as what went wrong.

**Comment by blueberry** [comment] 2015-09-12 16:43
The workaround is adding this line to the custom config:

(setq cider-font-lock-dynamically '())

Of course, it is clunky because it disables font locking for macros and core...

**Comment by corymickelson** [comment] 2015-09-13 21:16
I am having this same issue with rainbow-delimiters-mode, after connecting to cider some other modes no longer seem to work. Thanks for the workaround for now though.....

**Comment by Malabarba** [comment] 2015-09-13 22:42
I just installed rainbow-delimiters and can verify this happens as well.
I can only assume this happens because we change the value of `clojure-font-lock-keywords`, and rainbow delimiters somehow depends on that(?).

    (setq-local cider-font-lock-keywords
                (append clojure-font-lock-keywords
                        (cider--compile-font-lock-keywords)))

@Fanael Do you think that could be the cause? Is there an appropriate way to change a buffer's font-lock-keywords without screwing with `rainbow-delimiters`?

**Comment by Malabarba** [comment] 2015-09-13 22:48
Hm, I think I see the problem. Rainbow-delimiters sets the `syntax-begin-function`, and `(font-lock-refresh-defaults)` *probably* resets this variable to the default value.

I'm not sure, but it's the only thing I can think of.

**Comment by Malabarba** [comment] 2015-09-13 23:08
That was it. Should be fixed now.

**Closed** 2015-09-13 23:08 UTC

**Comment by blueberry** [comment] 2015-09-14 13:20
it works ok now. thank you.
