### ISSUE TITLE
cider-find-var takes me to the temporary files in boot cache, not original code

### ISSUE THREAD

**Issue by sooheon** [clojure-emacs/cider#2076] opened 2017-08-16 00:26 UTC
## Expected behavior

A user calls `cider-find-var`, edits some code, saves and pops back with `cider-pop-back`, and this is all persisted to the actual codebase.

## Actual behavior

`cider-find-var` takes me to an identical looking file deep in the tmp directory. If I mistakenly make changes here, the next time I open the project they will be gone.

This issue is resolved if I manually navigate to the ns in question, load the file with `cider-load-buffer`. Afterwards, `cider-find-var` will take me to this loaded buffer. But the desired behavior is for cider to do this automatically the first time you try to find a var definition.

## Steps to reproduce the problem

Jack in with boot (haven't tested if lein will reproduce), press M-. over any symbol which you have defined in a different namespace.

### CIDER version information

```
;; CIDER 0.15.1snapshot (package: 20170729.133), nREPL 0.2.12
;; Clojure 1.9.0-alpha17, Java 1.8.0_131
```

### Lein/Boot version

boot 2.7.2-SNAPSHOT

### Emacs version

GNU Emacs 25.2.2 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-07-30

### Operating system

macOS 10.12.6

**Comment by pandeiro** [comment] 2017-08-22 18:10
@sooheon I've heard about this problem anecdotally but I am not able to reproduce it with a minimal Boot/Clojure project. Perhaps creating repository with a minimal reproduction case would be a good first step to figuring out what's going on?

**Comment by sooheon** [comment] 2017-09-13 00:36
@pandeiro I spent a lot of time bisecting my config, before finding clj-refactor as the culprit.

Specifically, `(setq cljr-warn-on-eval nil cljr-eagerly-build-asts-on-startup t)`, along with the recommended [setup](https://github.com/clojure-emacs/clj-refactor.el#setup) causes this problem (on my machine).

The minimum reproducing case, if you want to try: 
1. emacs -Q
2. Selectively install only cider and clj-refactor, with setup described above.
3. Clone the following repo, go to `foo.clj` and jack-in. https://github.com/sooheon/bugcatcher/blob/master/src/bugcatcher/foo.clj
4. Calling `M-.` on `(bugcatcher/do-stuff)` immediately does not work. 
5. eval buffer with `C-c C-k`, and then `M-.` on the fn-call. This should take you to the temp file.

**Comment by bbatsov** [comment] 2017-09-17 11:37
I thought we fixed this problem ages ago https://github.com/clojure-emacs/cider/issues/1370

**Comment by bbatsov** [comment] 2017-09-17 11:38
In light of @sooheon's follow-up comment I guess we can close this. //cc @expez @benedekfazekas

**Closed by bbatsov** 2017-09-17 11:38 UTC
