### ISSUE TITLE
Cider jack-in failing with "error in process filter"

### ISSUE THREAD

**Issue by JvJ** [clojure-emacs/cider#1344] opened 2015-09-23 05:53 UTC
I've been having the following problem when attempting to jack into a cider repl.  It gives the below message instead of starting.  Is there a workaround for this issue?

Thanks

My cider version is CIDER 0.10.0snapshot (package: 20150922.412)
NREPL version: 0.2.10
Leiningen 2.5.3 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM

ERROR MESSAGE:
Starting nREPL server via lein repl :headless...
You can run the command ‘cider-jack-in’ with C-c M-j
Starting nREPL server via lein repl :headless...
nREPL server started on 51189
nREPL: Establishing direct connection to localhost:51189 ...
nREPL: Direct connection established
error in process filter: nrepl-log-message: Wrong number of arguments: (1 . 1), 0
error in process filter: Wrong number of arguments: (1 . 1), 0

**Comment by bbatsov** [comment] 2015-09-23 06:59
This is a duplicate of https://github.com/clojure-emacs/cider/issues/1343

**Closed by bbatsov** 2015-09-23 06:59 UTC
