### ISSUE TITLE
cider interaction with overtone is odd

### ISSUE THREAD

**Issue by bwanab** [clojure-emacs/cider#2737] opened 2019-10-27 16:08 UTC
This is probably more of a help request than a bug report.

My best guess is that the behavior I'm describing is simply a setting in cider that I've got wrong. It's a clean installation of emacs 26.3, using cider from melba packages.

I also know that if the reader is using a linux or windows machine, their might be additional setup to get the instrument to sound (jack for linux, I don't know what for windows), but I suspect the errant behavior will still exist even without getting the sound.

## Expected behavior

When I instantiate an overtone instrument using a terminal, it dutifully plays the note.

## Actual behavior

When I instantiate an overtone instrument using cider, it dutifully plays the note, but in addition it prints several thousand lines of data structure. This makes cider unusable for development of instruments.

#### from terminal:
```
lein new overtone-cider-problem
add this dependency to project.clj:
  		 [overtone "0.10.6"]
```
#### Project.clj now looks like:
```
(defproject overtone-cider-problem "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.0"]
  		 [overtone "0.10.6"]]
  :repl-options {:init-ns overtone-cider-problem.core})
 ```
```
cd overtone-cider-problem
lein repl
(require '[overtone.examples.getting-started.melody :as m])
nil
overtone-cider-problem.core=> (m/harpsichord)
```
#### the harpsichord will play an A440 and this line will print:
```
#<synth-node[loading]: overtone.example924/harpsichord 37>
```

#### from emacs where the current buffer is a file or dired in the overtone-cider-problem directory:
```
M-x cider-jack-in
require '[overtone.examples.getting-started.melody :as m])
(m/harpsichord)
```
#### the harpsichord will play A440, but in addition around 14000 lines get printed:
```
{:synth "overtone.example924/harpsichord",
 :id 37,
 :target 34,
 :position :tail,
 :args {"freq" 440.0},
 :sdef
 {:name "overtone.example924/harpsichord",
  :constants
  [0.0
   0
   2.0
   0.25
   16.0
   1.0
   1.25
   1.5
   -4
...
            {:doc "scales the levels of the breakpoints.",
             :name "level-scale",
             :default 1.0,
             :expands? true}
            {:doc "offsets the levels of the breakpoints.",
             :name "level-bias",
             :default 0.0,
             :expands? true}
            {:doc "scales the durations of the segments.",
             :name "time-scale",
             :default 1.0,
             :expands? true}
            {:doc
             "an integer representing an action to be executed\n                     when the env is fi
... output truncated to 1MB ...
overtone-cider-problem.core> 
```

 
### CIDER version information
```
;; Connected to nREPL server - nrepl://localhost:54850
;; CIDER 0.24.0snapshot (package: 20191009.1253), nREPL 0.6.0
;; Clojure 1.10.0, Java 11.0.5
```

### Lein/Boot version

 Leiningen 2.9.1 on Java 11.0.5 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2019-09-02
 
### Operating system

macOS High Sierra 10.13.6

**Comment by bbatsov** [comment] 2019-10-27 17:14
No idea why this is happening. I can't see a reason why you'd get different output in `lein repl` and CIDER's REPL. Perhaps @samaaron can shed some light on this?

**Comment by samaaron** [comment] 2019-10-27 17:21
This wasn’t the behaviour back when I maintained overtone. @hlolli is running things over there. Perhaps he made this change in behaviour?

**Comment by bwanab** [comment] 2019-10-27 18:09
Agreed, Sam. Until a couple of years ago I used this setup and it worked great. I’m getting back into both clojure and overtone so this is a bit of a surprise.

**Comment by hlolli** [comment] 2019-10-27 19:18
I've seen this being reported before, I did touch the print-method function some months ago, adding typehint to help the reflector

https://github.com/overtone/overtone/commit/79b671a85fdba68f56ac51d2d4f0bcf521a6b80f#diff-61a280267b5b5d17b97dae6343f95ae4L159

I wasn't able to reproduce this, but I'll look into it again.

**Comment by bwanab** [comment] 2019-10-27 19:48
Something I hadn't noticed previously that might be a clue. When I evaluate (m/harpsichord) in cider-nrepl, the following lines are repeated around 80 times in the *Messages* buffer:

error in process filter: clojure-string-start: Search failed: "\\(\\s-\\|^\\|#\\|(\\|\\[\\|{\\)\\(\"\\)"
error in process filter: Search failed: "\\(\\s-\\|^\\|#\\|(\\|\\[\\|{\\)\\(\"\\)"

**Comment by hlolli** [comment] 2019-10-27 19:52
Yes, I'm getting the exact same here. This error could be anything, so much string dump going on, that it could be the syntax highlighter searching for sexp-endings that aren't printed yet. But I'm trying to understand why the print-method is behaving like this, this data is the node-tree from the atom within the print-method, but as a perfectly valid clojure code, this shouldn't happen.

**Comment by bbatsov** [comment] 2019-10-27 19:58
Keep in mind that `clojure-mode` processes Clojure code with regular expressions and it can't really handle everything the Clojure reader would. I'm guessing there's something reasonably weird in the data that's causing that particular breakage.

**Comment by hlolli** [comment] 2019-10-27 21:22
There's a lot of archane code in these print-method in overtone, for example stuff like this

```Clojure
(let ....
i-name    (with-meta i-name (merge (meta i-name) {:type ::instrument}))
`(def ~i-name (inst ~i-name ~params ~ugen-form))
(defmethod print-method ::instrument  ...)
```

probably hasn't worked since pre Clojure 1.4 because of how vars are treated.

Nevertheless, I'm surprised to see this difference here in Cider, it obviously seems to work fine in cider-mode buffer, but inside a cider-repl-mode buffer is where it fails:

![cider_overtone](https://user-images.githubusercontent.com/6074754/67642008-b5b2ec00-f907-11e9-8ad5-0eaea7da53e7.jpg)

**Comment by hlolli** [comment] 2019-10-27 22:40
Anyway, after some experimentation and macro hacking, I need to research more this week, it could be newer Clojure version bug, but I don't think this is a cider bug, my gut tells me that this is coming from either a new bug or how Vars in defrecord are treated, or more specifically, how they are treated with the defrecord-ifn macro (which Inst class is coming from), for that I already have a ticket because of the 21 parameter limit, but if this is the problem causing it, I'll need to speed up that fix.

I'll leave this repl log that showcase why this is happening, and how the Var (which we want because we need the metadata) is lost in the instrument name harpsichord, but is bounded the the return value of the macro (which IS the instrument name) and how it's bounded to a new def. Totally strange

```Clojure

overtone.examples.getting-started.melody> (type (definst harpsichord [freq 440]
        (let [duration 1
              snd  (string freq duration)
              t1   (* 0.2 (string (* 2/1 freq) duration))
              t2   (* 0.15 (string (* 3/2 freq) duration))
              t3   (* 0.1 (string (* 4/3 freq) duration))
              t4   (* 0.1 (string (* 5/4 freq) duration))
              snd  (+ snd (mix [t1 t2 t3 t4]))]
          snd)))

clojure.lang.Var
overtone.examples.getting-started.melody> (type harpsichord)
overtone.studio.inst.Inst
overtone.examples.getting-started.melody> (meta (definst harpsichord [freq 440]
        (let [duration 1
              snd  (string freq duration)
              t1   (* 0.2 (string (* 2/1 freq) duration))
              t2   (* 0.15 (string (* 3/2 freq) duration))
              t3   (* 0.1 (string (* 4/3 freq) duration))
              t4   (* 0.1 (string (* 5/4 freq) duration))
              snd  (+ snd (mix [t1 t2 t3 t4]))]
          snd)))

{:line 70,
 :column 49,
 :file "*cider-repl supercollider/overtone:localhost:33705(clj)*",
 :name harpsichord,
 :ns #namespace[overtone.examples.getting-started.melody]}
overtone.examples.getting-started.melody> (meta harpsichord)
#:overtone.helpers.lib{:to-string
                       #function[overtone.examples.getting-started.melody/eval20890/fn--20920]}
overtone.examples.getting-started.melody> (def keeps-the-var-root?! (definst harpsichord [freq 440]
        (let [duration 1
              snd  (string freq duration)
              t1   (* 0.2 (string (* 2/1 freq) duration))
              t2   (* 0.15 (string (* 3/2 freq) duration))
              t3   (* 0.1 (string (* 4/3 freq) duration))
              t4   (* 0.1 (string (* 5/4 freq) duration))
              snd  (+ snd (mix [t1 t2 t3 t4]))]
          snd)))

#'overtone.examples.getting-started.melody/keeps-the-var-root?!
overtone.examples.getting-started.melody> (type keeps-the-var-root?!)
clojure.lang.Var
overtone.examples.getting-started.melody> (meta keeps-the-var-root?!)
{:line 88,
 :column 69,
 :file "*cider-repl supercollider/overtone:localhost:33705(clj)*",
 :name harpsichord,
 :ns #namespace[overtone.examples.getting-started.melody]}
overtone.examples.getting-started.melody> 
```

**Comment by hlolli** [comment] 2019-11-01 20:49
After testing older Cider versions with corresponding cider-nrepl releases, I can confirm that this problem was introduced between Riga-0.19.0 and Oslo-0.20.0

```Clojure
;; Connected to nREPL server - nrepl://localhost:36017
;; CIDER 0.19.0 (package: 20190926.701) (Raleigh), nREPL 0.5.3
;; Clojure 1.9.0, Java 11.0.3-internal
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
user> (require '[overtone.examples.getting-started.melody :as m])

--> Loading Overtone...
--> Booting internal SuperCollider server...
--> Connecting to internal SuperCollider server...
--> Connection established

    _____                 __
   / __  /_  _____  _____/ /_____  ____  ___
  / / / / | / / _ \/ ___/ __/ __ \/ __ \/ _ \
 / /_/ /| |/ /  __/ /  / /_/ /_/ / / / /  __/
 \____/ |___/\___/_/   \__/\____/_/ /_/\___/

   Collaborative Programmable Music. v0.10.6


Hello Hlolli, just take a moment to pause and focus your creative powers...

nil
user> (m/harpsichord)
#<synth-node[loading]: overtone.example924/harpsichord 37>
user> (m/harpsichord)
user> 
#<synth-node[loading]: overtone.example924/harpsichord 38>
user> :a
:a
```

Thanks to Alex Miller on clojurians to stop me from debugging the symbol/var thingy, it was a red herring.

Now going to find the bad commit...

**Comment by hlolli** [comment] 2019-11-01 21:10
Workaround (in case overtone users google it)

adding this to the emacs config prevents this



The bad "commit" is https://github.com/clojure-emacs/cider/commit/ecfea39a7f727ea8d607557a747d4f439422695b

For a fast solution just add

```
(setq cider-repl-use-pretty-printing nil)
```

I'll try to add custom dispatch for the pprinter to solve this indefinitely.

**Comment by bwanab** [comment] 2019-11-01 22:15
Thanks for your work on this Hlolli!

Bill

**Comment by hlolli** [comment] 2019-11-01 23:26
No problem!

I pushed a fix https://github.com/overtone/overtone/commit/2005bd7c40b8f348d615e61c0687c79143696a2c

Try out the latest changes trough the clojure command line tool by adding this to the deps.edn

```Clojure
{overtone/overtone {:git/url "https://github.com/overtone/overtone.git"
                    :sha "2005bd7c40b8f348d615e61c0687c79143696a2c"}}
```

I think we can close this now :)

**Comment by bbatsov** [comment] 2019-11-03 05:15
Thanks for tackling this! 🙇

**Closed by bbatsov** 2019-11-03 05:15 UTC
Labels: question
