### ISSUE TITLE
Behavior of the *cider-refresh-log* buffer is distracting

### ISSUE THREAD

**Issue by luxbock** [clojure-emacs/cider#1254] opened 2015-08-13 07:47 UTC
I usually only care about the results of calling `cider-refresh` if there was a problem. If there were no problems I would much rather just get a message in the mini-buffer. Right now the behavior of the `*cider-refresh-log*` buffer is to pop-up in the other-window, which is annoying because I was already using that buffer for something else I care about. I would therefore propose the following changes to the behavior of running `cider-refresh`:

- If there were no problems, log everything as usual but don't pop-up the log-buffer. Display a short message in the mini-buffer letting the user know that the reload was successful.
- If the reload failed, display the log-buffer in the current-window. This way the user can see what failed, and get rid of the buffer by pressing `q` without having to change windows.

**Comment by bbatsov** [comment] 2015-08-13 08:13
This is a duplicate of https://github.com/clojure-emacs/cider/issues/1239 //cc @cichli

**Closed by bbatsov** 2015-08-13 08:13 UTC

**Comment by cichli** [comment] 2015-08-17 13:56
@luxbock I've added `cider-refresh-show-log-buffer` now (defaults to `nil`) - let me know what you think next time you update?

**Comment by luxbock** [comment] 2015-08-20 08:16
Thanks! Works just as I had hoped.
