### ISSUE TITLE
`cider-refresh` messes up any `cider-scratch` buffer; `No namespace found`.

### ISSUE THREAD

**Issue by freckletonj** [clojure-emacs/cider#1879] opened 2016-11-14 21:10 UTC
## Expected behavior
`C-c C-x` / `cider-refresh` while in `cider-scratch` buffer simply refreshes the namespace, and any `def`d functions/vars get wiped out, but `cider-scratch` keeps working as if it were fresh.

## Actual behavior
`No namespace found` error

## Steps to reproduce the problem
1. `cider-scratch`
2. `cider-refresh`

## Environment & Version information
Clojure 1.9.0-alpha14

### CIDER version information

`Starting nREPL server via /home/x/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless...`
```

### Emacs version

Emacs 24.4.1

### Operating system

Ubuntu 14.04

**Comment by dpsutton** [comment] 2016-11-17 13:42
@freckletonj 
can you post some messages for me? When I'm using the refresh buffer, it seems to be in the namespace of my repl, which means my namespace is found.

```
(--> 
  ns  "fizzbuzz.core"
  op  "eval"
  session  "6f46166c-7edf-4355-bff1-b25c253d3ff2"
  code  #("(+ 1 1)" 0 1 (fontified t help-echo cider--help-echo cider-locals nil face (rainbow-delimiters-depth-1-face)) 1 6 (fontified t help-echo cider--help-echo cider-locals nil) 6 7 (fontified t help-echo cider--help-echo cider-locals nil face (rainbow-delimiters-depth-1-face)))
  file  "*cider-scratch*"
  line  9
  column  1
  id  "18"
)
(<-- 
  id  "18"
  ns  "fizzbuzz.core"
  session  "6f46166c-7edf-4355-bff1-b25c253d3ff2"
  value  "2"
)
```

This is the message going back and forth into nrepl. Here you can see its from *cider-scratch* and I'm evaluating `(+ 1 1)`. Is it possible that you can turn nrepl message logging on with `M-x nrepl-toggle-message-logging`? Then visit the buffer `*nrepl-messages <project>*.

We're looking for what namespace it *thinks* it is in to diagnose why its giving you the error that that namespace doesn't exist. As it stands, I can't reproduce this as my scratch buffer has the same namespace as my core file and it refreshes fine.

You can see the output of the refresh both in the nrepl messages buffer and in the emacs `*Messages*` buffer. Mine shows `cider-refresh: Reloading successful`.

Also, if you knew any/most/all of the above I don't mean to be condescending. But if its new to you know you know how to debug CIDER!.

**Comment by dpsutton** [comment] 2016-12-02 19:58
@freckletonj did you happen to have a chance to give a minimum example that can demonstrate this issue? I'm having trouble recreating it.

**Comment by freckletonj** [comment] 2016-12-02 20:55
I apologize for not getting back to you!

I just tried it again, and while I don't get the same error, there is an unusual behavior for a boot project, and not a lein project.

If I, ex, `(def a "hi")` within a `cider-scratch`, then delete it, and then `cider-refresh`, from a lein-based environment, refreshing now works as expected, complteley, and `a` cannot be found anymore, as expected. I can not resolve the bug I opened this ticket with, so it should be closed.

However, from a boot-based project, `cider-refresh` is not refreshing within `cider-scratch`, nor a normal namespace, ie, `cider-refresh` doesn't work at all, and strangely, neither does`C-c C-k / cider-load-buffer`. If I try that command, my computer focuses away from emacs (whereas it works as expected in `lein` projects). So, this isn't anything that has ever bugged me, I just noticed it now, while failing to recreate the original bug.

Thanks so much for your help, and hopefully my experiences aid the cause :)

**Comment by Malabarba** [comment] 2016-12-08 02:12
> If I try that command, my computer focuses away from emacs 

Well, that's a first for me. 😮

**Comment by dpsutton** [comment] 2017-01-07 21:41
@freckletonj is this still an issue or can we close this?

**Comment by bbatsov** [comment] 2018-09-23 05:05
Guess we can close it.

**Closed by bbatsov** 2018-09-23 05:05 UTC
